<?php $_items = $this->getReviewsCollection()->getItems(); ?>

<div id="customer-reviews">

  <?php if (count($_items)): ?>

    <h2>
      <?= $this->__('Customer Reviews') ?>
      <small><?= count($_items); ?> item(s)</small>
    </h2>

    <?= $this->getChildHtml('toolbar') ?>

    <?php foreach ($_items as $_review): ?>

      <div class="row">
        <div class="col-sm-4">
          <h5>
            <a href="<?= $this->getReviewUrl($_review->getId()) ?>">
              <?= $this->escapeHtml($_review->getTitle()) ?>
            </a>
          </h5>

          <?php $_votes = $_review->getRatingVotes(); ?>
          <?php if (count($_votes)): ?>
            <?php foreach ($_votes as $_vote): ?>
              <div>
                <?= $this->escapeHtml($_vote->getRatingCode()) ?>
                <?php
                echo $this->getLayout()
                  ->createBlock('core/template')
                  ->setTemplate('review/helper/rating.phtml')
                  ->setPercent($_vote->getPercent())
                  ->toHtml();
                ?>
              </div>
            <?php endforeach; ?>
          <?php endif; ?>
        </div>

        <div class="col-sm-8">
          <p><?= nl2br($this->escapeHtml($_review->getDetail())) ?></p>

          <p>
            <?= $this->__('Review by %s', $this->escapeHtml($_review->getNickname())) ?>
            /
            <?= $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?>

          <p>
        </div>
      </div>
    <?php endforeach; ?>

  <?php elseif ($this->getParentBlock()): ?>

    <?= $this->getParentBlock()->getReviewsSummaryHtml($this->getProduct(), 'short', true) ?>

  <?php endif; ?>

  <?= $this->getChildHtml('review_form') ?>

</div>
