<?php $_item = $this->getItem() ?>
<?php $_order = $this->getItem()->getOrderItem()->getOrder() ?>

<tr id="order-item-row-<?= $_item->getId() ?>">

  <td>
    <h4 class="product-name"><?= $this->escapeHtml($_item->getName()) ?></h4>

    <?php if ($_options = $this->getItemOptions()): ?>
      <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>

          <dt><?= $this->escapeHtml($_option['label']) ?></dt>

          <?php if (!$this->getPrintStatus()): ?>

            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
              <?= $_formatedOptionValue['value'] ?>
              <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="truncated_full_value">
                  <dl class="item-options">
                    <dt><?= $this->escapeHtml($_option['label']) ?></dt>
                    <dd><?= $_formatedOptionValue['full_view'] ?></dd>
                  </dl>
                </div>
              <?php endif; ?>
            </dd>

          <?php else: ?>

            <dd><?= $this->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>

          <?php endif; ?>

        <?php endforeach; ?>
      </dl>
    <?php endif; ?>

    <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
    <?php if ($addInfoBlock) : ?>
      <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
    <?php endif; ?>

    <?= $this->escapeHtml($_item->getDescription()) ?>

    <?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item->getOrderItem()) && $_item->getGiftMessageId()): ?>
      <a href="#"
         id="order-item-gift-message-link-<?= $_item->getId() ?>"
         class="js-gift-message-link"
         data-item-id="<?= $_item->getId() ?>">
        <?= $this->__('Gift Message') ?>
      </a>
    <?php endif; ?>

  </td>

  <td><?= $this->escapeHtml(Mage::helper('core/string')->splitInjection($this->getSku())) ?></td>

  <td><?= $_item->getQty() * 1 ?></td>

</tr>
