<?php /** @var $this Mage_Checkout_Block_Onepage_Shipping_Method_Available */ ?>

<?php $_shippingRateGroups = $this->getShippingRates(); ?>

<?php if (!$_shippingRateGroups): ?>

  <p class="text-info"><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>

<?php else: ?>

  <dl>
    <?php $_sole = count($_shippingRateGroups) == 1;

    foreach ($_shippingRateGroups as $code => $_rates): ?>

      <dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>

      <dd>
        <ul class="list-unstyled">
          <?php $_sole = $_sole && count($_rates) == 1;
          foreach ($_rates as $_rate): ?>

            <li>

              <?php if ($_rate->getErrorMessage()): ?>

                <p class="text-danger"><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></p>

              <?php else: ?>


                <div class="radio">
                  <label for="s_method_<?php echo $_rate->getCode() ?>">
                    <?php if ($_sole) : ?>

                      <input name="shipping_method"
                             class="hidden"
                             type="radio"
                             value="<?php echo $_rate->getCode() ?>"
                             data-price="<?php echo (float)$_rate->getPrice() ?>"
                             id="s_method_<?php echo $_rate->getCode() ?>"
                             checked="checked">

                    <?php else: ?>

                      <input name="shipping_method"
                             type="radio"
                             value="<?php echo $_rate->getCode() ?>"
                             data-price="<?php echo (float)$_rate->getPrice() ?>"
                             id="s_method_<?php echo $_rate->getCode() ?>"
                        <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                          checked="checked"
                          data-last-price="<?php echo (float)$_rate->getPrice() ?>"
                        <?php endif; ?>
                        >

                    <?php endif; ?>

                    <?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                    <?php echo $_excl; ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                      (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>
                  </label>
                </div>

              <?php endif ?>

            </li>

          <?php endforeach; ?>

        </ul>
      </dd>
    <?php endforeach; ?>

  </dl>
<?php endif; ?>

