<?php /* @var $this Mage_Sales_Block_Recurring_Profile_View */ ?>

<div class="order-page">



  <!-- title 'n' actions -->
  <div class="page-header">

    <h1><?= $this->__('Recurring Profile # %s', $this->escapeHtml($this->getReferenceId())) ?></h1>

    <?php if ($this->getCanCancel()): ?>
      <button type="button"
              title="<?= $this->__('Cancel') ?>"
              class="btn btn-danger"
              data-msg="<?= $this->getConfirmationMessage() ?>"
              data-url="<?= $this->getCancelUrl() ?>">
        <?= $this->__('Cancel') ?>
      </button>
    <?php endif; ?>

    <?php if ($this->getCanSuspend()): ?>
      <button type="button"
              title="<?= $this->__('Suspend') ?>"
              class="btn btn-warning"
              data-msg="<?= $this->getConfirmationMessage() ?>"
              data-url="<?= $this->getSuspendUrl() ?>">
        <?= $this->__('Suspend') ?>
      </button>
    <?php endif; ?>

    <?php if ($this->getCanActivate()): ?>
      <button type="button"
              title="<?= $this->__('Activate') ?>"
              class="btn btn-success"
              data-msg="<?= $this->getConfirmationMessage() ?>"
              data-url="<?= $this->getActivateUrl() ?>">
        <?= $this->__('Activate') ?>
      </button>
    <?php endif; ?>

    <?php if ($this->getCanUpdate()): ?>
      <button type="button"
              title="<?= $this->__('Get Update') ?>"
              class="btn btn-primary"
              data-msg="<?= $this->getConfirmationMessage() ?>"
              data-url="<?= $this->getUpdateUrl() ?>">
        <?= $this->__('Get Update') ?>
      </button>
    <?php endif; ?>
  </div>

  <!-- info tabs -->
  <p><?= $this->__('About This Profile:') ?></p>

  <?php $infoTabs = $this->getChildGroup('info_tabs'); ?>
  <ul id="order-info-tabs" class="nav nav-pills">
    <?php foreach ($infoTabs as $block): ?>
      <li role="presentation"
          <?php if ($this->getObjectData($block, 'is_view_current')): ?>class="active"<?php endif ?>
        >
        <a href="<?= $this->escapeHtml($this->getObjectData($block, 'view_url')) ?>">
          <?= $this->escapeHtml($this->getObjectData($block, 'view_label')) ?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>

  <!-- info blocks in 2 columns -->
  <?php for ($i = 1; $i <= 5; $i++): ?>
    <?php $infoBlocks = $this->getChildGroup("info_blocks_row_{$i}"); ?>
    <?php if ($infoBlocks): ?>
      <div class="row">
        <?php for ($j = 1; $j <= 2; $j++): ?>
          <?php foreach ($infoBlocks as $alias => $block): ?>
            <?php if ($j == $this->getObjectData($block, 'view_column')): ?>
              <div class="col-md-6">

                  <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h2 class="panel-title">
                      <?= $this->escapeHtml($this->getObjectData($block, 'view_label')) ?>
                    </h2>
                  </div>

                  <?php $html = $this->getChildHtml($alias) ?>
                  <?php if ($html) : ?>

                    <?= $html ?>

                  <?php else : ?>

                    <div class="panel-body">
                      <?= $this->__('No information available.'); ?>
                    </div>

                  <?php endif ?>

                </div>

              </div>
            <?php endif; ?>
          <?php endforeach; ?>
        <?php endfor; ?>
      </div>
    <?php endif; ?>
  <?php endfor; ?>

  <!-- table data block -->
  <?php $table = $this->getChild('table') ?>
  <?php if ($table): ?>
    <div>
      <h2><?= $this->escapeHtml($this->getObjectData($table, 'view_label')) ?></h2>
      <?= $this->getChildHtml('table') ?>
    </div>
  <?php endif; ?>

  <a href="<?= $this->getBackUrl() ?>" class="btn btn-default">
        <?= Mage::helper('vr_kiwiberry')->getSvgIcon('chevron-left') ?>
    <?= $this->__('Back to Recurring Profiles') ?>
  </a>
</div>
