<?php
$_filter = $this->getFilter();
$_label = $this->stripTags($_filter->getLabel());

$_swatchInnerWidth = $this->getSwatchInnerWidth();
$_swatchInnerHeight = $this->getSwatchInnerHeight();

$_swatchUrl = $this->getSwatchUrl();
?>

<li class="list-group-item">

  <strong><?= $this->__($_filter->getName()) ?>:</strong>
  <img src="<?= $_swatchUrl; ?>"
       alt="<?= $_label; ?>"
       title="<?= $_label ?>"
       width="<?= $_swatchInnerWidth ?>"
       height="<?= $_swatchInnerHeight ?>"/>

  <?php
  $clearLinkUrl = $_filter->getClearLinkUrl();
  if ($clearLinkUrl):
    ?>
    <a href="<?= $_filter->getRemoveUrl() ?>"
       title="<?= $this->__('Previous') ?>"><?= $this->__('Previous') ?></a>

    <a title="<?= $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
       href="<?= $clearLinkUrl ?>"><?= $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></a>
  <?php else: ?>
    <a class="close"
       href="<?= $_filter->getRemoveUrl() ?>"
       title="<?= $this->__('Remove This Item') ?>">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only"><?= $this->__('Remove This Item') ?></span>
    </a>
  <?php endif; ?>

</li>
