<?php if (!empty($collection) && $collection->getSize()): ?>
  <?php foreach ($collection as $_rating): ?>
    <?php if ($_rating->getSummary()): ?>

      <div>
        <?= $this->__($this->escapeHtml($_rating->getRatingCode())) ?>
        <?php
        echo $this->getLayout()
          ->createBlock('core/template')
          ->setTemplate('review/helper/rating.phtml')
          ->setPercent($_rating->getSummary())
          ->toHtml();
        ?>
      </div>

    <?php endif; ?>
  <?php endforeach; ?>
<?php endif; ?>
