<footer>

  <div class="row">
    <div class="col-sm-2">
      <?php echo $this->getChildHtml('cms_footer_links') ?>
    </div>
    <div class="col-sm-2">
      <?php echo $this->getChildHtml('footer_links') ?>
    </div>
    <div class="col-sm-2">
      <?php echo $this->getChildHtml('footer_links2') ?>
    </div>
    <div class="col-sm-2">
      <?php echo $this->getChildHtml('cms_footer_links_sm') ?>
    </div>
    <div class="col-sm-4">
      <?php echo $this->getChildHtml('newsletter') ?>
    </div>
  </div>

  <address><?php echo $this->getCopyright() ?></address>
</footer>
