<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<!--<header class="">-->
<!--  <h1 class="header-logo">-->
<!--    <a href="--><?php //echo $this->getUrl('') ?><!--" title="--><?php //echo $this->getLogoAlt() ?><!--">-->
<!--      <strong class="sr-only">--><?php //echo $this->getLogoAlt() ?><!--</strong>-->
<!--      <img class="logo" src="--><?php //echo $this->getLogoSrc() ?><!--" alt="--><?php //echo $this->getLogoAlt() ?><!--" />-->
<!--    </a>-->
<!--    <small>--><?php //echo $this->getChildHtml('welcome') ?><!-- --><?php //echo $this->getAdditionalHtml() ?><!--</small>-->
<!--  </h1>-->
<!---->
<!--  <div class="header-links">-->
<!--    --><?php //echo $this->getChildHtml('topLinks') ?>
<!--    --><?php //echo $this->getChildHtml('store_language') ?>
<!--  </div>-->
<!--</header>-->

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle Account</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-2">
        <span class="sr-only">Toggle Category</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>">
        <strong class="sr-only"><?php echo $this->getLogoAlt() ?></strong>
        <img class="logo" src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
      </a>
      <p class="navbar-text"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?></p>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-2">
      <?php echo $this->getChildHtml('topLinks') ?>
      <?php echo $this->getChildHtml('store_language') ?>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-category" id="navbar-collapse">
      <?php echo $this->getChildHtml('topMenu') ?>
      <?php echo $this->getChildHtml('topSearch') ?>
    </div>
  </div>
</nav>

<?php echo $this->getChildHtml('topContainer'); ?>
