<input
  id="dont_display_container"
  type="hidden"
  value="<?php echo $this->getDontDisplayContainer() ? 1 : 0 ?>"
  data-additional-url="<?php echo $this->escapeHtml($this->getAdditionalUrl()) ?>"
  >

<?php if ($this->isMessagesAvailable() || $this->isItemsAvailable()): ?>

  <?php switch ($this->getType()):
    case 'onepage_checkout':
      ?>

      <h3><?php echo $this->__('Do you have any gift items in your order?'); ?></h3>

      <div class="checkbox">
        <label for="allow_gift_messages">
          <input type="checkbox"
                 name="allow_gift_messages"
                 id="allow_gift_messages"
                 value="1"
                 class="checkbox"
                 <?php if ($this->getItemsHasMesssages() || $this->getEntityHasMessage()): ?>checked="checked"<?php endif; ?>
            >
          <?php echo $this->__('Add gift options.') ?>
        </label>
      </div>

      <div class="gift-messages-form"
           id="allow-gift-message-container"
           <?php if (!$this->getItemsHasMesssages() && !$this->getEntityHasMessage()): ?>style="display:none;"<?php endif; ?>
        >

        <?php if ($this->isMessagesAvailable()): ?>
          <h4><?php echo $this->__('Gift Options for the Entire Order.'); ?></h4>

          <div class="checkbox">
            <label for="allow_gift_messages_for_order">
              <input type="checkbox"
                     name="allow_gift_messages_for_order"
                     id="allow_gift_messages_for_order"
                     value="1"
                     class="checkbox"
                     <?php if ($this->getEntityHasMessage()): ?>checked="checked"<?php endif; ?>
                >
              <?php echo $this->__('Add gift options for the Entire Order') ?>
            </label>
          </div>

          <div class="allow-gift-messages-for-order-container"
               id="allow-gift-messages-for-order-container"
               <?php if (!$this->getEntityHasMessage()): ?>style="display:none"<?php endif; ?>
            >

            <p class="text-info">
              <?php echo $this->__('You can leave this box blank if you do not wish to add a gift message for whole order.') ?>
            </p>

            <input type="hidden" name="giftmessage[<?php echo $this->getEntity()->getId() ?>][type]" value="quote">

            <?php
            $msg = $this->getMessage()->getMessage();
            $requiredClass = (ctype_space($msg) || $msg == '') ? '' : ' required-entry';
            ?>

            <div class="form-group">
              <label for="gift-message-whole-from"><?php echo $this->__('From') ?></label>
              <input type="text"
                     name="giftmessage[<?php echo $this->getEntity()->getId() ?>][from]"
                     id="gift-message-whole-from"
                     title="<?php echo $this->__('From') ?>"
                     value="<?php echo $this->getEscaped($this->getMessage()->getSender(), $this->getDefaultFrom()) ?>"
                     class="form-control input-text validation-passed<?php echo $requiredClass ?>">
            </div>

            <div class="form-group">
              <label for="gift-message-whole-to"><?php echo $this->__('To') ?></label>
              <input type="text"
                     name="giftmessage[<?php echo $this->getEntity()->getId() ?>][to]"
                     id="gift-message-whole-to"
                     title="<?php echo $this->__('To') ?>"
                     value="<?php echo $this->getEscaped($this->getMessage()->getRecipient(), $this->getDefaultTo()) ?>"
                     class="form-control input-text validation-passed<?php echo $requiredClass ?>">
            </div>

            <div class="form-group">
              <label for="gift-message-whole-message"><?php echo $this->__('Message') ?></label>
              <textarea id="gift-message-whole-message"
                        class="form-control validation-passed giftmessage-area"
                        name="giftmessage[<?php echo $this->getEntity()->getId() ?>][message]"
                        title="<?php echo $this->__('Message') ?>"
                        rows="5">
                <?php echo $this->getEscaped($this->getMessage()->getMessage()) ?>
              </textarea>
            </div>

          </div>
        <?php endif; ?>

        <?php if ($this->isItemsAvailable()): ?>
          <h4><?php echo $this->__('Gift Options for Individual Items'); ?></h4>

          <div class="checkbox">
            <label for="allow_gift_messages_for_items">
              <input type="checkbox"
                     name="allow_gift_messages_for_items"
                     id="allow_gift_messages_for_items"
                     value="1"
                     class="checkbox"
                     <?php if ($this->getItemsHasMesssages()): ?>checked="checked"<?php endif; ?>
                >
              <?php echo $this->__('Add gift options for Individual Items') ?>
            </label>
          </div>

          <div id="allow-gift-messages-for-items-container"
               <?php if (!$this->getItemsHasMesssages()): ?>style="display:none;"<?php endif; ?>
            >

            <p class="text-info"><?php echo $this->__('You can leave this box blank if you do not wish to add a gift message for the item.') ?></p>

            <ul class="media-list">
              <?php foreach ($this->getItems() as $_index => $_item): ?>

                <?php $_product = $_item->getProduct() ?>
                <li class="media js-item">

                  <div class="pull-left">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(75); ?>"
                         class="media-object"
                         alt="<?php echo $this->escapeHtml($_product->getName()) ?>"
                         title="<?php echo $this->escapeHtml($_product->getName()) ?>"/>

                    <p><?php echo $this->__('Item %d of %d', $_index + 1, $this->countItems()) ?></p>
                  </div>

                  <div class="media-body">
                    <h5 class="media-heading"><?php echo $this->escapeHtml($_product->getName()) ?></h5>

                    <input type="hidden"
                           name="giftmessage[<?php echo $_item->getId() ?>][type]"
                           value="quote_item">

                    <?php
                    $msg = $this->getMessage($_item)->getMessage();
                    $requiredClass = (ctype_space($msg) || $msg == '') ? '' : ' required-entry';
                    ?>

                    <div class="form-group">
                      <label for="gift-message-<?php echo $_item->getId() ?>-from"><?php echo $this->__('From') ?></label>
                      <input type="text"
                             name="giftmessage[<?php echo $_item->getId() ?>][from]"
                             id="gift-message-<?php echo $_item->getId() ?>-from"
                             title="<?php echo $this->__('From') ?>"
                             value="<?php echo $this->getEscaped($this->getMessage($_item)->getSender(), $this->getDefaultFrom()) ?>"
                             class="form-control input-text validation-passed<?php echo $requiredClass ?>">
                    </div>

                    <div class="form-group">
                      <label for="gift-message-<?php echo $_item->getId() ?>-to"><?php echo $this->__('To') ?></label>
                      <input type="text"
                             name="giftmessage[<?php echo $_item->getId() ?>][to]"
                             id="gift-message-<?php echo $_item->getId() ?>-to"
                             title="<?php echo $this->__('To') ?>"
                             value="<?php echo $this->getEscaped($this->getMessage($_item)->getRecipient(), $this->getDefaultTo()) ?>"
                             class="form-control input-text validation-passed<?php echo $requiredClass ?>">
                    </div>

                    <div class="form-group">
                      <label for="gift-message-<?php echo $_item->getId() ?>-message"><?php echo $this->__('Message') ?></label>
                      <textarea id="gift-message-<?php echo $_item->getId() ?>-message"
                                class="form-control validation-passed giftmessage-area"
                                name="giftmessage[<?php echo $_item->getId() ?>][message]"
                                title="<?php echo $this->__('Message') ?>"
                                rows="5"><?php
                        echo $this->getEscaped($this->getMessage($_item)->getMessage())
                        ?></textarea>
                    </div>
                  </div>

                </li>
              <?php endforeach; ?>
            </ul>

          </div>
        <?php endif; ?>

      </div>

      <?php break; ?>

    <?php
    case 'multishipping_adress_checkbox':
      break;
    case 'multishipping_adress':
      ?>
      <div class="gift-messages">
        <h3><?php echo $this->__('Do you have any gift items in your order?'); ?></h3>

        <p class="control">
          <input type="checkbox"
                 name="allow_gift_messages_<?php echo $this->getEntity()->getId() ?>"
                 id="allow_gift_messages_<?php echo $this->getEntity()->getId() ?>"
                 value="1"
                 onclick="toogleVisibilityOnObjects(this, ['allow-gift-message-container-<?php echo $this->getEntity()->getId() ?>']);"<?php if ($this->getItemsHasMesssages() || $this->getEntityHasMessage()): ?> checked="checked"<?php endif ?>
                 class="checkbox"/>
          <label for="allow_gift_messages_<?php echo $this->getEntity()->getId() ?>"><?php echo $this->__('Add gift options') ?></label>
        </p>
      </div>
      <div class="gift-messages-form" id="allow-gift-message-container-<?php echo $this->getEntity()->getId() ?>">
        <div class="inner-box">
          <?php if ($this->isMessagesAvailable()): ?>
            <h4><?php echo $this->__('Gift Options for this address.'); ?></h4>
            <p>
              <input type="checkbox"
                     name="allow_gift_messages_for_order_<?php echo $this->getEntity()->getId() ?>"
                     id="allow_gift_messages_for_order_<?php echo $this->getEntity()->getId() ?>"
                     value="1"
                     onclick="toogleVisibilityOnObjects(this, ['allow-gift-messages-for-order-container-<?php echo $this->getEntity()->getId() ?>']);"<?php if ($this->getEntityHasMessage()): ?> checked="checked"<?php endif; ?>
                     class="checkbox"/>
              <label for="allow_gift_messages_for_order"><?php echo $this->__('Add gift options for the Entire Order') ?></label>
            </p>
            <div id="allow-gift-messages-for-order-container-<?php echo $this->getEntity()->getId() ?>">
              <p><?php echo $this->__('You can leave this box blank if you do not wish to add a gift message for this address.') ?></p>
              <input type="hidden"
                     name="giftmessage[<?php echo $this->getEntity()->getId() ?>][type]"
                     value="quote_address"/>
              <ul class="form-list">
                <li class="fields">
                  <div class="field">
                    <label for="gift-message-<?php echo $this->getEntity()->getId() ?>-from"><?php echo $this->__('From') ?></label>

                    <div class="input-box">
                      <input type="text"
                             name="giftmessage[<?php echo $this->getEntity()->getId() ?>][from]"
                             id="gift-message-<?php echo $this->getEntity()->getId() ?>-from"
                             title="<?php echo $this->__('From') ?>"
                             value="<?php echo $this->getEscaped($this->getMessage()->getSender(), $this->getDefaultFrom()) ?>"
                             class="input-text validation-passed"/>
                    </div>
                  </div>
                  <div class="field">
                    <label for="gift-message-<?php echo $this->getEntity()->getId() ?>-to"><?php echo $this->__('To') ?></label>

                    <div class="input-box">
                      <input type="text"
                             name="giftmessage[<?php echo $this->getEntity()->getId() ?>][to]"
                             id="gift-message-<?php echo $this->getEntity()->getId() ?>-to"
                             title="<?php echo $this->__('To') ?>"
                             value="<?php echo $this->getEscaped($this->getMessage()->getRecipient(), $this->getDefaultTo()) ?>"
                             class="input-text validation-passed"/>
                    </div>
                  </div>
                </li>
                <li class="wide">
                  <label for="gift-message-<?php echo $this->getEntity()->getId() ?>-message"><?php echo $this->__('Message') ?></label>

                  <div class="input-box">
                    <textarea id="gift-message-<?php echo $this->getEntity()->getId() ?>-message"
                              onchange="toogleRequired('gift-message-<?php echo $this->getEntity()->getId() ?>-message', ['gift-message-<?php echo $this->getEntity()->getId() ?>-from','gift-message-<?php echo $this->getEntity()->getId() ?>-to'])"
                              class="input-text validation-passed giftmessage-area"
                              name="giftmessage[<?php echo $this->getEntity()->getId() ?>][message]"
                              title="<?php echo $this->__('Message') ?>"
                              rows="5"
                              cols="40"><?php
                      echo $this->getEscaped($this->getMessage()->getMessage())
                      ?></textarea>
                  </div>
                </li>
              </ul>
              <script type="text/javascript">
                //<![CDATA[
                var shippingMethod = new VarienForm('shipping_method_form');
                toogleRequired('gift-message-<?php echo $this->getEntity()->getId() ?>-message', ['gift-message-<?php echo $this->getEntity()->getId() ?>-from', 'gift-message-<?php echo $this->getEntity()->getId() ?>-to']);
                //]]>
              </script>
            </div>
          <?php endif; ?>
          <?php if ($this->isItemsAvailable()): ?>
            <h4><?php echo $this->__('Gift Options for Individual Items'); ?></h4>
            <p>
              <input type="checkbox"
                     name="allow_gift_messages_for_items_<?php echo $this->getEntity()->getId() ?>"
                     id="allow_gift_messages_for_items_<?php echo $this->getEntity()->getId() ?>"
                     value="1"
                     onclick="toogleVisibilityOnObjects(this, ['allow-gift-messages-for-items-container-<?php echo $this->getEntity()->getId() ?>']);"<?php if ($this->getItemsHasMesssages()): ?> checked="checked"<?php endif; ?>
                     class="checkbox"/>
              <label for="allow_gift_messages_for_items_<?php echo $this->getEntity()->getId() ?>"><?php echo $this->__('Add gift options for Individual Items') ?></label>
            </p>
            <div id="allow-gift-messages-for-items-container-<?php echo $this->getEntity()->getId() ?>">
              <p><?php echo $this->__('You can leave this box blank if you do not wish to add a gift message for the item.') ?></p>
              <ol>
                <?php foreach ($this->getItems() as $_index => $_item): ?>
                  <?php $_product = $_item->getProduct() ?>
                  <li class="item">
                    <div class="product-img-box">
                      <p class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(75); ?>"
                             width="75"
                             height="75"
                             alt="<?php echo $this->escapeHtml($_product->getName()) ?>"
                             title="<?php echo $this->escapeHtml($_product->getName()) ?>"/></p>

                      <p class="number"><?php echo $this->__('Item %d of %d', $_index + 1, $this->countItems()) ?></p>
                    </div>
                    <div class="details">
                      <div class="f-fix">
                        <input type="hidden"
                               name="giftmessage[<?php echo $_item->getId() ?>][type]"
                               value="quote_address_item"/>
                        <input type="hidden"
                               name="giftmessage[<?php echo $_item->getId() ?>][address]"
                               value="<?php echo $this->getEntity()->getId() ?>"/>
                        <h5 class="product-name"><?php echo $this->escapeHtml($_product->getName()) ?></h5>
                        <ul class="form-list">
                          <li class="fields">
                            <div class="field">
                              <label for="gift-message-<?php echo $_item->getId() ?>-from"><?php echo $this->__('From') ?></label>

                              <div class="input-box">
                                <input type="text"
                                       name="giftmessage[<?php echo $_item->getId() ?>][from]"
                                       id="gift-message-<?php echo $_item->getId() ?>-from"
                                       title="<?php echo $this->__('From') ?>"
                                       value="<?php echo $this->getEscaped($this->getMessage($_item)->getSender(), $this->getDefaultFrom()) ?>"
                                       class="input-text validation-passed"/>
                              </div>
                            </div>
                            <div class="field">
                              <label for="gift-message-<?php echo $_item->getId() ?>-to"><?php echo $this->__('To') ?></label>

                              <div class="input-box">
                                <input type="text"
                                       name="giftmessage[<?php echo $_item->getId() ?>][to]"
                                       id="gift-message-<?php echo $_item->getId() ?>-to"
                                       title="<?php echo $this->__('To') ?>"
                                       value="<?php echo $this->getEscaped($this->getMessage($_item)->getRecipient(), $this->getDefaultTo()) ?>"
                                       class="input-text validation-passed"/>
                              </div>
                            </div>
                          </li>
                          <li class="wide">
                            <label for="gift-message-<?php echo $_item->getId() ?>-message"><?php echo $this->__('Message') ?></label>

                            <div class="input-box">
                              <textarea id="gift-message-<?php echo $_item->getId() ?>-message"
                                        onchange="toogleRequired('gift-message-<?php echo $_item->getId() ?>-message', ['gift-message-<?php echo $_item->getId() ?>-from','gift-message-<?php echo $_item->getId() ?>-to'])"
                                        class="input-text validation-passed  giftmessage-area"
                                        name="giftmessage[<?php echo $_item->getId() ?>][message]"
                                        title="<?php echo $this->__('Message') ?>"
                                        rows="5"
                                        cols="10"><?php echo $this->getEscaped($this->getMessage($_item)->getMessage()) ?></textarea>
                            </div>
                          </li>
                        </ul>
                        <script type="text/javascript">
                          //<![CDATA[
                          toogleRequired('gift-message-<?php echo $_item->getId() ?>-message', ['gift-message-<?php echo $_item->getId() ?>-from', 'gift-message-<?php echo $_item->getId() ?>-to']);
                          //]]>
                        </script>
                      </div>
                    </div>
                  </li>
                <?php endforeach; ?>
              </ol>
            </div>
          <?php endif; ?>
        </div>
      </div>
      <script type="text/javascript">
        //<![CDATA[
        toogleVisibilityOnObjects('allow_gift_messages_<?php echo $this->getEntity()->getId() ?>', ['allow-gift-message-container-<?php echo $this->getEntity()->getId() ?>']);
        toogleVisibilityOnObjects('allow_gift_messages_for_order_<?php echo $this->getEntity()->getId() ?>', ['allow-gift-messages-for-order-container-<?php echo $this->getEntity()->getId() ?>']);
        toogleVisibilityOnObjects('allow_gift_messages_for_items_<?php echo $this->getEntity()->getId() ?>', ['allow-gift-messages-for-items-container-<?php echo $this->getEntity()->getId() ?>']);
        //]]>
      </script>
      <?php break; ?>
    <?php endswitch ?>
<?php endif; ?>
