<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>

<div class="page-header">
  <h1><?php echo $this->__('Address Book') ?></h1>
</div>

<a title="<?php echo $this->__('Add New Address') ?>"
   class="btn btn-default"
   href="<?php echo $this->getAddAddressUrl() ?>">
  <?php echo $this->__('Add New Address') ?>
</a>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="row">

  <div class="col-md-6">

    <h2><?php echo $this->__('Default Addresses') ?></h2>


    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->__('Default Billing Address') ?></h3>
      </div>

      <?php if ($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>

        <div class="panel-body">
          <address>
            <?php
            echo $this->getAddressHtml(Mage::getSingleton('customer/session')
              ->getCustomer()
              ->getAddressById($_pAddsses))
            ?>
          </address>
        </div>

        <div class="panel-footer">
          <a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')
            ->getCustomer()
            ->getAddressById($_pAddsses)) ?>"
            >
            <?php echo $this->__('Change Billing Address') ?>
          </a>
        </div>

      <?php else: ?>

        <div class="panel-body">
          <?php echo $this->__('You have no default billing address in your address book.') ?>
        </div>

      <?php endif ?>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->__('Default Shipping Address') ?></h3>
      </div>

      <?php if ($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>

        <div class="panel-body">
          <address>
            <?php
            echo $this->getAddressHtml(Mage::getSingleton('customer/session')
              ->getCustomer()
              ->getAddressById($_pAddsses))
            ?>
          </address>
        </div>

        <div class="panel-footer">
          <a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')
            ->getCustomer()->getAddressById($_pAddsses)) ?>"
            >
            <?php echo $this->__('Change Shipping Address') ?>
          </a>
        </div>

      <?php else: ?>

        <div class="panel-body">
          <?php echo $this->__('You have no default shipping address in your address book.') ?>
        </div>

      <?php endif ?>
    </div>

  </div>

  <div class="col-md-6">

    <h2><?php echo $this->__('Additional Address Entries') ?></h2>

    <?php if ($_pAddsses = $this->getAdditionalAddresses()): ?>

      <ul class="list-group">
        <?php foreach ($_pAddsses as $_address): ?>
          <li class="list-group-item">
            <address>
              <?php echo $this->getAddressHtml($_address) ?>
            </address>
            <p>
              <a href="<?php echo $this->getUrl('customer/address/edit', array('id' => $_address->getId())) ?>"
                 class="btn btn-default"
                >
                <?php echo $this->__('Edit Address') ?>
              </a>
              <a href="<?php echo $this->getUrl('customer/address/delete', array('id' => $_address->getId())) ?>"
                 class="btn btn-danger js-delete-address"
                >
                <?php echo $this->__('Delete Address') ?>
              </a>

            </p>
          </li>
        <?php endforeach; ?>
      </ul>

    <?php else: ?>

      <p class="text-info"><?php echo $this->__('You have no additional address entries in your address book.') ?></p>

    <?php endif ?>

  </div>

</div>

<a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="btn btn-default">
  <?php echo $this->__('Back') ?>
</a>
