<?php
/**
 * Edit customer address template
 *
 * @see Mage_Customer_Block_Address_Edit
 */
?>

<?php if ($this->getTitle()): ?>
  <div class="page-header">
    <h1><?= $this->getTitle() ?></h1>
  </div>
<?php endif; ?>



<form action="<?= $this->getSaveUrl() ?>"
      method="post"
      id="form-validate-address-edit"
      role="form"
      enctype="multipart/form-data"
      class="js-validate-form"
      data-regions="<?= $this->escapeHtml($this->helper('directory')->getRegionJsonByStore()) ?>"
  >

  <?= $this->getBlockHtml('formkey') ?>

  <input type="hidden" name="success_url" value="<?= $this->getSuccessUrl() ?>"/>
  <input type="hidden" name="error_url" value="<?= $this->getErrorUrl() ?>"/>

  <p class="text-danger"><?= $this->__('* Required Fields') ?></p>

  <div class="row">
    <div class="col-md-6">

      <h2><?= $this->__('Contact Information') ?></h2>

      <?= $this->getNameBlockHtml() ?>

      <div class="form-group">
        <label for="company"><?= $this->__('Company') ?></label>
        <input type="text"
               name="company"
               id="company"
               title="<?= $this->__('Company') ?>"
               value="<?= $this->escapeHtml($this->getAddress()->getCompany()) ?>"
               class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('company') ?>">
      </div>

      <div class="form-group">
        <label for="telephone" class="required"><?= $this->__('Telephone') ?></label>
        <input type="tel"
               name="telephone"
               value="<?= $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
               title="<?= $this->__('Telephone') ?>"
               class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>"
               id="telephone">
      </div>

      <div class="form-group">
        <label for="fax"><?= $this->__('Fax') ?></label>
        <input type="tel"
               name="fax"
               id="fax"
               title="<?= $this->__('Fax') ?>"
               value="<?= $this->escapeHtml($this->getAddress()->getFax()) ?>"
               class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('fax') ?>">
      </div>

    </div>
    <div class="col-md-6">

      <h2><?= $this->__('Address') ?></h2>

      <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
      <div class="form-group">
        <label for="street_1" class="required"><?= $this->__('Street Address') ?></label>
        <input type="text"
               name="street[]"
               value="<?= $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
               title="<?= $this->__('Street Address') ?>"
               id="street_1"
               class="form-control <?= $_streetValidationClass ?>">
      </div>

      <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
      <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
        <div class="form-group">
          <label for="billing:street<?= $_i ?>"><?= $this->__('Street Address %s', $_i) ?></label>
          <input type="text"
                 name="street[]"
                 value="<?= $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
                 title="<?= $this->__('Street Address %s', $_i) ?>"
                 id="street_<?= $_i ?>"
                 class="form-control <?= $_streetValidationClass ?>">
        </div>
      <?php endfor; ?>

      <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
        <div class="form-group">
          <label for="vat_id"><?= $this->__('VAT Number') ?></label>
          <input type="text"
                 name="vat_id"
                 value="<?= $this->escapeHtml($this->getAddress()->getVatId()) ?>"
                 title="<?= $this->__('VAT Number') ?>"
                 id="vat_id"
                 class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>">
        </div>
      <?php endif; ?>

      <div class="form-group">
        <label for="city" class="required"><?= $this->__('City') ?></label>
        <input type="text"
               name="city"
               value="<?= $this->escapeHtml($this->getAddress()->getCity()) ?>"
               title="<?= $this->__('City') ?>"
               class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
               id="city">
      </div>

      <div class="form-group">
        <label for="region_id" class="required"><?= $this->__('State/Province') ?></label>

        <select id="region_id"
                name="region_id"
                title="<?= $this->__('State/Province') ?>"
                class="validate-select form-control"
                defaultValue="<?= $this->getAddress()->getRegionId() ?>"
                style="display:none;">
          <option value=""><?= $this->__('Please select region, state or province') ?></option>
        </select>

        <input type="text"
               id="region"
               name="region"
               value="<?= $this->escapeHtml($this->getAddress()->getRegion()) ?>"
               title="<?= $this->__('State/Province') ?>"
               class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('region') ?>">
      </div>

      <div class="form-group">
        <label for="zip" class="required"><?= $this->__('Zip/Postal Code') ?></label>

        <input type="text"
               name="postcode"
               value="<?= $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
               title="<?= $this->__('Zip/Postal Code') ?>"
               id="zip"
               class="form-control validate-zip-international <?= $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>">
      </div>

      <div class="form-group">
        <label for="country" class="required"><?= $this->__('Country') ?></label>
        <?= $this->getCountryHtmlSelect() ?>
      </div>
    </div>

  </div>

  <?php if ($this->isDefaultBilling()): ?>

    <p class="form-control-static">
      <?= $this->__('Default Billing Address') ?>
    </p>

  <?php elseif ($this->canSetAsDefaultBilling()): ?>

    <div class="checkbox">
      <label>
        <input type="checkbox"
               id="primary_billing"
               name="default_billing"
               value="1"
               title="<?= $this->__('Use as My Default Billing Address') ?>"
          >
        <?= $this->__('Use as my default billing address') ?>
      </label>
    </div>

    <?php
  else: ?>

    <input type="hidden" name="default_billing" value="1">

  <?php endif; ?>

  <?php if ($this->isDefaultShipping()): ?>

    <p class="form-control-static">
      <?= $this->__('Default Shipping Address') ?>
    </p>

  <?php elseif ($this->canSetAsDefaultShipping()): ?>

    <div class="checkbox">
      <label>
        <input type="checkbox"
               id="primary_shipping"
               name="default_shipping"
               value="1"
               title="<?= $this->__('Use as My Default Shipping Address') ?>"
          >
        <?= $this->__('Use as my default shipping address') ?>
      </label>
    </div>

    <?php
  else: ?>

    <input type="hidden" name="default_shipping" value="1">

  <?php endif; ?>

  <a href="<?= $this->escapeUrl($this->getBackUrl()) ?>" class="btn btn-default">
    <?= $this->__('Back') ?>
  </a>

  <button type="submit" title="<?= $this->__('Save Address') ?>" class="btn btn-default">
    <?= $this->__('Save Address') ?>
  </button>

</form>
