<?php if ($this->getReviewsCount()): ?>

  <div class="ratings">
    <?php
    if ($this->getRatingSummary()):
      echo $this->getLayout()
        ->createBlock('core/template')
        ->setTemplate('review/helper/rating.phtml')
        ->setPercent($this->getRatingSummary())
        ->toHtml();
    endif;
    ?>

    <div class="btn-group">
      <a class="btn btn-default" href="<?php echo $this->getReviewsUrl() ?>">
        <?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?>
      </a>
      <a class="btn btn-default" href="<?php echo $this->getReviewsUrl() ?>#review-form">
        <?php echo $this->__('Add Your Review') ?>
      </a>
    </div>
  </div>

<?php elseif ($this->getDisplayIfEmpty()): ?>

  <p class="text-info">
    <a href="<?php echo $this->getReviewsUrl() ?>#review-form">
      <?php echo $this->__('Be the first to review this product') ?>
    </a>
  </p>

<?php endif; ?>
