<?php if ($this->getReviewsCount()): ?>

  <div class="ratings">
    <?php
    if ($this->getRatingSummary()):
      echo $this->getLayout()
        ->createBlock('core/template')
        ->setTemplate('review/helper/rating.phtml')
        ->setPercent($this->getRatingSummary())
        ->toHtml();
    endif;
    ?>

    <a class="label label-info" href="<?php echo $this->getReviewsUrl() ?>">
      <?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?>
    </a>
  </div>

<?php elseif ($this->getDisplayIfEmpty()): ?>

  <p class="ratings text-info">
    <a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a>
  </p>

<?php endif; ?>
