<?php if ($this->getReviewsCount()): ?>

  <a href="<?php echo $this->getReviewsUrl() ?>"
     class="ratings"
     data-toggle="tooltip"
     data-placement="top"
    >
    <?php
    if ($this->getRatingSummary()):
      echo $this->getLayout()
        ->createBlock('core/template')
        ->setTemplate('review/helper/rating.phtml')
        ->setPercent($this->getRatingSummary())
        ->toHtml();
    endif;


    echo $this->getReviewsCount();
    ?>
  </a>

<?php elseif ($this->getDisplayIfEmpty()): ?>

  <a class="ratings text-info" href="<?php echo $this->getReviewsUrl() ?>#review-form">
    <?php echo $this->__('Be the first to review this product') ?>
  </a>

<?php endif; ?>
