<?php if ($this->getReviewsCount()): ?>

  <div class="ratings">
    <?php
    if ($this->getRatingSummary()):
      echo $this->getLayout()
        ->createBlock('core/template')
        ->setTemplate('review/helper/rating.phtml')
        ->setPercent($this->getRatingSummary())
        ->toHtml();
    endif;
    ?>

    <a class="label label-primary" href="<?= $this->getReviewsUrl() ?>">
      <?= $this->__('%d Review(s)', $this->getReviewsCount()) ?>
    </a>

    <a class="" href="<?= $this->getReviewsUrl() ?>#review-form">
      <?= $this->__('Add Your Review') ?>
    </a>
  </div>

<?php elseif ($this->getDisplayIfEmpty()): ?>

  <p class="rating text-info">
    <a href="<?= $this->getReviewsUrl() ?>#review-form">
      <?= $this->__('Be the first to review this product') ?>
    </a>
  </p>

<?php endif; ?>
