<div class="panel panel-default">

  <div class="panel-heading">
    <h2 class="panel-title">
      <?= $this->__('My Recent Tags') ?>
      <small><a href="<?= $this->getAllTagsUrl() ?>"><?= $this->__('View All Tags') ?></a></small>
    </h2>
  </div>

  <ul id="my_recent_tags" class="list-group">
    <?php foreach ($this->getCollection()->getItems() as $_item): ?>

      <li class="list-group-item">
        <h3 class="product-name">
          <a href="<?= $_item->getProductUrl() ?>"><?= $this->escapeHtml($_item->getName()) ?></a>
        </h3>

        <div>
          <strong><?= $this->__('Tags:') ?></strong>

          <ul class="list-inline">
            <?php foreach ($_item->getProductTags() as $_tag): ?>

              <li>
                <a href="<?= $_tag->getViewTagUrl() ?>">
                  <?= $this->escapeHtml($_tag->getName()) ?>
                </a>
              </li>

            <?php endforeach; ?>
          </ul>

        </div>
      </li>

    <?php endforeach; ?>
  </ul>

</div>
