<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="page-header">
  <h1><?php echo $this->__('My Tags') ?></h1>
</div>

<?php if ($this->getTags()): ?>

  <p class="text-info"><?php echo $this->__('Click on a tag to view your corresponding products.') ?></p>

  <ul class="list-inline">
    <?php foreach ($this->getTags() as $_tag): ?>
      <li>
        <a href="<?php echo $this->getUrl('tag/customer/view', array('tagId' => $_tag->getTagId())) ?>"
           style="font-size:<?php echo $_tag->getRatio() * 70 + 75 ?>%;">
          <?php echo $this->escapeHtml($_tag->getName()) ?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>

<?php else: ?>

  <p class="text-info"><?php echo $this->__('You have not tagged any products yet.') ?></p>

<?php endif; ?>

<a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="btn btn-default">
  <i class="fa fa-angle-double-left"></i>
  <?php echo $this->__('Back') ?>
</a>
