

<div class="page-header">
  <h1><?= $this->__('My Tags') ?></h1>
</div>

<?php if ($this->getTags()): ?>

  <p class="text-info"><?= $this->__('Click on a tag to view your corresponding products.') ?></p>

  <ul class="list-inline">
    <?php foreach ($this->getTags() as $_tag): ?>
      <li>
        <a href="<?= $this->getUrl('tag/customer/view', array('tagId' => $_tag->getTagId())) ?>"
           style="font-size:<?= $_tag->getRatio() * 70 + 75 ?>%;">
          <?= $this->escapeHtml($_tag->getName()) ?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>

<?php else: ?>

  <p class="text-info"><?= $this->__('You have not tagged any products yet.') ?></p>

<?php endif; ?>

<a href="<?= $this->escapeUrl($this->getBackUrl()) ?>" class="btn btn-default">
      <?= Mage::helper('vr_kiwiberry')->getSvgIcon('chevron-left') ?>
  <?= $this->__('Back') ?>
</a>
