<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="page-heading">
  <h1><?php echo $this->__('My Tags') ?></h1>
</div>

<p class="my-tag-edit">
  <span class="label label-default"><?php echo $this->escapeHtml($this->getTagInfo()->getName()) ?></span>
  <a href="#"
     title="<?php echo $this->__('Delete') ?>"
     data-confirmation="<?php echo $this->__('Are you sure you want to delete this tag?') ?>"
     data-remove-tag-url="<?php echo $this->getTagInfo()->getRemoveTagUrl(); ?>"
    >
    <i class="fa fa-remove"></i>
    <span class="sr-only"><?php echo $this->__('Delete') ?></span>
  </a>
</p>

<?php echo $this->getToolbarHtml() ?>

<?php if (sizeof($this->getMyProducts()) > 0): ?>

  <table class="table table-striped table-bordered table-hover" id="my-tags-table">
    <tbody>
    <?php foreach ($this->getMyProducts() as $_product): ?>
      <tr>

        <td>
          <a href="<?php echo $_product->getProductUrl(); ?>"
             title="<?php echo $this->escapeHtml($_product->getName()) ?>"
             class="product-image">
            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(100, 100); ?>"
                 width="100"
                 height="100"
                 alt="<?php echo $this->escapeHtml($_product->getName()) ?>">
          </a>
        </td>

        <td>
          <h2 class="product-name">
            <a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a>
          </h2>
          <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
          <?php echo $this->getPriceHtml($_product) ?>
          <?php echo $this->escapeHtml($_product->getDescription()) ?>
        </td>

        <td>
          <?php if ($_product->isSaleable()): ?>
            <?php $params[Mage_Core_Model_Url::FORM_KEY] = Mage::getSingleton('core/session')->getFormKey() ?>
            <?php $params['product'] = $_product->getId(); ?>
            <a title="<?php echo $this->__('Add to Cart') ?>"
               class="btn btn-default"
               href="<?php echo $this->getUrl('checkout/cart/add', $params) ?>"
              >
              <?php echo $this->__('Add to Cart') ?>
            </a>
          <?php endif; ?>

          <?php if ($this->helper('wishlist')->isAllow()) : ?>
            <a href="<?php echo $this->getUrl('wishlist/index/add', array('product' => $_product->getId())) ?>"
               class="btn btn-default">
              <?php echo $this->__('Add to Wishlist') ?>
            </a>
          <?php endif; ?>
        </td>

      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>

<?php else: ?>

  <p class="text-info">
    <?php echo $this->__(
      "Unable to find any products tagged with '%s' in the current store",
      $this->escapeHtml($this->getTagInfo()->getName())
    ) ?>
  </p>

<?php endif; ?>

<?php echo $this->getToolbarHtml() ?>

<a href="<?php echo $this->getUrl('*/*/') ?>" class="btn btn-default">
  <i class="fa fa-angle-double-left"></i>
  <?php echo $this->__('Back to Tags List') ?>
</a>
