

<div class="page-heading">
  <h1><?= $this->__('My Tags') ?></h1>
</div>

<p class="my-tag-edit">
  <span class="label label-default"><?= $this->escapeHtml($this->getTagInfo()->getName()) ?></span>
  <a href="#"
     title="<?= $this->__('Delete') ?>"
     data-confirmation="<?= $this->__('Are you sure you want to delete this tag?') ?>"
     data-remove-tag-url="<?= $this->getTagInfo()->getRemoveTagUrl(); ?>"
    >
    <i class="fa fa-remove"></i>
    <span class="sr-only"><?= $this->__('Delete') ?></span>
  </a>
</p>

<?= $this->getToolbarHtml() ?>

<?php if (sizeof($this->getMyProducts()) > 0): ?>

  <table class="table table-striped table-bordered table-hover" id="my-tags-table">
    <tbody>
    <?php foreach ($this->getMyProducts() as $_product): ?>
      <tr>

        <td>
          <a href="<?= $_product->getProductUrl(); ?>"
             title="<?= $this->escapeHtml($_product->getName()) ?>"
             class="product-image">
            <img src="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(100, 100); ?>"
                 width="100"
                 height="100"
                 alt="<?= $this->escapeHtml($_product->getName()) ?>">
          </a>
        </td>

        <td>
          <h2 class="product-name">
            <a href="<?= $_product->getProductUrl() ?>"><?= $this->escapeHtml($_product->getName()) ?></a>
          </h2>
          <?= $this->getReviewsSummaryHtml($_product, 'short') ?>
          <?= $this->getPriceHtml($_product) ?>
          <?= $this->escapeHtml($_product->getDescription()) ?>
        </td>

        <td>
          <?php if ($_product->isSaleable()): ?>
            <?php $params[Mage_Core_Model_Url::FORM_KEY] = Mage::getSingleton('core/session')->getFormKey() ?>
            <?php $params['product'] = $_product->getId(); ?>
            <a title="<?= $this->__('Add to Cart') ?>"
               class="btn btn-default"
               href="<?= $this->getUrl('checkout/cart/add', $params) ?>"
              >
              <?= $this->__('Add to Cart') ?>
            </a>
          <?php endif; ?>

          <?php if ($this->helper('wishlist')->isAllow()) : ?>
            <a href="<?= $this->getUrl('wishlist/index/add', array('product' => $_product->getId())) ?>"
               class="btn btn-default">
              <?= $this->__('Add to Wishlist') ?>
            </a>
          <?php endif; ?>
        </td>

      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>

<?php else: ?>

  <p class="text-info">
    <?= $this->__(
      "Unable to find any products tagged with '%s' in the current store",
      $this->escapeHtml($this->getTagInfo()->getName())
    ) ?>
  </p>

<?php endif; ?>

<?= $this->getToolbarHtml() ?>

<a href="<?= $this->getUrl('*/*/') ?>" class="btn btn-default">
      <?= Mage::helper('vr_kiwiberry')->getSvgIcon('chevron-left') ?>
  <?= $this->__('Back to Tags List') ?>
</a>
