<?= $this->getMessagesBlock()->toHtml() ?>
<?php $_orders = $this->getOrders(); ?>

<div class="page-header">
  <h1><?= $this->__('My Orders') ?></h1>
</div>

<?= $this->getChildHtml('info'); ?>

<?= $this->getPagerHtml(); ?>

<?php if ($_orders->getSize()): ?>

  <table class="table table-striped" id="my-orders-table">
    <thead>
    <tr>
      <th class="number"><?= $this->__('Order #') ?></th>
      <th class="date"><?= $this->__('Date') ?></th>
      <th class="ship"><?= $this->__('Ship To') ?></th>
      <th class="total"><span class="nobr"><?= $this->__('Order Total') ?></span></th>
      <th class="status"><span class="nobr"><?= $this->__('Order Status') ?></span></th>
      <th class="view">&nbsp;</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($_orders as $_order): ?>

      <tr>
        <td class="number"><?= $_order->getRealOrderId() ?></td>
        <td class="date">
          <span class="nobr"><?= $this->formatDate($_order->getCreatedAtStoreDate()) ?></span>
        </td>
        <td class="ship">
          <?php
          echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;'
          ?>
        </td>
        <td class="total"><?= $_order->formatPrice($_order->getGrandTotal()) ?></td>
        <td class="status"><em><?= $_order->getStatusLabel() ?></em></td>
        <td class="view">
            <a href="<?= $this->getViewUrl($_order) ?>" class="btn btn-default">
              <?= $this->__('View Order') ?>
            </a>

            <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
              <a href="<?= $this->getReorderUrl($_order) ?>" class="btn btn-default">
                <?= $this->__('Reorder') ?>
              </a>
            <?php endif ?>
        </td>
      </tr>

    <?php endforeach; ?>
    </tbody>

  </table>

  <?= $this->getPagerHtml(); ?>

<?php else: ?>

  <p class="text-info"><?= $this->__('You have placed no orders.'); ?></p>

<?php endif ?>
