<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>

<div class="page-header">
  <h1><?php echo $this->__('My Orders') ?></h1>
</div>

<?php echo $this->getChildHtml('info'); ?>

<?php echo $this->getPagerHtml(); ?>

<?php if ($_orders->getSize()): ?>

  <table class="table table-striped" id="my-orders-table">
    <thead>
    <tr>
      <th class="number"><?php echo $this->__('Order #') ?></th>
      <th class="date"><?php echo $this->__('Date') ?></th>
      <th class="ship"><?php echo $this->__('Ship To') ?></th>
      <th class="total"><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
      <th class="status"><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>
      <th class="view">&nbsp;</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($_orders as $_order): ?>

      <tr>
        <td class="number"><?php echo $_order->getRealOrderId() ?></td>
        <td class="date">
          <span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span>
        </td>
        <td class="ship">
          <?php
          echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;'
          ?>
        </td>
        <td class="total"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
        <td class="status"><em><?php echo $_order->getStatusLabel() ?></em></td>
        <td class="view">
            <a href="<?php echo $this->getViewUrl($_order) ?>" class="btn btn-default">
              <?php echo $this->__('View Order') ?>
            </a>

            <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
              <a href="<?php echo $this->getReorderUrl($_order) ?>" class="btn btn-default">
                <?php echo $this->__('Reorder') ?>
              </a>
            <?php endif ?>
        </td>
      </tr>

    <?php endforeach; ?>
    </tbody>

  </table>

  <?php echo $this->getPagerHtml(); ?>

<?php else: ?>

  <p class="text-info"><?php echo $this->__('You have placed no orders.'); ?></p>

<?php endif ?>
