<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="page-header">
  <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
</div>

<?php echo $this->getChildHtml('buttons') ?>

<?php echo $this->getStatusHistoryRssUrl($_order) ?>

<ul id="order-info-tabs" class="nav nav-tabs">
  <?php foreach ($this->getLinks() as $_link): ?>
    <?php if ($_link->getUrl()): ?>
      <li role="presentation"><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
    <?php else: ?>
      <li role="presentation" class="active"><a href="#"><?php echo $_link->getLabel() ?></a></li>
    <?php endif; ?>
  <?php endforeach; ?>
</ul>

<p class="text-info">
  <?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?>
</p>

<?php if (!$_order->getIsVirtual()): ?>

  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title"><?php echo $this->__('Shipping Address') ?></h2>
        </div>
        <div class="panel-body">
          <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title"><?php echo $this->__('Shipping Method') ?></h2>
        </div>
        <div class="panel-body">
          <?php if ($_order->getShippingDescription()): ?>
            <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
          <?php else: ?>
            <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
          <?php endif; ?>
        </div>
      </div>
    </div>
  </div>

<?php endif; ?>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title"><?php echo $this->__('Billing Address') ?></h2>
      </div>
      <div class="panel-body">
        <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title"><?php echo $this->__('Payment Method') ?></h2>
      </div>
      <div class="panel-body">
        <?php echo $this->getPaymentInfoHtml() ?>
      </div>
    </div>
  </div>
</div>
