<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>

<?= $this->getMessagesBlock()->toHtml() ?>

<div class="page-header">
  <h1><?= $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
</div>

<?= $this->getChildHtml('buttons') ?>

<?= $this->getStatusHistoryRssUrl($_order) ?>

<ul id="order-info-tabs" class="nav nav-tabs">
  <?php foreach ($this->getLinks() as $_link): ?>
    <?php if ($_link->getUrl()): ?>
      <li role="presentation"><a href="<?= $_link->getUrl() ?>"><?= $_link->getLabel() ?></a></li>
    <?php else: ?>
      <li role="presentation" class="active"><a href="#"><?= $_link->getLabel() ?></a></li>
    <?php endif; ?>
  <?php endforeach; ?>
</ul>

<p class="text-info">
  <?= $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?>
</p>

<?php if (!$_order->getIsVirtual()): ?>

  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title"><?= $this->__('Shipping Address') ?></h2>
        </div>
        <div class="panel-body">
          <address><?= $_order->getShippingAddress()->format('html') ?></address>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title"><?= $this->__('Shipping Method') ?></h2>
        </div>
        <div class="panel-body">
          <?php if ($_order->getShippingDescription()): ?>
            <?= $this->escapeHtml($_order->getShippingDescription()) ?>
          <?php else: ?>
            <p><?= $this->helper('sales')->__('No shipping information available'); ?></p>
          <?php endif; ?>
        </div>
      </div>
    </div>
  </div>

<?php endif; ?>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title"><?= $this->__('Billing Address') ?></h2>
      </div>
      <div class="panel-body">
        <address><?= $_order->getBillingAddress()->format('html') ?></address>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title"><?= $this->__('Payment Method') ?></h2>
      </div>
      <div class="panel-body">
        <?= $this->getPaymentInfoHtml() ?>
      </div>
    </div>
  </div>
</div>
