<?php $_order = $this->getOrder() ?>
<table class="table table-bordered table-order" id="my-orders-table" summary="<?php echo $this->__('Items Ordered') ?>">

  <thead>
  <tr>
    <th><?php echo $this->__('Product') ?></th>
    <th><?php echo $this->__('SKU') ?></th>
    <th><?php echo $this->__('Price') ?></th>
    <th><?php echo $this->__('Qty') ?></th>
    <th><?php echo $this->__('Subtotal') ?></th>
  </tr>
  </thead>

  <tfoot><?php echo $this->getChildHtml('order_totals') ?></tfoot>

  <tbody>
  <?php foreach ($_order->getItemsCollection() as $_item): ?>
    <?php if ($_item->getParentItem()) continue; ?>

    <?php echo $this->getItemHtml($_item) ?>

    <?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()): ?>
      <tr id="order-item-gift-message-<?php echo $_item->getId() ?>" style="display:none;">
        <?php $_giftMessage = $this->helper('giftmessage/message')->getGiftMessageForEntity($_item); ?>
        <td class="gift-message-row" colspan="7">

          <a href="#"
             title="<?php echo $this->__('Close') ?>"
             data-item-id="<?php echo $_item->getId() ?>"
             class="js-btn-close-gift-msg">
            <?php echo $this->__('Close') ?>
          </a>

          <dl class="dl-horizontal">
            <dt><?php echo $this->__('From:') ?></dt>
            <dd><?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?></dd>
            <dt><?php echo $this->__('To:') ?></dt>
            <dd><?php echo $this->escapeHtml($_giftMessage->getSender()) ?></dd>
            <dt><?php echo $this->__('Message:') ?></dt>
            <dd><?php echo $this->helper('giftmessage/message')->getEscapedGiftMessage($_item) ?></dd>
          </dl>

        </td>
      </tr>
    <?php endif ?>

  <?php endforeach; ?>
  </tbody>

</table>
