<?php $_order = $this->getOrder() ?>

<h1><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h1>

<p>
  <?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?>
</p>

<?php if (!$_order->getIsVirtual()): ?>
  <div class="row">
    <div class="col-xs-6">
      <h2><?php echo $this->__('Shipping Address') ?></h2>
      <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
    </div>

    <div class="col-xs-6">
      <h2><?php echo $this->__('Shipping Method') ?></h2>
      <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
    </div>
  </div>
<?php endif ?>

<div class="row">
  <div class="col-xs-6">
    <h2><?php echo $this->__('Billing Address') ?></h2>
    <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
  </div>

  <div class="col-xs-6">
    <h2><?php echo $this->__('Payment Method') ?></h2>
    <?php echo $this->getPaymentInfoHtml() ?>
  </div>
</div>

<h2><?php echo $this->__('Items Ordered') ?></h2>

<table class="table table-bordered" id="my-orders-table">
  <thead>
  <tr>
    <th><?php echo $this->__('Product Name') ?></th>
    <th><?php echo $this->__('SKU') ?></th>
    <th><?php echo $this->__('Price') ?></th>
    <th><?php echo $this->__('Qty') ?></th>
    <th><?php echo $this->__('Subtotal') ?></th>
  </tr>
  </thead>

  <tfoot><?php echo $this->getChildHtml('order_totals') ?></tfoot>

  <tbody>
  <?php
  foreach ($_order->getItemsCollection() as $_item):
    if ($_item->getParentItem()) continue;
    echo $this->getItemHtml($_item);
  endforeach;
  ?>
  </tbody>
</table>
