<div class="panel panel-primary">

  <?php $_orders = $this->getOrders(); ?>

  <div class="panel-heading">
    <h2 class="panel-title"><?= $this->__('Recent Orders') ?></h2>

    <?php if (sizeof($_orders->getItems()) > 0): ?>
      <a href="<?= $this->getUrl('sales/order/history') ?>">
        <?= $this->__('View All') ?>
      </a>
    <?php endif; ?>
  </div>

  <?php if (sizeof($_orders->getItems()) > 0): ?>
    <table class="table table-striped" id="my-orders-table">
      <thead>
      <tr>
        <th class="number"><?= $this->__('Order #') ?></th>
        <th class="date"><?= $this->__('Date') ?></th>
        <th class="ship"><?= $this->__('Ship To') ?></th>
        <th class="total"><span class="nobr"><?= $this->__('Order Total') ?></span></th>
        <th class="status"><?= $this->__('Status') ?></th>
        <th class="view">&nbsp;</th>
      </tr>
      </thead>

      <tbody>
      <?php foreach ($_orders as $_order): ?>
        <tr>
          <td class="number"><?= $_order->getRealOrderId() ?></td>
          <td class="date">
            <span class="nobr"><?= $this->formatDate($_order->getCreatedAtStoreDate()) ?></span>
          </td>
          <td class="ship">
            <?php
            echo $_order->getShippingAddress() ?
              $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;'
            ?>
          </td>
          <td class="total"><?= $_order->formatPrice($_order->getGrandTotal()) ?></td>
          <td class="status"><em><?= $_order->getStatusLabel() ?></em></td>
          <td class="view">
            <div class="btn-group" role="group" aria-label="Operation">
              <a class="btn btn-default" href="<?= $this->getViewUrl($_order) ?>">
                <?= $this->__('View Order') ?>
              </a>

              <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                <a href="<?= $this->getReorderUrl($_order) ?>" class="btn btn-default">
                  <?= $this->__('Reorder') ?>
                </a>
              <?php endif ?>
            </div>
          </td>
        </tr>
      <?php endforeach; ?>
      </tbody>

    </table>

  <?php else: ?>

    <div class="panel-body">
      <p class="text-info"><?= $this->__('You have placed no orders.'); ?></p>
    </div>

  <?php endif; ?>

</div>
