<div class="order-items order-details">

  <?php $_order = $this->getOrder() ?>
  <h2>
    <?php echo $this->__('Items Ordered') ?>
    <?php if ($_order->getTracksCollection()->count()) : ?>
      <small>
        <a href="<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>"
           target="_blank"
           title="<?php echo $this->__('Track your order') ?>">
          <?php echo $this->__('Track your order') ?>
        </a>
      </small>
    <?php endif; ?>
  </h2>

  <?php echo $this->getChildHtml('order_items') ?>

  <?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $_order) && $_order->getGiftMessageId()): ?>
    <div class="order-additional order-gift-message">
      <h2><?php echo $this->__('Gift Message for This Order') ?></h2>
      <?php $_giftMessage = $this->helper('giftmessage/message')->getGiftMessageForEntity($_order); ?>
      <dl class="dl-horizontal">
        <dt><?php echo $this->__('From:') ?></dt>
        <dd><?php echo $this->escapeHtml($_giftMessage->getSender()) ?></dd>
        <dt><?php echo $this->__('To:') ?></dt>
        <dd><?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?></dd>
        <dt><?php echo $this->__('Message:') ?></dt>
        <dd><?php echo $this->helper('giftmessage/message')->getEscapedGiftMessage($_order) ?></dd>
      </dl>
    </div>
  <?php endif; ?>

  <?php $_history = $this->getOrder()->getVisibleStatusHistory() ?>

  <?php if (count($_history)): ?>
    <div class="order-additional order-comments">
      <h2><?php echo $this->__('About Your Order') ?></h2>
      <dl class="dl-horizontal">
        <?php foreach ($_history as $_historyItem): ?>
          <dt><?php echo $this->formatDate($_historyItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
          <dd><?php echo $this->escapeHtml($_historyItem->getComment()) ?></dd>
        <?php endforeach; ?>
      </dl>
    </div>
  <?php endif; ?>

  <a href="<?php echo $this->getBackUrl() ?>" class="btn btn-default">
    <i class="fa fa-angle-double-left"></i>
    <?php echo $this->getBackTitle() ?>
  </a>
</div>
