<?php $_product = $this->getProduct(); ?>
<?php if ($_product->isSaleable()): ?>

  <?php if (!$_product->isGrouped()): ?>
    <div class="form-group">
      <label for="qty" class="col-sm-2 control-label">
        <?php echo $this->__('Qty:') ?>
      </label>

      <div class="col-sm-10">
        <input type="text"
               pattern="\d*"
               name="qty"
               id="qty"
               maxlength="12"
               value="<?php echo max($this->getProductDefaultQty() * 1, 1) ?>"
               title="<?php echo $this->__('Qty') ?>"
               class="form-control">
      </div>
    </div>
  <?php endif; ?>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <?php $buttonTitle = $this->__('Add to Cart'); ?>
      <button type="button"
              title="<?php echo $buttonTitle ?>"
              class="btn btn-primary"
              id="add_to_cart">
        <?php echo $buttonTitle ?>
      </button>
    </div>
  </div>

  <?php echo $this->getChildHtml('', true, true) ?>

<?php endif; ?>
