<?php
/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */
?>
<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct()
?>
<?php if ($_additional = $this->getAdditionalData()): ?>
  <dl class="dl-horizontal">
    <?php foreach ($_additional as $_data): ?>
      <dt><?php echo $this->escapeHtml($this->__($_data['label'])) ?></dt>
      <dd><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></dd>
    <?php endforeach; ?>
  </dl>
<?php endif; ?>
