<?php
/**
 * Product media data template
 *
 * @var $this Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>

<?php if (!$this->getGalleryImages()) : ?>

  <div class="item active">
    <img id="image-main"
         src="<?= $this->helper('catalog/image')->init($_product, 'image') ?>"
         alt="<?= $this->escapeHtml($this->getImageLabel()) ?>">
  </div>

<?php else: ?>

  <div id="product-gallery" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <?php for ($i = 0; $i < count($this->getGalleryImages()); $i++) : ?>
        <li data-target="#product-gallery"
            data-slide-to="<?= $i ?>"
          <?php if ($i === 0) echo 'class="active"'; ?>>
        </li>
      <?php endfor ?>
    </ol>

    <!-- Wrapper for slides -->
    <div id="product-gallery-images" class="carousel-inner">
      <?php $i = 0;
      foreach ($this->getGalleryImages() as $_image): ?>
        <?php if ($this->isGalleryImageVisible($_image)): ?>
          <div class="item<?php if ($i === 0) echo ' active'; ?>">
            <img class="gallery-image"
                 src="<?= $this->getGalleryImageUrl($_image); ?>"
                 alt="<?= $this->escapeHtml($_image->getLabel()) ?>">
          </div>
        <?php endif; ?>
        <?php $i++; endforeach; ?>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#product-gallery" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#product-gallery" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>

  <h5><?= $this->__('More Views') ?></h5>

  <div class="row">
    <?php
    $i = 0;
    foreach ($this->getGalleryImages() as $_image): ?>
      <?php if ($this->isGalleryImageVisible($_image)): ?>

        <div class="col-sm-3">
          <a href="#product-gallery"
             title="<?= $this->escapeHtml($_image->getLabel()) ?>"
             data-slide-to="<?= $i; ?>">
            <img src="<?= $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(150); ?>"
                 class="img-responsive"
                 alt="<?= $this->escapeHtml($_image->getLabel()) ?>">
          </a>
        </div>

      <?php endif; ?>
      <?php $i++; endforeach; ?>
  </div>
<?php endif; ?>

<?= $this->getChildHtml('after'); ?>
