<?php
/**
 * Product media data template
 *
 * @var $this Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>

<div id="product-gallery" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <?php for ($i = 0; $i < count($this->getGalleryImages()); $i++) : ?>
      <li data-target="#product-gallery"
          data-slide-to="<?php echo $i ?>"
        <?php if ($i === 0) echo 'class="active"'; ?>>
      </li>
    <?php endfor ?>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img id="image-main"
           src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>"
           alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>">
    </div>

    <?php $i = 0;
    foreach ($this->getGalleryImages() as $_image): ?>
      <?php if ($this->isGalleryImageVisible($_image)): ?>
        <div class="item<?php if ($i === 0) echo ' active'; ?>">
          <img class="gallery-image"
               src="<?php echo $this->getGalleryImageUrl($_image); ?>"
               alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
        </div>
      <?php endif; ?>
      <?php $i++; endforeach; ?>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#product-gallery" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#product-gallery" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<?php if (count($this->getGalleryImages()) > 0): ?>
  <h5><?php echo $this->__('More Views') ?></h5>

  <div class="row">
    <?php
    $i = 0;
    foreach ($this->getGalleryImages() as $_image): ?>
      <?php if ($this->isGalleryImageVisible($_image)): ?>

        <div class="col-sm-3">
          <a href="#product-gallery"
             title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"
             data-slide-to="<?php echo $i; ?>">
            <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(150); ?>"
                 class="img-responsive"
                 alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
          </a>
        </div>

      <?php endif; ?>
    <?php $i++; endforeach; ?>
  </div>
<?php endif; ?>

<?php echo $this->getChildHtml('after'); ?>
