<?php
$_product = $this->getProduct();
$_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product);
$_helper = $this->helper('catalog/output');
$_productName = urlencode(trim($_helper->productAttribute($_product, $_product->getName(), 'name')));
$_productImageUrl = urlencode(trim($this->helper('catalog/image')->init($_product, 'image')));
$_productUrl = urlencode(trim($_product->getProductUrl()));
$_u = 'p[url]=' . $_productUrl
  . '&p[images][0]=' . $_productImageUrl
  . '&p[title]=' . $_productName
  . '&p[summary]=' . urlencode(
    trim($_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description'))
  );
?>

<?php if ($this->canEmailToFriend()): ?>
  <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"
     class="btn btn-default"
     title="<?php echo $this->__('Email to a Friend') ?>">
    <?php echo $this->__('Email to a Friend') ?>
  </a>
<?php endif; ?>

<a href="<?php echo 'http://www.facebook.com/sharer.php?s=100&' . $_u; ?>"
   target="_blank"
   title="<?php echo $this->__('Share on Facebook') ?>"
   class="btn btn-default">
  <?php echo $this->__('Share Facebook') ?>
</a>
<a href="<?php echo 'http://twitter.com/home?status=' . $_productName . '+' . $_productUrl; ?>"
   target="_blank"
   title="<?php echo $this->__('Share on Twitter') ?>"
   class="btn btn-default">
  <?php echo $this->__('Share on Twitter') ?>
</a>

