<?php
/**
 * @see Mage_Checkout_Block_Cart_Totals
 */
?>
<?php if ($this->getTotals()): ?>
  <tfoot>
  <?php $_colspan = $this->helper('tax')->displayCartBothPrices() ? 5 : 3; ?>
  <?php echo $this->renderTotals(null, $_colspan); ?>
  <?php echo $this->renderTotals('footer', $_colspan); ?>
  <?php if ($this->needDisplayBaseGrandtotal()): ?>
    <tr>
      <td colspan="<?php echo $_colspan; ?>">
        <small><?php echo $this->helper('sales')->__('Your credit card will be charged for') ?></small>
      </td>
      <td>
        <small><?php echo $this->displayBaseGrandtotal() ?></small>
      </td>
    </tr>
  <?php endif ?>
  </tfoot>
<?php endif; ?>
