<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 * @var $this Mage_Customer_Block_Form_Login
 */
?>
<div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">

  <div class="page-header">
    <h1>
      <?= $this->helper('customer')->isRegistrationAllowed() ?
        $this->__('Login or Create an Account') : $this->__('Login');
      ?>
    </h1>
  </div>

  <div class="row-login">

    <?php // Registration Column ?>
    <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
      <div class="col-new-users">

        <h2><?= $this->__('New Here?') ?></h2>

        <div class="registration-benefits">

          <p class="text-info"><?= $this->__('Registration is free and easy!') ?></p>

          <ul class="media-list">
            <li class="media">
              <div class="media-left">
                <?= Mage::helper('vr_kiwiberry')->getSvgIcon('rocket', 'media-object') ?>
              </div>
              <div class="media-body">
                <h3 class="media-heading"><?= $this->__('Faster checkout') ?></h3>
              </div>
            </li>
            <li class="media">
              <div class="media-left">
                <?= Mage::helper('vr_kiwiberry')->getSvgIcon('truck', 'media-object') ?>
              </div>
              <div class="media-body">
                <h3 class="media-heading"><?= $this->__('Save multiple shipping addresses') ?></h3>
              </div>
            </li>
            <li class="media">
              <div class="media-left">
                <?= Mage::helper('vr_kiwiberry')->getSvgIcon('binoculars', 'media-object') ?>
              </div>
              <div class="media-body">
                <h3 class="media-heading"><?= $this->__('View and track orders and more') ?></h3>
              </div>
            </li>
          </ul>

        </div>

        <a title="<?= $this->__('Create an Account') ?>"
           class="btn btn-primary btn-lg"
           href="<?= Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>">
          <?= $this->__('Create an Account') ?>
        </a>

      </div>
    <?php endif; ?>

    <?php // Login Column ?>
    <div class="col-registered-users">

      <h2><?= $this->__('Already registered?') ?></h2>

      <form action="<?= $this->getPostActionUrl() ?>" method="post" id="login-form" role="form">

        <?= $this->getBlockHtml('formkey'); ?>

        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
          <input name="context" type="hidden" value="checkout"/>
        <?php endif; ?>

        <p class="text-info"><?= $this->__('If you have an account with us, please log in.') ?></p>

        <p class="text-danger"><?= $this->__('* Required Fields') ?></p>

        <div class="form-group">
          <label for="email" class="required"><?= $this->__('Email Address') ?></label>
          <input type="email"
                 autocapitalize="off"
                 autocorrect="off"
                 spellcheck="false"
                 name="login[username]"
                 value="<?= $this->escapeHtml($this->getUsername()) ?>"
                 id="email"
                 class="form-control required-entry validate-email"
                 title="<?= $this->__('Email Address') ?>"/>
        </div>

        <div class="form-group">
          <label for="pass" class="required"><?= $this->__('Password') ?></label>
          <input type="password"
                 name="login[password]"
                 class="form-control required-entry validate-password"
                 id="pass"
                 title="<?= $this->__('Password') ?>"/>
        </div>

        <?= $this->getChildHtml('form.additional.info'); ?>

        <a href="<?= $this->getForgotPasswordUrl() ?>" class="text-info">
          <?= $this->__('Forgot Your Password?') ?>
        </a>

        <?= $this->getChildHtml('persistent.remember.me'); ?>

        <button type="submit" class="btn btn-primary btn-lg" title="<?= $this->__('Login') ?>" name="send" id="send2">
          <?= $this->__('Login') ?>
        </button>
      </form>
    </div>

  </div>
  <!-- .row-login -->

</div><!-- .account-login -->
