<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 * @var $this Mage_Customer_Block_Form_Login
 */
?>
<div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">

  <h1>
    <?= $this->helper('customer')->isRegistrationAllowed() ?
      $this->__('Login or Create an Account') : $this->__('Login');
    ?>
  </h1>


    <form action="<?= $this->getPostActionUrl() ?>" method="post" id="login-form" role="form">

    <?= $this->getBlockHtml('formkey'); ?>

    <div class="row">

      <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
        <div class="col-md-6 new-users">
          <h2><?= $this->__('New Here?') ?></h2>

          <p class="text-info"><?= $this->__('Registration is free and easy!') ?></p>

          <ul>
            <li><?= $this->__('Faster checkout') ?></li>
            <li><?= $this->__('Save multiple shipping addresses') ?></li>
            <li><?= $this->__('View and track orders and more') ?></li>
          </ul>

          <a title="<?= $this->__('Create an Account') ?>"
             class="btn btn-default"
             href="<?= Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>">
            <?= $this->__('Create an Account') ?>
          </a>
        </div>
      <?php endif; ?>

      <?php // This column should be col-md-12 if the registration column is not displayed ?>
      <div class="<?php if ($this->helper('customer')->isRegistrationAllowed()): ?>col-md-6<?php else: ?>col-md-12<?php endif; ?> registered-users">
        <h2><?= $this->__('Already registered?') ?></h2>

        <p class="text-info"><?= $this->__('If you have an account with us, please log in.') ?></p>

        <p class="text-danger"><?= $this->__('* Required Fields') ?></p>

        <div class="form-group">
          <label for="email" class="required"><em>*</em><?= $this->__('Email Address') ?></label>
          <input type="email"
                 autocapitalize="off"
                 autocorrect="off"
                 spellcheck="false"
                 name="login[username]"
                 value="<?= $this->escapeHtml($this->getUsername()) ?>"
                 id="email"
                 class="form-control required-entry validate-email"
                 title="<?= $this->__('Email Address') ?>"/>
        </div>

        <div class="form-group">
          <label for="pass" class="required"><em>*</em><?= $this->__('Password') ?></label>
          <input type="password"
                 name="login[password]"
                 class="form-control required-entry validate-password"
                 id="pass"
                 title="<?= $this->__('Password') ?>"/>
        </div>

        <?= $this->getChildHtml('form.additional.info'); ?>

        <a href="<?= $this->getForgotPasswordUrl() ?>" class="text-info">
          <?= $this->__('Forgot Your Password?') ?>
        </a>

        <?= $this->getChildHtml('persistent.remember.me'); ?>

        <button type="submit" class="btn btn-default" title="<?= $this->__('Login') ?>" name="send" id="send2">
          <?= $this->__('Login') ?>
        </button>
      </div>

    </div>

    <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
      <input name="context" type="hidden" value="checkout"/>
    <?php endif; ?>
  </form>
</div>
