<?php
/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 * @var $this Mage_Customer_Block_Form_Register
 */
?>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<h1><?php echo $this->__('Create an Account') ?></h1>

<?php echo $this->getChildHtml('form_fields_before') ?>

<form action="<?php echo $this->getPostActionUrl() ?>"
      method="post"
      id="form-validate"
      role="form"
      data-show-address-fields="<?php echo $this->getShowAddressFields() ? 'true' : 'false'; ?>"
      data-region-json="<?php echo $this->escapeHtml($this->helper('directory')->getRegionJsonByStore()); ?>"
      enctype="multipart/form-data">

  <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>"/>
  <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>"/>

  <p class="text-info"><?php echo $this->__('Please enter the following information to create your account.') ?></p>

  <p class="text-danger"><?php echo $this->__('* Required Fields') ?></p>

  <?php
  echo $this->getLayout()
    ->createBlock('customer/widget_name')
    ->setObject($this->getFormData())
    ->setForceUseCustomerAttributes(true)
    ->toHtml()
  ?>

  <div class="form-group">
    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
    <input type="email"
           autocapitalize="off"
           autocorrect="off"
           spellcheck="false"
           name="email"
           id="email_address"
           value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>"
           title="<?php echo $this->__('Email Address') ?>"
           class="form-control validate-email required-entry">
  </div>

  <?php
  $_dob = $this->getLayout()->createBlock('customer/widget_dob');
  if ($_dob->isEnabled()): echo $_dob->setDate($this->getFormData()->getDob())->toHtml(); endif;

  $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat');
  if ($_taxvat->isEnabled()): echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml(); endif;

  $_gender = $this->getLayout()->createBlock('customer/widget_gender');
  if ($_gender->isEnabled()): echo $_gender->setGender($this->getFormData()->getGender())->toHtml(); endif;
  ?>

  <?php if ($this->getShowAddressFields()): ?>

    <input type="hidden" name="create_address" value="1">

    <div class="form-group">
      <label for="company"><?php echo $this->__('Company') ?></label>
      <input type="text"
             name="company"
             id="company"
             value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>"
             title="<?php echo $this->__('Company') ?>"
             class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>">
    </div>

    <div class="form-group">
      <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
      <input type="tel"
             name="telephone"
             id="telephone"
             value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>"
             title="<?php echo $this->__('Telephone') ?>"
             class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>">
    </div>

    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
    <div class="form-group">
      <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
      <input type="text"
             name="street[]"
             value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>"
             title="<?php echo $this->__('Street Address') ?>"
             id="street_1"
             class="form-control <?php echo $_streetValidationClass ?>">
    </div>

    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
      <div class="form-group">
        <label for="billing:street<?php echo $_i ?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
        <input type="text"
               name="street[]"
               value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i - 1)) ?>"
               title="<?php echo $this->__('Street Address %s', $_i) ?>"
               id="street_<?php echo $_i ?>"
               class="form-control <?php echo $_streetValidationClass ?>">
      </div>
    <?php endfor; ?>

    <div class="form-group">
      <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
      <input type="text"
             name="city"
             value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>"
             title="<?php echo $this->__('City') ?>"
             class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
             id="city">
    </div>

    <div class="form-group">
      <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
      <select id="region_id"
              name="region_id"
              title="<?php echo $this->__('State/Province') ?>"
              class="form-control validate-select"
              defaultValue="<?php echo $this->getFormData()->getRegionId() ?>"
              style="display:none;">
        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
      </select>

      <input type="text"
             id="region"
             name="region"
             value="<?php echo $this->escapeHtml($this->getRegion()) ?>"
             title="<?php echo $this->__('State/Province') ?>"
             class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
             style="display:none;">
    </div>

    <div class="form-group">
      <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
      <input type="text"
             name="postcode"
             value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>"
             title="<?php echo $this->__('Zip/Postal Code') ?>"
             id="zip"
             class="form-control validate-zip-international <?php
             echo $this->helper('customer/address')->getAttributeValidationClass('postcode')
             ?>"
        >
    </div>

    <div class="form-group">
      <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
      <?php echo $this->getCountryHtmlSelect() ?>
    </div>

    <input type="hidden" name="default_billing" value="1"/>
    <input type="hidden" name="default_shipping" value="1"/>
  <?php endif; ?>

  <div class="form-group">
    <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
    <input type="password"
           name="password"
           id="password"
           title="<?php echo $this->__('Password') ?>"
           class="form-control required-entry validate-password">
  </div>

  <div class="form-group">
    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
    <input type="password"
           name="confirmation"
           title="<?php echo $this->__('Confirm Password') ?>"
           id="confirmation"
           class="form-control required-entry validate-cpassword">
  </div>

  <?php echo $this->getChildHtml('form.additional.info'); ?>

  <?php if ($this->isNewsletterEnabled()): ?>
    <div class="checkbox">
      <label for="is_subscribed">
        <input type="checkbox"
               name="is_subscribed"
               title="<?php echo $this->__('Sign Up for Newsletter') ?>"
               value="1"
               id="is_subscribed"<?php if ($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
          >
        <?php echo $this->__('Sign Up for Newsletter') ?>
      </label>
    </div>
  <?php endif ?>

  <?php echo $this->getChildHtml('persistent.remember.me'); ?>

  <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="btn btn-default">
    <i class="fa fa-angle-double-left"></i>
    <?php echo $this->__('Back') ?>
  </a>

  <button type="submit" title="<?php echo $this->__('Register') ?>" class="btn btn-default">
    <?php echo $this->__('Register') ?>
  </button>

  <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
    <input name="context" type="hidden" value="checkout">
  <?php endif; ?>

</form>

<script>
</script>
