<h1>OUR STORY</h1>

<div class="row">

  <div class="col-sm-6">
    <p>Madison Island is...</p>

    <p>
      ...a breath of fresh air.<br/>
      &hellip;a mecca for style savvy travellers. <br/>
      &hellip;a curator of gorgeous sartorial design. <br/>
      &hellip;a world class concept store.
    </p>

    <p>
      Uniquely designed with cosmopolitan appeal, Madison Island gives couture-conscious frequent flyers exactly what
      they want&mdash;unprecedented access to the latest looks of the season, style solutions for easy international jet
      setting, and convenient worldwide delivery.
    </p>

    <p>
      With its website relaunch in 2013, Madison Island has solidified its standing as the new essential luxury. Its
      pages are filled with exquisite finds for fashion and home.
    </p>
  </div>

  <div class="col-sm-6">
    <div class="thumbnail">
      <img src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/about_us.jpg' ?>"
           alt="about-us-image"/>
      <div class="caption">
        <h3>Madison Island Boutique in NYC</h3>
      </div>
    </div>
  </div>
</div>
