<h1>Customer Service</h1>

<h2>SHIPPING &amp; DELIVERY</h2>

<p>
  Shipping and Delivery is the charge for Internet order processing, item selection, packaging, transport and
  handling. Delivery times are not guaranteed, but are our best approximation and will vary with specific
  requests. Shipments and deliveries only occur on weekdays. Shipping and Delivery is subject to change and will
  be determined at the time of order.
</p>

<p>
  Estimated delivery time assumes orders are placed before 12:00 noon (PST). Orders placed late on Friday
  or on Saturday will not be processed until Monday. Additional charges may accrue on Priority, Overnight and
  International shipping if multiple attempts are made for delivery.
</p>

<p>
  Shipping addresses in Alaska, Hawaii, Puerto Rico, and Guam should add an additional $5.00 charge for
  standard Shipping &amp; Delivery. Orders arrive in 7 to 9 business days when ordered before 12:00 noon (PST).
</p>

<div class="table-responsive">
  <table class="table">
    <thead>
    <tr class="active">
      <th>&nbsp;</th>
      <th>Standard</th>
      <th>Priority</th>
      <th>Overnight</th>
      <th>International</th>
    </tr>
    </thead>
    <tfoot>
    <tr>
      <td colspan="5"><small>* before tax and additional charges</small></td>
    </tr>
    </tfoot>
    <tbody>
    <tr>
      <td>&nbsp;</td>
      <td>Package arrives 5 to 7 business days after processing if ordered by 12:00 noon (PST).</td>
      <td>Package arrives 2 to 3 business days after processing if ordered by 12:00 noon (PST).</td>
      <td>Package arrives the next business day if ordered before 12:00 noon (PST).</td>
      <td>Order should arrive 3-9 business days after processing. Flat rate does not include duties and taxes.</td>
    </tr>

    <tr>
      <th colspan="5" class="active">Merchandise Total *</th>
    </tr>

    <tr>
      <td>Up to $200</td>
      <td>$16</td>
      <td>$26</td>
      <td>$33</td>
      <td>$80 (flat rate) excludes duties and taxes</td>
    </tr>
    <tr>
      <td>$200.01—500.00</td>
      <td>$21</td>
      <td>$31</td>
      <td>$38</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>$500.01—1000.00</td>
      <td>$29</td>
      <td>$39</td>
      <td>$46</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>Over $1000.00</td>
      <td>$34</td>
      <td>$44</td>
      <td>$51</td>
      <td>&nbsp;</td>
    </tr>
    </tbody>
  </table>
</div>

<h2>RETURNS &amp; REPLACEMENTS</h2>

<p>
  <strong>We want you to be completely happy with your order. </strong>
  If for any reason you are not satisfied, we will gladly accept your timely return of unworn, unwashed, or defective
  merchandise. Used merchandise cannot be returned unless defective. Returned merchandise should include the vendor
  packaging and tags and be in the same condition as when it was received. A pickup and/or restock fee may apply.
  Merchandise must be returned within 30 days of receipt of merchandise.
</p>

<p>
  <strong>GIFTS</strong><br>
  When returning a gift, a Madison Island Anytime Anyplace Gift Card will be issued to the gift recipient for the amount
  of the returned merchandise. The card can be used for purchases from any Madison Island or affiliate store, and
  online. In compliance with Federal law, for gifts valued at more than $2,000.00, the recipient will receive a check
  rather than an Anytime Anyplace Gift Card.
</p>

<p>
  <strong>RETURNING MERCHANDISE BY MAIL</strong><br>
  On the back of the packing slip enclosed with your order, please note the reason(s) for return and whether you wish to
  exchange the item(s) or receive a credit/refund (depending on the original form of payment). Enclose the return
  section of the packing slip with your item(s). Please use one of the return labels provided on the front of your
  packing slip to ensure proper return address and credit information.
</p>

<p>
  <strong>OTHER ITEMS</strong><br>
  All cosmetic and bath items must be unused, unopened, and in original packaging for a credit/refund or exchange to be
  issued. Restricted items must be returned using ground transportation.
</p>

<p>
  <strong>Please allow 10 to 14 days for the processing of your return.</strong>
</p>
