<div class="alert alert-warning" role="alert">Please enable cookies in your web browser to continue.</div>

<h1><a id="top"></a>What are Cookies?</h1>

<p>
  Cookies are short pieces of data that are sent to your computer when you visit a website. On later visits, this
  data is then returned to that website. Cookies allow us to recognize you automatically whenever you visit our site
  so that we can personalize your experience and provide you with better service. We also use cookies (and similar
  browser data, such as Flash cookies) for fraud prevention and other purposes. If your web browser is set to refuse
  cookies from our website, you will not be able to complete a purchase or take advantage of certain features of our
  website, such as storing items in your Shopping Cart or receiving personalized recommendations. As a result, we
  strongly encourage you to configure your web browser to accept cookies from our website.
</p>

<h2>Enabling Cookies</h2>

<ul>
  <li><a href="#ie7">Internet Explorer 7.x</a></li>
  <li><a href="#ie6">Internet Explorer 6.x</a></li>
  <li><a href="#firefox">Mozilla/Firefox</a></li>
  <li><a href="#opera">Opera 7.x</a></li>
</ul>

<div class="row">
  <div class="col-md-6">
    <h3><a id="ie7"></a>Internet Explorer 7.x</h3>

    <ol>
      <li>
        <p>Start Internet Explorer</p>
      </li>
      <li>
        <p>Under the <strong>Tools</strong> menu, click <strong>Internet Options</strong></p>

        <p><img class="img-responsive" src="<?= $this->getSkinUrl('images/cookies/ie7-1.gif') ?>" alt=""/></p>
      </li>
      <li>
        <p>Click the <strong>Privacy</strong> tab</p>

        <p><img class="img-responsive" src="<?= $this->getSkinUrl('images/cookies/ie7-2.gif') ?>" alt=""/></p>
      </li>
      <li>
        <p>Click the <strong>Advanced</strong> button</p>

        <p><img class="img-responsive" src="<?= $this->getSkinUrl('images/cookies/ie7-3.gif') ?>" alt=""/></p>
      </li>
      <li>
        <p>Put a check mark in the box for <strong>Override Automatic Cookie Handling</strong>, put another check mark
          in
          the <strong>Always accept session cookies </strong>box</p>

        <p><img class="img-responsive" src="<?= $this->getSkinUrl('images/cookies/ie7-4.gif') ?>" alt=""/></p>
      </li>
      <li>
        <p>Click <strong>OK</strong></p>

        <p><img class="img-responsive" src="<?= $this->getSkinUrl('images/cookies/ie7-5.gif') ?>" alt=""/></p>
      </li>
      <li>
        <p>Click <strong>OK</strong></p>

        <p><img class="img-responsive" src="<?= $this->getSkinUrl('images/cookies/ie7-6.gif') ?>" alt=""/></p>
      </li>
      <li>
        <p>Restart Internet Explore</p>
      </li>
    </ol>

    <p><a href="#top">Back to Top</a></p>
  </div>
  <div class="col-md-6">
    <h3><a id="ie6"></a>Internet Explorer 6.x</h3>

    <ol>
      <li>
        <p>Select <strong>Internet Options</strong> from the Tools menu</p>

        <p><img class="img-responsive" src="<?= $this->getSkinUrl('images/cookies/ie6-1.gif') ?>" alt=""/></p>
      </li>
      <li>
        <p>Click on the <strong>Privacy</strong> tab</p>
      </li>
      <li>
        <p>Click the <strong>Default</strong> button (or manually slide the bar down to <strong>Medium</strong>) under
          <strong>Settings</strong>. Click <strong>OK</strong></p>

        <p><img class="img-responsive" src="<?= $this->getSkinUrl('images/cookies/ie6-2.gif') ?>" alt=""/></p>
      </li>
    </ol>

    <p><a href="#top">Back to Top</a></p>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <h3><a id="firefox"></a>Mozilla/Firefox</h3>

    <ol>
      <li>
        <p>Click on the <strong>Tools</strong>-menu in Mozilla</p>
      </li>
      <li>
        <p>Click on the <strong>Options...</strong> item in the menu - a new window open</p>
      </li>
      <li>
        <p>Click on the <strong>Privacy</strong> selection in the left part of the window. (See image below)</p>

        <p><img class="img-responsive" src="<?= $this->getSkinUrl('images/cookies/firefox.png') ?>" alt=""/></p>
      </li>
      <li>
        <p>Expand the <strong>Cookies</strong> section</p>
      </li>
      <li>
        <p>Check the <strong>Enable cookies</strong> and <strong>Accept cookies normally</strong> checkboxes</p>
      </li>
      <li>
        <p>Save changes by clicking <strong>Ok</strong>.</p>
      </li>
    </ol>

    <p><a href="#top">Back to Top</a></p>
  </div>
  <div class="col-md-6">
    <h3><a id="opera"></a>Opera 7.x</h3>

    <ol>
      <li>
        <p>Click on the <strong>Tools</strong> menu in Opera</p>
      </li>
      <li>
        <p>Click on the <strong>Preferences...</strong> item in the menu - a new window open</p>
      </li>
      <li>
        <p>Click on the <strong>Privacy</strong> selection near the bottom left of the window. (See image below)</p>

        <p><img class="img-responsive" src="<?= $this->getSkinUrl('images/cookies/opera.png') ?>" alt=""/></p>
      </li>
      <li>
        <p>The <strong>Enable cookies</strong> checkbox must be checked, and <strong>Accept all cookies</strong> should
          be
          selected in the &quot;<strong>Normal cookies</strong>&quot; drop-down</p>
      </li>
      <li>
        <p>Save changes by clicking <strong>Ok</strong></p>
      </li>
    </ol>

    <p><a href="#top">Back to Top</a></p>
  </div>
</div>




