<p>
  <img class="img-responsive"
       src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/404-banner-3.jpg' ?>"
       alt="404bannerimage"/>
</p>

<h1>OOPS!</h1>

<p>
  <strong>404 Page not found.</strong>
  You might want to check that URL again or head over to our
  <a href="<?= Mage::getStoreConfig('web/unsecure/base_url')?>">homepage.</a>
</p>

<h2>WERE YOU LOOKING FOR SOMETHING SPECIAL?</h2>

<p>Here are some suggestions that you might like....</p>
