<h5>Connect With Us</h5>
<ul class="list-unstyled">
  <li>
    <i class="fa fa-fw fa-facebook"></i>
    <a href="http://facebook.com/">Facebook</a>
  </li>
  <li>
    <i class="fa fa-fw fa-twitter"></i>
    <a href="http://twitter.com/">Twitter</a>
  </li>
  <li>
    <i class="fa fa-fw fa-instagram"></i>
    <a href="http://instagram.com/">Instagram</a>
  </li>
  <li>
    <i class="fa fa-fw fa-youtube-play"></i>
    <a href="http://youtube.com/">YouTube</a>
  </li>
  <li>
    <i class="fa fa-fw fa-pinterest"></i>
    <a href="http://pinterest.com/">Pinterest</a>
  </li>

  <li>
    <i class="fa fa-fw fa-rss"></i>
    <a href="#">RSS</a>
  </li>
</ul>
