<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp(
  $_item->getProduct(),
  Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM
);
?>

<li class="list-group-item">
  <div class="media minicart-media">
    <div class="media-left minicart-media-left">
      <?php ob_start() ?>
      <img src="<?= $this->getProductThumbnail()->resize(150, 150)->setWatermarkSize('30x10'); ?>"
           class="minicart-product-img"
           alt="<?= $this->escapeHtml($this->getProductName()) ?>">
      <?php $imgHtml = ob_get_clean() ?>


      <?php if ($this->hasProductUrl()): ?>
        <a href="<?= $this->getProductUrl() ?>"
           title="<?= $this->escapeHtml($this->getProductName()) ?>"
           class="minicart-product-img-container media-object">
          <?= $imgHtml ?>
        </a>
      <?php else: ?>
        <div class="minicart-product-img-container media-object">
          <?= $imgHtml ?>
        </div>
      <?php endif; ?>

      <?php if ($isVisibleProduct): ?>
        <a href="<?= $this->getConfigureUrl() ?>" title="<?= $this->__('Edit item') ?>"
           class="minicart-btn-edit"
          >
          <?= Mage::helper('vr_kiwiberry')->getSvgIcon('edit') ?>
          <span><?= $this->__('Edit') ?></span>
        </a>
      <?php endif ?>
    </div>

    <div class="media-body minicart-media-body">
      <h5 class="media-heading">
        <?php $nameHtml = $this->escapeHtml($this->getProductName()) ?>
        <?php if ($this->hasProductUrl()): ?>
          <a href="<?= $this->getProductUrl() ?>">
            <?= $nameHtml ?>
          </a>
        <?php else : ?>
          <?= $nameHtml ?>
        <?php endif; ?>
      </h5>

      <?php if ($isVisibleProduct && !$this->isOnCheckoutPage()): ?>
        <a href="<?= $this->getAjaxDeleteUrl() ?>" title="<?= $this->__('Remove This Item') ?>"
           data-confirm="<?= $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>"
           aria-label="close"
           class="close">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only"><?= $this->__('Remove Item') ?></span>
        </a>
      <?php endif ?>

      <table class="table table-condensed minicart-table">
        <tbody>
        <tr>
          <th><?= $this->__('Price'); ?></th>
          <td>
            <?php if ($canApplyMsrp): ?>

              <span class="map-cart-sidebar-item"><?= $this->__('See price before order confirmation.'); ?></span>

            <?php else: ?>

              <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                  <?= $this->__('Excl. Tax'); ?>:
                <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                  <?= $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?>
                <?php else: ?>
                  <?= $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                <?php endif; ?>
                <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                  <br/>
                  <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                    <small>
                      <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?= $tax['title']; ?>
                          : <?= Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span>
                      <?php endforeach; ?>
                    </small>
                  <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                      <span class="nobr">
                        <small><?= $tax['title']; ?>
                          : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></small>
                      </span><br/>
                    <?php endforeach; ?>
                  <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
                    <small>
                      <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?= $tax['title']; ?>
                          : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
                        <br/>
                      <?php endforeach; ?>
                    </small>
                  <?php endif; ?>
                  <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <span class="nobr"><?= Mage::helper('weee')->__('Total'); ?>
                      :<br/> <?= $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?>
                    </span>
                  <?php endif; ?>
                <?php endif; ?>
              <?php endif; ?>



              <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                  <br/><?= $this->__('Incl. Tax'); ?>:
                <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                  <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
                <?php else: ?>
                  <?= $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxDisposition()) ?>
                <?php endif; ?>
                <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                  <br/>
                  <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                    <small>
                      <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?= $tax['title']; ?>
                          : <?= Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span><br/>
                      <?php endforeach; ?>
                    </small>
                  <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                      <span class="nobr">
                        <small><?= $tax['title']; ?>
                          : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></small>
                      </span>
                    <?php endforeach; ?>
                  <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
                    <small>
                      <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?= $tax['title']; ?>
                          : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
                        <br/>
                      <?php endforeach; ?>
                    </small>
                  <?php endif; ?>
                  <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <span class="nobr"><?= Mage::helper('weee')->__('Total incl. tax'); ?>
                      :<br/> <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
                    </span>
                  <?php endif; ?>
                <?php endif; ?>
              <?php endif; ?>

            <?php endif; //Can apply MSRP ?>
          </td>
        </tr>

        <tr class="qty-wrapper">
          <th><?= $this->__('Qty'); ?></th>
          <td>
            <div class="input-group input-group-sm minicart-input-group-qty">
              <input
                id="qinput-<?= $_item->getId(); ?>"
                data-link="<?= $this->getAjaxUpdateUrl() ?>"
                data-item-id="<?= $_item->getId(); ?>"
                class="qty js-cart-item-quantity input-text form-control"
                name=""
                value="<?= $this->getQty() ?>"
                required
                type="number"
                <?php if ($this->isOnCheckoutPage()) echo 'disabled'; ?>
                >
              <span class="input-group-btn">
                <button id="qbutton-<?= $_item->getId(); ?>"
                        data-item-id="<?= $_item->getId(); ?>"
                        disabled="disabled"
                        data-update
                        class="btn btn-primary quantity-button js-quantity-button">
                  <?= $this->__('OK'); ?>
                </button>
              </span>
            </div>
            <!-- /input-group -->
          </td>
        </tr>

        <?php if ($_options = $this->getOptionList()): ?>

          <?php foreach ($_options as $_option) : ?>
            <tr>
              <th>
                <?= $this->escapeHtml($_option['label']) ?>
              </th>
              <td>
                <?php if (is_array($_option['value'])): ?>
                  <?= nl2br(implode("\n", $_option['value'])) ?>
                <?php else: ?>
                  <?= $_option['value'] ?>
                <?php endif; ?>
              </td>
            </tr>
          <?php endforeach; ?>

        <?php endif; ?>
        </tbody>
      </table>
    </div>
  </div>
</li>

