<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp(
  $_item->getProduct(),
  Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM
);
?>

<tr class="minicart-item-start">
  <th>
    <?php ob_start() ?>
    <img src="<?php echo $this->getProductThumbnail()->resize(50, 50)->setWatermarkSize('30x10'); ?>"
         class="minicart-product-img"
         alt="<?php echo $this->escapeHtml($this->getProductName()) ?>">
    <?php $imgHtml = ob_get_clean() ?>


    <?php if ($this->hasProductUrl()): ?>
      <a href="<?php echo $this->getProductUrl() ?>"
         title="<?php echo $this->escapeHtml($this->getProductName()) ?>"
         class="minicart-product-img-container">
        <?php echo $imgHtml ?>
      </a>
    <?php else: ?>
      <div class="minicart-product-img-container">
        <?php echo $imgHtml ?>
      </div>
    <?php endif; ?>
  </th>
  <td>
    <?php $nameHtml = $this->escapeHtml($this->getProductName()) ?>
    <?php if ($this->hasProductUrl()): ?>
      <a href="<?php echo $this->getProductUrl() ?>">
        <?php echo $nameHtml ?>
      </a>
    <?php else : ?>
      <?php echo $nameHtml ?>
    <?php endif; ?>

    <?php if ($isVisibleProduct && !$this->isOnCheckoutPage()): ?>
      <a href="<?php echo $this->getAjaxDeleteUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>"
         data-confirm="<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>"
         aria-label="close"
         class="close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only"><?php echo $this->__('Remove Item') ?></span>
      </a>
    <?php endif ?>

    <?php if ($isVisibleProduct): ?>
      <a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo $this->__('Edit item') ?>"
         class="minicart-btn-edit"
        >
        <?php echo Mage::helper('vr_kiwiberry')->getSvgIcon('edit') ?>
        <span class="sr-only"><?php echo $this->__('Edit item') ?></span>
      </a>
    <?php endif ?>
  </td>
</tr>

<tr>
  <th><?php echo $this->__('Price'); ?></th>
  <td>
    <?php if ($canApplyMsrp): ?>

      <span class="map-cart-sidebar-item"><?php echo $this->__('See price before order confirmation.'); ?></span>

    <?php else: ?>

      <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
          <?php echo $this->__('Excl. Tax'); ?>:
        <?php endif; ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
          <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?>
        <?php else: ?>
          <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
        <?php endif; ?>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>
          <br/>
          <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
            <small>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                <span class="nobr"><?php echo $tax['title']; ?>
                  : <?php echo Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span>
              <?php endforeach; ?>
            </small>
          <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
              <span class="nobr">
                <small><?php echo $tax['title']; ?>
                  : <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></small>
              </span><br/>
            <?php endforeach; ?>
          <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
            <small>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                <span class="nobr"><?php echo $tax['title']; ?>
                  : <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
                <br/>
              <?php endforeach; ?>
            </small>
          <?php endif; ?>
          <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
            <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>
              :<br/> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?>
            </span>
          <?php endif; ?>
        <?php endif; ?>
      <?php endif; ?>



      <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
          <br/><?php echo $this->__('Incl. Tax'); ?>:
        <?php endif; ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
          <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
        <?php else: ?>
          <?php echo $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxDisposition()) ?>
        <?php endif; ?>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>
          <br/>
          <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
            <small>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                <span class="nobr"><?php echo $tax['title']; ?>
                  : <?php echo Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span><br/>
              <?php endforeach; ?>
            </small>
          <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
              <span class="nobr">
                <small><?php echo $tax['title']; ?>
                  : <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></small>
              </span>
            <?php endforeach; ?>
          <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
            <small>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                <span class="nobr"><?php echo $tax['title']; ?>
                  : <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
                <br/>
              <?php endforeach; ?>
            </small>
          <?php endif; ?>
          <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
            <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>
              :<br/> <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
            </span>
          <?php endif; ?>
        <?php endif; ?>
      <?php endif; ?>

    <?php endif; //Can apply MSRP ?>
  </td>
</tr>

<tr class="qty-wrapper">
  <th><?php echo $this->__('Qty'); ?></th>
  <td>
    <div class="input-group input-group-sm minicart-input-group-qty">
      <input
        id="qinput-<?php echo $_item->getId(); ?>"
        data-link="<?php echo $this->getAjaxUpdateUrl() ?>"
        data-item-id="<?php echo $_item->getId(); ?>"
        class="qty cart-item-quantity input-text form-control"
        name=""
        value="<?php echo $this->getQty() ?>"
        required
        type="number"
        <?php if ($this->isOnCheckoutPage()) echo 'disabled'; ?>
        >
      <span class="input-group-btn">
        <button id="qbutton-<?php echo $_item->getId(); ?>"
                data-item-id="<?php echo $_item->getId(); ?>"
                disabled="disabled"
                data-update
                class="btn btn-primary quantity-button">
          <?php echo $this->__('OK'); ?>
        </button>
      </span>
    </div>
    <!-- /input-group -->
  </td>
</tr>

<?php if ($_options = $this->getOptionList()): ?>

  <?php foreach ($_options as $_option) : ?>
    <tr>
      <th>
        <?php echo $this->escapeHtml($_option['label']) ?>
      </th>
      <td>
        <?php if (is_array($_option['value'])): ?>
          <?php echo nl2br(implode("\n", $_option['value'])) ?>
        <?php else: ?>
          <?php echo $_option['value'] ?>
        <?php endif; ?>
      </td>
    </tr>
  <?php endforeach; ?>

<?php endif; ?>
