<?php
/**
 * Shoping cart sidebar
 *
 * @var Mage_Checkout_Block_Cart_Minicart $this
 */

$_cartQty = $this->getSummaryCount();
if (empty($_cartQty)) {
  $_cartQty = 0;
}
?>

<div class="panel panel-default">

  <?php $_items = $this->getRecentItems() ?>
  <?php if (count($_items)): ?>

    <div class="panel-heading">
      <?php echo $this->__('Recently added item(s)') ?>
    </div>

    <div id="minicart-error-message" class="minicart-message"></div>
    <div id="minicart-success-message" class="minicart-message"></div>

    <table id="cart-sidebar" class="table minicart-table">
      <?php foreach ($_items as $_item): ?>
        <?php echo $this->getItemHtml($_item) ?>
      <?php endforeach; ?>

      <tr class="info minicart-subtotal">
        <?php if ($this->canApplyMsrp()): ?>

          <td colspan="2">
            <?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?>
          </td>

        <?php else: ?>

          <th>
            <?php echo $this->__('Cart Subtotal') ?>
          </th>

          <td>
            <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>

            <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
              <br/>
              (
              <?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?>
              <?php echo Mage::helper('tax')->getIncExcText(true) ?>
              )
            <?php endif; ?>
          </td>

        <?php endif; ?>
      </tr>
    </table>

    <?php echo $this->getChildHtml('cart_promotion') ?>

    <div class="panel-footer">
      <?php if ($_cartQty && $this->isPossibleOnepageCheckout()): ?>
        <?php echo $this->getChildHtml('extra_actions') ?>
      <?php endif ?>

      <div class="btn-group btn-group-justified" role="group">
        <a class="btn btn-info" href="<?php echo $this->getUrl('checkout/cart'); ?>">
          <?php echo $this->__('View Cart'); ?>
        </a>

        <?php if ($_cartQty && $this->isPossibleOnepageCheckout()): ?>
          <a title="<?php echo $this->__('Checkout') ?>"
             class="btn btn-primary"
             href="<?php echo $this->getCheckoutUrl() ?>">
            <?php echo $this->__('Checkout') ?>
          </a>
        <?php endif ?>
      </div>
    </div>


  <?php else: ?>

    <div class="panel-body">
      <?php echo $this->__('You have no items in your shopping cart.') ?>
    </div>

  <?php endif ?>

</div>
