<?php if ($this->getCheckout()->getStepData('billing', 'complete')): ?>

  <div class="panel-heading js-complete">
    <?= $this->__('Billing Address') ?>

    <button type="button"
            class="btn btn-default js-btn-edit-opc"
            data-target="billing">
      <i class="fa fa-pencil-square"></i>
      <?= $this->__('Change') ?>
    </button>
  </div>

  <div class="panel-body js-panel-body js-complete">
    <address><?= $this->getBilling()->format('html') ?></address>
  </div>

<?php else: ?>

  <div class="panel-heading">
    <?= $this->__('Billing Address') ?>
  </div>

<?php endif; ?>
