<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>

  <div class="panel-heading js-complete">
    <?= $this->__('Payment Method') ?>

    <button type="button"
            class="btn btn-default js-btn-edit-opc"
            data-target="payment">
      <i class="fa fa-pencil-square"></i>
      <?= $this->__('Change') ?>
    </button>
  </div>

  <div class="panel-body js-panel-body js-complete">
    <?= $this->getPaymentHtml() ?>
  </div>

<?php else: ?>

  <div class="panel-heading">
    <?= $this->__('Payment Method') ?>
  </div>

<?php endif; ?>

