<?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>

  <div class="panel-heading is-completed">
    <h3 class="panel-title">
      <?= $this->__('Shipping Address') ?>

      <a href="#" class="js-link-edit-opc link-edit-opc" data-target="shipping">
        <i class="fa fa-pencil"></i>
        <span class="sr-only"><?= $this->__('Change') ?></span>
      </a>
    </h3>
  </div>

  <div class="panel-body js-panel-body is-completed">
    <address><?= $this->getShipping()->format('html') ?></address>
  </div>

<?php else: ?>

  <div class="panel-heading">
    <h3 class="panel-title">
      <?= $this->__('Shipping Address') ?>
    </h3>
  </div>

<?php endif; ?>

