<?php if ($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>

  <div class="panel-heading is-completed">
    <h3 class="panel-title">
      <?= $this->__('Shipping Method') ?>

      <a href="#" class="js-link-edit-opc link-edit-opc" data-target="shipping_method">
        <i class="fa fa-pencil"></i>
        <span class="sr-only"><?= $this->__('Change') ?></span>
      </a>
    </h3>
  </div>

  <div class="panel-body js-panel-body is-completed">
    <?php if ($this->getShippingMethod()): ?>

      <?= $this->getShippingDescription() ?>

      <?php $_excl = $this->getShippingPriceExclTax(); ?>
      <?php $_incl = $this->getShippingPriceInclTax(); ?>

      <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
        <?= $_incl; ?>
      <?php else: ?>
        <?= $_excl; ?>
      <?php endif; ?>

      <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
        (<?= $this->__('Incl. Tax'); ?> <?= $_incl; ?>)
      <?php endif; ?>

    <?php else: ?>

      <?= $this->__('Shipping method has not been selected yet') ?>

    <?php endif; ?>
  </div>

<?php else: ?>

  <div class="panel-heading">
    <h3 class="panel-title">
      <?= $this->__('Shipping Method') ?>
    </h3>
  </div>

<?php endif; ?>

