<?php if ($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>

  <div class="panel-heading js-complete">
    <?= $this->__('Shipping Method') ?>

    <button type="button"
            class="btn btn-default js-btn-edit-opc"
            data-target="shipping_method">
      <i class="fa fa-pencil-square"></i>
      <?= $this->__('Change') ?>
    </button>
  </div>

  <div class="panel-body js-panel-body js-complete">
    <?php if ($this->getShippingMethod()): ?>

      <?= $this->getShippingDescription() ?>

      <?php $_excl = $this->getShippingPriceExclTax(); ?>
      <?php $_incl = $this->getShippingPriceInclTax(); ?>

      <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
        <?= $_incl; ?>
      <?php else: ?>
        <?= $_excl; ?>
      <?php endif; ?>

      <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
        (<?= $this->__('Incl. Tax'); ?> <?= $_incl; ?>)
      <?php endif; ?>

    <?php else: ?>

      <?= $this->__('Shipping method has not been selected yet') ?>

    <?php endif; ?>
  </div>

<?php else: ?>

  <div class="panel-heading">
    <?= $this->__('Shipping Method') ?>
  </div>

<?php endif; ?>

