<tr>
  <td colspan="<?= $this->getColspan(); ?>" style="<?= $this->getTotal()->getStyle() ?>">

    <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
      <strong><?= $this->escapeHtml($this->getTotal()->getTitle()); ?></strong>
    <?php else: ?>
      <?= $this->escapeHtml($this->getTotal()->getTitle()); ?>
    <?php endif; ?>

  </td>
  <td style="<?= $this->getTotal()->getStyle() ?>">

    <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
      <strong><?= $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    <?php else: ?>
      <?= $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
    <?php endif; ?>

  </td>
</tr>
