<?php /* @var $this Mage_Sales_Block_Billing_Agreements */ ?>



<div class="page-header">
  <h1><?= $this->__('Billing Agreements') ?></h1>
</div>

<div class="billing-agreements">

  <?php $billingAgreements = $this->getBillingAgreements(); ?>

  <?php if (count($billingAgreements) > 0): ?>

    <?= $this->getChildHtml('pager'); ?>

    <table id="billing-agreements" class="table table-bordered table-hover">

      <thead>
      <tr>
        <th><span class="nobr"><?= $this->__('Reference ID'); ?></span></th>
        <th><?= $this->__('Status'); ?></th>
        <th><span class="nobr"><?= $this->__('Created At'); ?></span></th>
        <th><span class="nobr"><?= $this->__('Updated At'); ?></span></th>
        <th><span class="nobr"><?= $this->__('Payment Method'); ?></span></th>
        <th>&nbsp;</th>
      </tr>
      </thead>

      <tbody>
      <?php foreach ($billingAgreements as $item): ?>
        <tr>
          <td><span class="nobr"><?= $this->getItemValue($item, 'reference_id') ?></span></td>
          <td><?= $this->getItemValue($item, 'status') ?></td>
          <td><span class="nobr"><?= $this->getItemValue($item, 'created_at') ?></span></td>
          <td><span class="nobr"><?= $this->getItemValue($item, 'updated_at') ?></span></td>
          <td><?= $this->getItemValue($item, 'payment_method_label') ?></td>
          <td><a href="<?= $this->getItemValue($item, 'edit_url') ?>"><?= $this->__('View') ?></a></td>
        </tr>
      <?php endforeach; ?>
      </tbody>

    </table>

  <?php else: ?>

    <p class="text-info"><?= $this->__('There are no billing agreements yet.') ?></p>

  <?php endif; ?>

  <?php $paymentMethods = $this->getWizardPaymentMethodOptions() ?>
  <?php if ($paymentMethods): ?>
    <h2 class="box-title"><?= $this->__('New Billing Agreement') ?></h2>
    <p class="text-info"><?= $this->__('You will be redirected to the payment system website.') ?></p>

    <form action="<?= $this->getCreateUrl() ?>" method="post" class="form-inline" role="form">

      <div class="form-group">
        <div class="input-group">
          <label class="sr-only" for="payment_method">Payment Method</label>
          <select id="payment_method" name="payment_method" class="form-control">
            <option value=""><?= $this->__('-- Please Select --') ?></option>
            <?php foreach ($paymentMethods as $code => $title): ?>
              <option value="<?= $code ?>"><?= $title ?></option>
            <?php endforeach; ?>
          </select>
        </div>
      </div>

      <button type="submit" class="btn btn-default"><?= $this->__('Create...') ?></button>
    </form>
  <?php endif; ?>

  <a href="<?= $this->escapeHtml($this->getBackUrl()) ?>" class="btn btn-default">
    <i class="fa fa-angle-double-left"></i>
    <?= $this->__('Back') ?>
  </a>
</div>
