<div class="page-header">
  <h1><?= $this->__('All Tags') ?></h1>
</div>

<?php if (sizeof($this->getTags()) > 0): ?>

  <ul class="list-inline">
    <?php foreach ($this->getTags() as $_tag): ?>
      <li>
        <a href="<?= $_tag->getTaggedProductsUrl() ?>"
           style="font-size:<?= $_tag->getRatio() * 70 + 75 ?>%;">
          <?= $this->escapeHtml($_tag->getName()) ?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>

<?php else: ?>

  <p class="text-info"><?= $this->__('There are no tags available.') ?></p>

<?php endif; ?>
