<div class="page-header">
  <h1><?php echo $this->__('All Tags') ?></h1>
</div>

<?php if (sizeof($this->getTags()) > 0): ?>

  <ul class="list-inline">
    <?php foreach ($this->getTags() as $_tag): ?>
      <li>
        <a href="<?php echo $_tag->getTaggedProductsUrl() ?>"
           style="font-size:<?php echo $_tag->getRatio() * 70 + 75 ?>%;">
          <?php echo $this->escapeHtml($_tag->getName()) ?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>

<?php else: ?>

  <p class="text-info"><?php echo $this->__('There are no tags available.') ?></p>

<?php endif; ?>
