<div class="panel panel-default">

  <div class="panel-heading">
    <?php echo $this->__('Popular Tags'); ?>
  </div>

  <div class="panel-body">

    <ul class="list-inline">
      <?php foreach ($this->getTags() as $_tag): ?>
        <li>
          <a href="<?php echo $_tag->getTaggedProductsUrl() ?>"
             style="font-size:<?php echo $_tag->getRatio() * 70 + 75 ?>%;">
            <?php echo $this->escapeHtml($_tag->getName()) ?>
          </a>
        </li>
      <?php endforeach; ?>
    </ul>

  </div>

  <div class="panel-footer">
    <a href="<?php echo $this->getUrl('tag/list') ?>" class="btn btn-default">
      <?php echo $this->__('View All Tags') ?>
    </a>
  </div>

</div>
