<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Grandtotal
 * @see Mage_Tax_Block_Checkout_Grandtotal
 */
?>
<?php if ($this->includeTax() && $this->getTotalExclTax() >= 0): ?>

  <tr>
    <td style="<?= $this->getStyle() ?>" colspan="<?= $this->getColspan(); ?>">
      <strong><?= $this->helper('tax')->__('Grand Total Excl. Tax') ?></strong>
    </td>
    <td style="<?= $this->getStyle() ?>" >
      <strong><?= $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></strong>
    </td>
  </tr>

  <?= $this->renderTotals('taxes', $this->getColspan()); ?>

  <tr>
    <td style="<?= $this->getStyle() ?>" colspan="<?= $this->getColspan(); ?>">
      <strong><?= $this->helper('tax')->__('Grand Total Incl. Tax') ?></strong>
    </td>
    <td style="<?= $this->getStyle() ?>">
      <strong><?= $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
  </tr>

<?php else: ?>

  <tr>
    <td style="<?= $this->getStyle() ?>" colspan="<?= $this->getColspan(); ?>">
      <strong><?= $this->getTotal()->getTitle() ?></strong>
    </td>
    <td style="<?= $this->getStyle() ?>">
      <strong><?= $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
  </tr>

<?php endif; ?>
