<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Shipping
 * @see Mage_Tax_Block_Checkout_Shipping
 */
?>

<?php if ($this->displayBoth()): ?>

  <tr>
    <td style="<?= $this->getStyle() ?>" colspan="<?= $this->getColspan(); ?>">
      <?= $this->getExcludeTaxLabel() ?>
    </td>
    <td style="<?= $this->getStyle() ?>">
      <?= $this->helper('checkout')->formatPrice($this->getShippingExcludeTax()) ?>
    </td>
  </tr>
  <tr>
    <td style="<?= $this->getStyle() ?>" colspan="<?= $this->getColspan(); ?>">
      <?= $this->getIncludeTaxLabel() ?>
    </td>
    <td style="<?= $this->getStyle() ?>">
      <?= $this->helper('checkout')->formatPrice($this->getShippingIncludeTax()) ?>
    </td>
  </tr>

<?php elseif ($this->displayIncludeTax()) : ?>

  <tr>
    <td style="<?= $this->getStyle() ?>" colspan="<?= $this->getColspan(); ?>">
      <?= $this->getTotal()->getTitle() ?>
    </td>
    <td style="<?= $this->getStyle() ?>">
      <?= $this->helper('checkout')->formatPrice($this->getShippingIncludeTax()) ?>
    </td>
  </tr>

<?php else: ?>

  <tr>
    <td style="<?= $this->getStyle() ?>" colspan="<?= $this->getColspan(); ?>">
      <?= $this->escapeHtml($this->getTotal()->getTitle()) ?>
    </td>
    <td style="<?= $this->getStyle() ?>">
      <?= $this->helper('checkout')->formatPrice($this->getShippingExcludeTax()) ?>
    </td>
  </tr>

<?php endif; ?>
