<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Subtotal
 * @see Mage_Tax_Block_Checkout_Subtotal
 */
?>
<?php if ($this->displayBoth()): ?>

  <tr>
    <td style="<?= $this->getStyle() ?>" colspan="<?= $this->getColspan(); ?>">
      <?= $this->helper('tax')->__('Subtotal (Excl. Tax)') ?>
    </td>
    <td style="<?= $this->getStyle() ?>">
      <?= $this->helper('checkout')->formatPrice($this->getTotal()->getValueExclTax()) ?>
    </td>
  </tr>
  <tr>
    <td style="<?= $this->getStyle() ?>" colspan="<?= $this->getColspan(); ?>">
      <?= $this->helper('tax')->__('Subtotal (Incl. Tax)') ?>
    </td>
    <td style="<?= $this->getStyle() ?>">
      <?= $this->helper('checkout')->formatPrice($this->getTotal()->getValueInclTax()) ?>
    </td>
  </tr>

<?php else : ?>

  <tr>
    <td style="<?= $this->getStyle() ?>" colspan="<?= $this->getColspan(); ?>">
      <?= $this->getTotal()->getTitle() ?>
    </td>
    <td style="<?= $this->getStyle() ?>">
      <?= $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
    </td>
  </tr>

<?php endif; ?>
