<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Tax
 * @see Mage_Tax_Block_Checkout_Tax
 */

$_value = $this->getTotal()->getValue();
$_style = $this->getTotal()->getStyle();

global $taxIter;
$taxIter++;
?>

<?php if ($this->helper('tax')->displayFullSummary() && $_value != 0): ?>

  <?php $isTop = 1; ?>
  <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>

    <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>

    <?php $percent = $info['percent']; ?>
    <?php $amount = $info['amount']; ?>
    <?php $rates = $info['rates']; ?>
    <?php $isFirst = 1; ?>

    <?php foreach ($rates as $rate): ?>

      <tr class="summary-details summary-details-<?= $taxIter ?> <?php if ($isTop): ?>summary-details-first<?php endif ?>">

        <td style="<?= $_style ?>" colspan="<?= $this->getColspan(); ?>">
          <?= $this->escapeHtml($rate['title']); ?>
          <?php if (!is_null($rate['percent'])): ?>
            (<?= (float)$rate['percent']; ?>%)
          <?php endif ?>
        </td>

        <?php if ($isFirst): ?>
          <td style="<?= $_style ?>" rowspan="<?= count($rates); ?>">
            <?= $this->helper('checkout')->formatPrice($amount); ?>
          </td>
        <?php endif ?>

      </tr>

      <?php $isFirst = 0; ?>
      <?php $isTop = 0; ?>

    <?php endforeach; ?>
  <?php endforeach; ?>

  <?php $weees = $this->getAllWeee(); ?>
  <?php foreach ($weees as $weeeTitle => $weeeAmount): ?>

    <tr class="summary-details summary-details-<?= $taxIter ?> <?php if ($isTop): ?>summary-details-first<?php endif ?>">
      <td style="<?= $_style ?>" colspan="<?= $this->getColspan(); ?>"><?= $this->escapeHtml($weeeTitle); ?></td>
      <td style="<?= $_style ?>" rowspan="1"><?= $this->helper('checkout')->formatPrice($weeeAmount); ?></td>
    </tr>

  <?php endforeach; ?>

<?php endif ?>

<tr
  <?php if ($this->helper('tax')->displayFullSummary() && $_value != 0): ?>
    class="summary-total js-toggle-tax-details"
    data-target=".summary-details-<?= $taxIter ?>"
  <?php endif ?>
  >

  <td style="<?= $_style ?>" colspan="<?= $this->getColspan(); ?>"><?= $this->getTotal()->getTitle() ?></td>
  <td style="<?= $_style ?>"><?= $this->helper('checkout')->formatPrice($_value) ?></td>

</tr>
