<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if ($this->canShowBlock()): ?>
  <div class="<?php if (!$this->getLayer()->getState()->getFilters()): ?> no-filters<?php endif; ?>">

    <h4><?php echo $this->__('Shop By') ?></h4>

    <?php echo $this->getStateHtml() ?>

    <?php if ($this->canShowOptions()): ?>

      <div class="well">

        <?php $_filters = $this->getFilters() ?>

        <?php foreach ($_filters as $_filter): ?>
          <?php if ($_filter->getItemsCount()): ?>

            <div class="panel panel-default">
              <div class="panel-heading">
                <?php echo $this->__($_filter->getName()) ?>
              </div>
              <?php echo $_filter->getHtml() ?>
            </div>

          <?php endif; ?>
        <?php endforeach; ?>

      </div>
    <?php endif; ?>

  </div>
<?php endif; ?>
