<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if ($this->canShowBlock()): ?>

  <div class="panel panel-default panel-collapse-mobile">


    <div class="panel-heading" role="tab" id="panel-heading-filter">
      <div class="panel-title">
        <a data-toggle="collapse"
           aria-expanded="false"
           aria-controls="panel-collapse-filter"
           href="#panel-collapse-filter">
          <?= $this->__('Shop By') ?>
        </a>
      </div>
    </div>

    <div class="panel-collapse collapse"
         id="panel-collapse-filter"
         role="tabpanel"
         aria-labelledby="panel-heading-filter"
         aria-expanded="false"
      >
      <div class="panel-body">

        <?= $this->getStateHtml() ?>

        <div class="panel-group panel-group-filter<?php if (!$this->getLayer()->getState()->getFilters()): ?> no-filter<?php endif; ?>"
             id="accordion-filter"
             role="tablist"
             aria-multiselectable="true"
          >

          <?php if ($this->canShowOptions()): ?>

            <?php $_filters = $this->getFilters() ?>

            <?php foreach ($_filters as $_filter): ?>
              <?php if ($_filter->getItemsCount()): ?>

                <?php
                $filterId = $_filter->getAttributeModel() ? $_filter->getAttributeModel()->getAttributeCode() : $_filter->getName();
                $filterId = strtolower(str_replace('_', '-', $filterId));
                $panelHeadingId = 'panel-heading-' . $filterId;
                $listGroupId = 'panel-collapse-' . $filterId;
                ?>
                <div class="panel panel-primary">
                  <div class="panel-heading" role="tab" id="<?= $panelHeadingId ?>">
                    <div class="panel-title">
                      <a data-toggle="collapse"
                         data-parent="#accordion-filter"
                         class="link-toggle-collapse"
                         aria-expanded="false"
                         aria-controls="<?= $listGroupId ?>"
                         href="#<?= $listGroupId ?>">
                        <?= $this->__($_filter->getName()) ?>
                      </a>
                    </div>
                  </div>
                  <div class="panel-collapse collapse"
                       id="<?= $listGroupId ?>"
                       role="tabpanel"
                       aria-labelledby="<?= $listGroupId ?>"
                       aria-expanded="false"
                    >
                    <?= $_filter->getHtml() ?>
                  </div>
                </div>

              <?php endif; ?>
            <?php endforeach; ?>

          <?php endif; ?>

        </div>

      </div>
    </div>

  </div>

<?php endif; ?>
