<?php /* @var $this Mage_ConfigurableSwatches_Block_Catalog_Media_Js_Abstract */ ?>
<script>
  var configurableSwatches = {
    imageType: '<?= $this->getImageType(); ?>',

    imageFallback: {
      <?php
      foreach ($this->getProductImageFallbacks() as $imageFallback) {
        printf("%s: %s,\n", $imageFallback['product']->getId(), $imageFallback['image_fallback']);
      }
      ?>
    }
  };
</script>
