<?php
/**
 * Shopping cart template
 *
 * @var $this Mage_Checkout_Block_Cart
 */
?>
<?php $_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price'; ?>
<div class="cart <?= $_priceDisplay; ?>">

  <h1><?= $this->__('Shopping Cart') ?></h1>

  <?php if (!$this->hasError()): ?>
    <div>
      <?php foreach ($this->getMethods('top_methods') as $method): ?>
        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
          <?= $methodHtml; ?>
        <?php endif; ?>
      <?php endforeach; ?>
    </div>
  <?php endif; ?>

  <?= $this->getMessagesBlock()->toHtml() ?>

  <?= $this->getChildHtml('form_before') ?>

  <form action="<?= $this->getUrl('checkout/cart/updatePost') ?>" method="post" role="form">

    <?= $this->getBlockHtml('formkey'); ?>

    <table id="shopping-cart-table" class="table table-striped">

      <col width="1"/>
      <col width="1"/>
      <col width="1"/>
      <col width="1"/>
      <col width="1"/>
      <col width="1"/>
      <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1"/>
        <col width="1"/>
      <?php endif; ?>

      <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>

      <thead>
      <tr>
        <th rowspan="<?= $mergedCells; ?>">
          <?= $this->__('Product') ?>
        </th>

        <th rowspan="<?= $mergedCells; ?>">&nbsp;</th>

        <th colspan="<?= $mergedCells; ?>">
          <?= $this->__('Price') ?>
        </th>

        <th rowspan="<?= $mergedCells; ?>">
          <?= $this->__('Qty') ?>
        </th>

        <th colspan="<?= $mergedCells; ?>">
          <?= $this->__('Subtotal') ?>
        </th>

        <th rowspan="<?= $mergedCells; ?>">&nbsp;</th>

      </tr>

      <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <tr>
          <th><?= $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
          <th><?= $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
          <th><?= $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
          <th><?= $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
        </tr>
      <?php endif; ?>
      </thead>

      <tfoot>
      <tr>
        <td colspan="50">

          <!-- Make this button the first responder rather than empty cart -->
          <!--          <button type="submit"-->
          <!--                  style="visibility:hidden;"-->
          <!--                  name="update_cart_action"-->
          <!--                  value="update_qty"-->
          <!--                  title="--><?php //echo $this->__('Update Shopping Cart'); ?><!--"-->
          <!--                  class="btn btn-default">-->
          <!--            --><?php //echo $this->__('Update Shopping Cart'); ?>
          <!--          </button>-->
          <div class="pull-right">
            <button type="submit"
                    name="update_cart_action"
                    value="update_qty"
                    title="<?= $this->__('Update Shopping Cart'); ?>"
                    class="btn btn-primary">
              <?= $this->__('Update Shopping Cart'); ?>
            </button>

            <?php if ($this->getContinueShoppingUrl()): ?>
              <a title="<?= $this->__('Continue Shopping') ?>"
                 class="btn btn-primary"
                 href="<?= $this->getContinueShoppingUrl() ?>">
                <?= $this->__('Continue Shopping') ?>
              </a>
            <?php endif; ?>
          </div>

          <button type="submit"
                  name="update_cart_action"
                  value="empty_cart"
                  title="<?= $this->__('Empty Cart'); ?>"
                  class="btn btn-danger"
                  id="empty_cart_button">
            <?= $this->__('Empty Cart'); ?>
          </button>

        </td>
      </tr>
      </tfoot>

      <tbody>
      <?php foreach ($this->getItems() as $_item): ?>
        <?= $this->getItemHtml($_item) ?>
      <?php endforeach ?>
      </tbody>

    </table>
  </form>

  <?= $this->getChildHtml('shopping.cart.table.after'); ?>

  <div class="cart-forms">
    <?php /* Extensions placeholder */ ?>
    <?= $this->getChildHtml('checkout_cart_widget') ?>
    <?= $this->getChildHtml('coupon') ?>
    <?= $this->getChildHtml('checkout.cart.extra') ?>
    <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
  </div>

  <div class="cart-totals">

    <?= $this->getChildHtml('totals'); ?>

    <?php if (!$this->hasError()): ?>
      <div>
        <?php foreach ($this->getMethods('methods') as $method): ?>
          <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <?= $methodHtml; ?>
          <?php endif; ?>
        <?php endforeach; ?>
      </div>
    <?php endif; ?>

  </div>

  <?= $this->getChildHtml('crosssell') ?>

</div>
