<div class="page-header">
  <h1><?= $this->__('Checkout') ?></h1>
</div>

<div id="checkoutSteps"
     class="panel-group opc opc-firststep-<?= $this->getActiveStep() ?>"
     data-active-step="opc-<?= $this->getActiveStep() ?>"
     data-progress-url="<?= $this->getUrl('checkout/onepage/progress') ?>"
     data-review-url="<?= $this->getUrl('checkout/onepage/review') ?>"
     data-save-method-url="<?= $this->getUrl('checkout/onepage/saveMethod') ?>"
     data-failure-url="<?= $this->getUrl('checkout/cart') ?>"
  >
  <?php foreach ($this->getSteps() as $_stepId => $_stepInfo): ?>
    <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()) continue ?>

    <div id="opc-<?= $_stepId ?>"
         class="panel panel-checkout section<?php
         echo !empty($_stepInfo['allow']) ? ' allow' : '';
         echo !empty($_stepInfo['complete']) ? ' saved' : '' ?>"
      >

      <div class="panel-heading">
        <h2 class="step-title panel-title">
          <?= $_stepInfo['label'] ?>
          <a href="#" class="link-opc-edit-step">
            <i class="fa fa-pencil"></i>
            <span class="sr-only"><?= $this->__('Edit') ?></span>
          </a>
        </h2>
      </div>


      <div id="checkout-step-<?= $_stepId ?>" class="panel-body step a-item" style="display:none;">
        <?= $this->getChildHtml($_stepId) ?>
      </div>

    </div>

  <?php endforeach ?>
</div>

