<h1><?= $this->__('Your order has been received.') ?></h1>

<?= $this->getMessagesBlock()->toHtml() ?>

<h2><?= $this->__('Thank you for your purchase!') ?></h2>

<?php if ($this->getOrderId()): ?>

  <?php if ($this->getCanViewOrder()) : ?>
    <p>
      <?= $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>',
        $this->escapeHtml($this->getViewOrderUrl()),
        $this->escapeHtml($this->getOrderId()))) ?>
    </p>
  <?php else : ?>
    <p><?= $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
  <?php endif; ?>

  <p>
    <?= $this->__(
      'You will receive an order confirmation email with details of your order and a link to track its progress.'
    ) ?>
  </p>

  <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) : ?>
    <p>
      <?= $this->__(
        'Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.',
        $this->getPrintUrl()) ?>
      <?= $this->getChildHtml() ?>
    </p>
  <?php endif; ?>

<?php endif; ?>

<?php if ($this->getAgreementRefId()): ?>
  <p>
    <?= $this->__(
      'Your billing agreement # is: %s.',
      sprintf(
        '<a href="%s">%s</a>',
        $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())
      )) ?>
  </p>
<?php endif; ?>

<?php if ($profiles = $this->getRecurringProfiles()): ?>
  <p><?= $this->__('Your recurring payment profiles:'); ?></p>
  <ul>
    <?php foreach ($profiles as $profile): ?>
      <?php
      $profileIdHtml = ($this->getCanViewProfiles() ?
        sprintf(
          '<a href="%s">%s</a>',
          $this->escapeHtml($this->getProfileUrl($profile)),
          $this->escapeHtml($this->getObjectData($profile, 'reference_id'))
        )
        :
        $this->escapeHtml($this->getObjectData($profile, 'reference_id')));
      ?>
      <li>
        <?= $this->__(
          'Payment profile # %s: "%s".',
          $profileIdHtml,
          $this->escapeHtml($this->getObjectData($profile, 'schedule_description'))
        ) ?>
      </li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>

<a class="btn btn-default"
   title="<?= $this->__('Continue Shopping') ?>"
   href="<?= $this->getUrl() ?>">
  <?= $this->__('Continue Shopping') ?>
</a>
