<?php foreach ($types as $type) : ?>
  <?php if ($messages = $this->getMessages($type)) : ?>
    <div class="alert alert-<?php echo $type ?> alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <?php foreach ($messages as $message) : ?>
        <p>$message->getText()</p>
      <?php endforeach ?>
    </div>
  <?php endif ?>
<?php endforeach ?>
