<?php
/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Items */
$columns = $this->getColumns();
?>
<table class="table table-bordered" id="wishlist-table">
  <thead>
  <tr>
    <?php
    /* @var $column Mage_Wishlist_Block_Customer_Wishlist_Item_Column */
    foreach ($columns as $column):
      $_blockName = str_replace('.', '-', strtolower($column->getNameInLayout()));
      ?>
      <th class="<?= $_blockName; ?>"><?= $column->getTitle(); ?></th>
    <?php endforeach; ?>
  </tr>
  </thead>

  <tbody>
  <?php if (count($this->getItems())): ?>

    <?php foreach ($this->getItems() as $item): ?>

      <tr id="item_<?= $item->getId(); ?>">
        <?php
        foreach ($columns as $key => $column):
          $_blockName = str_replace('.', '-', strtolower($column->getNameInLayout()));

          /* Override default column title in layout, useful for certain cases like select all box */
          if ($column->getRwdTitle()) {
            $_rwdLabel = $column->getRwdTitle();
          } else {
            $_rwdLabel = ($column->getTitle()) ? $column->getTitle() : false;
          }
          ?>
          <td class="<?= 'wishlist-cell' . $key; ?> <?= $_blockName; ?>"
            <?php if ($_rwdLabel): ?> data-rwd-label="<?= $_rwdLabel; ?>"<?php endif; ?>
            >
            <?php
            $column->setItem($item);
            echo $column->toHtml($item);
            ?>
          </td>
        <?php endforeach; ?>
      </tr>

    <?php endforeach ?>

  <?php else: ?>

    <td colspan="<?= count($columns); ?>" class="text-info">
      <?= $this->__('This Wishlist has no Items'); ?>
    </td>

  <?php endif; ?>
  </tbody>

</table>

<?php foreach ($columns as $column): ?>
  <?= $column->getAdditionalHtml(); ?>
<?php endforeach; ?>

<script>
  <?php foreach ($columns as $column): ?>
  <?= $column->getJs();?>
  <?php endforeach; ?>
</script>
