<form id="discount-coupon-form"
      class="form-inline"
      action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>"
      method="post"
      role="form"
  >

  <input type="hidden" name="remove" id="remove-coupon" value="0"/>

  <h2><?php echo $this->__('Discount Codes') ?></h2>

  <div class="form-group">

    <label class="sr-only" for="coupon_code"><?php echo $this->__('Discount Codes') ?></label>

    <input class="form-control"
           type="text"
           id="coupon_code"
           name="coupon_code"
           placeholder="<?php echo $this->__('Discount Codes') ?>"
           value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>"/>

    <button type="button"
            id="btn_coupon_apply"
            title="<?php echo $this->__('Apply') ?>"
            class="btn btn-primary"
            value="<?php echo $this->__('Apply') ?>">
      <?php echo $this->__('Apply') ?>
    </button>

    <?php if (strlen($this->getCouponCode())): ?>
      <button type="button"
              id="btn_coupon_remove"
              title="<?php echo $this->__('Cancel') ?>"
              class="btn btn-danger"
              value="<?php echo $this->__('Cancel') ?>">
        <?php echo $this->__('Cancel') ?>
      </button>
    <?php endif; ?>

  </div>

</form>

