<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php if ($this->getItemCount()): ?>
  <div class="panel panel-default panel-crosssell">
    <div class="panel-heading">

      <h2 class="panel-title">
        <?= $this->__('Based on your selection, you may be interested in the following items:') ?>
      </h2>

    </div>
    <div class="panel-body">

      <?= $this->getChild('product-collection')->setProductCollection($this->getItems())->toHtml() ?>

    </div>
  </div>
<?php endif; ?>
