<?php
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */

$_cartQty = $this->getSummaryCount();
if (empty($_cartQty)) {
  $_cartQty = 0;
}
?>

<div class="btn-group" role="group">
  <button type="button"
          class="btn btn-primary btn-minicart"
          data-toggle="dropdown"
          aria-expanded="false"
    >
    <?php echo Mage::helper('vr_kiwiberry')->getSvgIcon('shopping-cart') ?>
    <span class="btn-title"><?php echo $this->__('Mini Cart') ?></span>
    <span class="js-minicart-count"><?php echo $_cartQty; ?></span>
    <span class="caret"></span>
  </button>

  <?php echo $this->getChildHtml('minicart_content'); ?>
</div>
