<h1><?= $this->__('Shopping Cart is Empty') ?></h1>

<div class="cart-empty">

  <?= $this->getMessagesBlock()->toHtml() ?>

  <?= $this->getChildHtml('checkout_cart_empty_widget'); ?>

  <p><?= $this->__('You have no items in your shopping cart.') ?></p>

  <p><?= $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getContinueShoppingUrl()) ?></p>

  <?= $this->getChildHtml('shopping.cart.table.after'); ?>

</div>
