<?php /** @var $this Mage_Checkout_Block_Cart_Shipping */ ?>

<div class="panel panel-default">
  <div class="panel-heading">

    <h2 class="panel-title"><?= $this->__('Estimate Shipping and Tax') ?></h2>

  </div>
  <div class="panel-body">
    <form action="<?= $this->getUrl('checkout/cart/estimatePost') ?>"
          method="post"
          id="shipping-zip-form"
          class="shipping-zip-form"
          data-regions="<?= $this->escapeHtml($this->helper('directory')->getRegionJsonByStore()) ?>"
          role="form">

      <p class="text-info"><?= $this->__('Enter your destination to get a shipping estimate.') ?></p>

      <div class="form-group">
        <label for="country" class="required"><?= $this->__('Country') ?></label>

        <?= Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId()) ?>
      </div>

      <div class="form-group">
        <label for="region_id" class="required"><?= $this->__('State/Province') ?></label>

        <select id="region_id"
                name="region_id"
                title="<?= $this->__('State/Province') ?>"
                style="display:none;"
                class="form-control<?= ($this->isStateProvinceRequired() ? ' validate-select' : '') ?>"
                defaultValue="<?= $this->getEstimateRegionId() ?>">
          <option value=""><?= $this->__('Please select region, state or province') ?></option>
        </select>

        <input type="text"
               id="region"
               name="region"
               value="<?= $this->escapeHtml($this->getEstimateRegion()) ?>"
               title="<?= $this->__('State/Province') ?>"
               placeholder="<?= $this->__('State/Province') ?>"
               class="form-control"
               style="display:none;">
      </div>

      <?php if ($this->getCityActive()): ?>
        <div class="form-group">
          <label for="city" class="<?php if ($this->isCityRequired()) echo ' required' ?>">
            <?= $this->__('City') ?>
          </label>

          <input class="form-control<?php if ($this->isCityRequired()): ?> required-entry<?php endif; ?>"
                 id="city"
                 type="text"
                 name="estimate_city"
                 value="<?= $this->escapeHtml($this->getEstimateCity()) ?>">
        </div>
      <?php endif; ?>

      <div class="form-group">
        <label for="zip" class="required">
          <?= $this->__('Zip') ?>
        </label>

        <input class="form-control validate-postcode<?php if ($this->isZipCodeRequired()): ?> required-entry<?php endif; ?>"
               type="text"
               id="zip"
               name="estimate_postcode"
               title="<?= $this->__('Zip') ?>"
               placeholder="<?= $this->__('Zip') ?>"
               value="<?= $this->escapeHtml($this->getEstimatePostcode()) ?>">
      </div>

      <button type="button"
              id="btn_estimate_shipping"
              title="<?= $this->__('Estimate') ?>"
              class="btn btn-default">
        <?= $this->__('Estimate') ?>
      </button>

    </form>

    <?php if (($_shippingRateGroups = $this->getEstimateRates())): ?>
      <form id="cart-shipping-method-form"
            action="<?= $this->getUrl('checkout/cart/estimateUpdatePost') ?>"
            role="form">

        <?php foreach ($_shippingRateGroups as $code => $_rates): ?>

          <div class="form-group">

            <label><?= $this->escapeHtml($this->getCarrierName($code)) ?></label>

            <?php foreach ($_rates as $_rate): ?>

              <?php if ($_rate->getErrorMessage()): ?>

                <?= $this->escapeHtml($_rate->getErrorMessage()) ?>

              <?php else: ?>

                <div class="radio">
                  <label for="s_method_<?= $_rate->getCode() ?>">
                    <input name="estimate_method"
                           type="radio"
                           value="<?= $this->escapeHtml($_rate->getCode()) ?>"
                           id="s_method_<?= $_rate->getCode() ?>"
                           <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>checked=<?php endif ?>
                      >

                    <?= $this->escapeHtml($_rate->getMethodTitle()) ?>
                    -
                    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                    <?= $_excl; ?>

                    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                      (<?= $this->__('Incl. Tax'); ?> <?= $_incl; ?>)
                    <?php endif; ?>
                  </label>
                </div>

              <?php endif ?>

            <?php endforeach; ?>

          </div>

        <?php endforeach; ?>

        <button type="submit"
                title="<?= $this->__('Update Total') ?>"
                class="btn btn-default"
                name="do"
                value="<?= $this->__('Update Total') ?>">
          <?= $this->__('Update Total') ?>
        </button>

      </form>
    <?php endif; ?>
  </div>
</div>
