<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 * @var $this Mage_Checkout_Block_Cart_Totals
 */
?>
<?php if ($this->canApplyMsrp()): ?>

    <div class="cart-msrp-totals"><?= $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></div>

<?php else: ?>

    <table id="shopping-cart-totals-table" class="table table-hover table-condensed">
        <col />
        <col width="1" />
        <tfoot>
            <?= $this->renderTotals('footer'); ?>
        </tfoot>
        <tbody>
            <?= $this->renderTotals(); ?>
        </tbody>
    </table>

<?php endif; ?>
