<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 * @var $this Mage_Checkout_Block_Cart_Totals
 */
?>
<?php if ($this->canApplyMsrp()): ?>

  <p class="cart-msrp-totals text-info">
    <?= $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?>
  </p>

<?php else: ?>

  <table id="shopping-cart-totals-table" class="table-total table table-hover table-bordered">
    <colgroup>
      <col>
      <col width="1">
    </colgroup>

    <tfoot><?= $this->renderTotals('footer'); ?></tfoot>
    <tbody><?= $this->renderTotals(); ?></tbody>
  </table>

<?php endif; ?>
