<?php $_order = $this->getOrder() ?>

<p>
  <a href="<?= $this->getPrintAllInvoicesUrl($_order) ?>"
     target="_blank"
     class="btn btn-default">
    <?= $this->__('Print All Invoices') ?>
  </a>
</p>

<?php foreach ($_order->getInvoiceCollection() as $_invoice): ?>

  <h2>
    <?= $this->__('Invoice #') . $_invoice->getIncrementId(); ?>

    <small>
      <a href="<?= $this->getPrintInvoiceUrl($_invoice) ?>"
         target="_blank">
        <?= $this->__('Print Invoice') ?>
      </a>
    </small>
  </h2>

  <h3><?= $this->__('Items Invoiced') ?></h3>

  <table class="table table-bordered table-invoice" id="my-invoice-table-<?= $_invoice->getId(); ?>">

    <thead>
    <tr>
      <th><?= $this->__('Product Name') ?></th>
      <th><?= $this->__('SKU') ?></th>
      <th><?= $this->__('Price') ?></th>
      <th><span class="nobr"><?= $this->__('Qty Invoiced') ?></span></th>
      <th><?= $this->__('Subtotal') ?></th>
    </tr>
    </thead>

    <tfoot><?= $this->getInvoiceTotalsHtml($_invoice) ?></tfoot>

    <tbody>
    <?php foreach ($_invoice->getAllItems() as $_item): ?>
      <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
      <?= $this->getItemHtml($_item) ?>
    <?php endforeach; ?>
    </tbody>

  </table>

  <?= $this->getInvoiceCommentsHtml($_invoice) ?>

<?php endforeach; ?>
