<?php /* @var $this Mage_Sales_Block_Recurring_Profile_View */ ?>

<?php if ($this->getIsAddress()): ?>

  <?php foreach ($this->getRenderedInfo() as $row): ?>
    <div class="panel-body">
      <address><?php echo nl2br($this->escapeHtml($this->getObjectData($row, 'value'))) ?></address>
    </div>
  <?php endforeach; ?>

<?php else: ?>

  <table class="table">
    <tbody>
    <?php foreach ($this->getRenderedInfo() as $row): ?>
      <?php $isAmount = $this->getObjectData($row, 'is_amount'); ?>
      <tr>
        <th><?php echo $this->escapeHtml($this->getObjectData($row, 'label')) ?>:</th>
        <td><?php echo $this->renderRowValue($row) ?></td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>
<?php endif; ?>
