<?php $_order = $this->getOrder() ?>

<p>

  <?php if ($_order->getTracksCollection()->count()) : ?>

    <a href="<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>"
       title="<?php echo $this->__('Track all shipment(s)') ?>"
       class="btn btn-default">
      <?php echo $this->__('Track all shipments') ?>
    </a>

  <?php endif; ?>

  <a href="<?php echo $this->getPrintAllShipmentsUrl($_order) ?>"
     target="_blank"
     class="btn btn-default">
    <?php echo $this->__('Print All Shipments') ?>
  </a>

</p>

<?php foreach ($_order->getShipmentsCollection() as $_shipment): ?>

  <h2>
    <?php echo $this->__('Shipment #') . $_shipment->getIncrementId(); ?>
    <small>
      <a href="<?php echo $this->getPrintShipmentUrl($_shipment) ?>"
         target="_blank">
        <?php echo $this->__('Print Shipment') ?></a>
    </small>
  </h2>

  <?php $tracks = $_shipment->getTracksCollection(); ?>
  <?php if ($tracks->count()): ?>
    <table class="table table-bordered" id="my-tracking-table-<?php echo $_shipment->getId(); ?>">
      <tbody>
      <tr>
        <td colspan="2">
          <a href="<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_shipment) ?>"
             target="_blank"
             title="<?php echo $this->__('Track this shipment') ?>">
            <?php echo $this->__('Track this shipment') ?>
          </a>
        </td>
      </tr>
      <tr>
        <th class="label"><?php echo $this->__('Tracking Number(s):') ?></th>
        <td>&nbsp;
          <?php
          $i = 1;
          $_size = $tracks->count();
          foreach ($tracks as $track): ?>
            <?php if ($track->isCustom()): ?>
              <?php echo $this->escapeHtml($track->getNumber()) ?>
            <?php else: ?>
              <a href="<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($track) ?>">
                <?php echo $this->escapeHtml($track->getNumber()) ?>
              </a>
            <?php endif; ?>
            <?php if ($i != $_size): ?>, <?php endif; ?>
            <?php $i++;
          endforeach; ?>
        </td>
      </tr>
      </tbody>
    </table>
  <?php endif; ?>

  <h3><?php echo $this->__('Items Shipped') ?></h3>

  <table class="table table-bordered" id="my-shipment-table-<?php echo $_shipment->getId(); ?>">

    <thead>
    <tr>
      <th><?php echo $this->__('Product Name') ?></th>
      <th><?php echo $this->__('SKU') ?></th>
      <th><span class="nobr"><?php echo $this->__('Qty Shipped') ?></span></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($_shipment->getAllItems() as $_item): ?>
      <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
      <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach; ?>
    </tbody>

  </table>

  <?php echo $this->getCommentsHtml($_shipment) ?>

<?php endforeach; ?>
