<?php
/**
 * @see Mage_Catalog_Block_Seo_Sitemap_
 */
?>
<?php $_items = $this->getCollection(); ?>
<?php if ($_items->getSize()): ?>

  <ul class="list-unstyled">
    <?php foreach ($_items as $_item): ?>
      <li><a href="<?= $this->getItemUrl($_item) ?>"><?= $this->escapeHtml($_item->name) ?></a></li>
    <?php endforeach; ?>
  </ul>

<?php else: ?>

  <p class="text-info">
    <?= $this->__('There are no %s available.', $this->getItemsTitle()); ?>
  </p>

<?php endif ?>
