<?php
/**
 * @see Mage_Catalog_Block_Seo_Sitemap_
 */
?>
<?php $_items = $this->getCollection(); ?>
<?php if ($_items->getSize()): ?>

  <ul class="list-unstyled">
    <?php foreach ($_items as $_item): ?>
      <li class="level-<?= $this->getLevel($_item) ?>"
        <?= $this->getLevel($_item) ? 'style="padding-left:' . $this->getLevel($_item, 2) . '0px;"' : '' ?>>

        <a href="<?= $this->getItemUrl($_item) ?>"><?= $_item->name ?></a>

      </li>
    <?php endforeach; ?>
  </ul>

<?php else: ?>

  <p class="text-info">
    <?= $this->__('There are no %s available.', $this->getItemsTitle()); ?>
  </p>

<?php endif ?>
