<?php
// $_productCollection is set by the parent block/template
$_productCollection = $this->getProductCollection();
?>

<?php if ($_productCollection instanceof Varien_Data_Collection && $_productCollection->getSize()): ?>

  <?php $_helper = $this->helper('catalog/output'); ?>

  <div class="showcase-collection <?= $this->getMode() ?: 'grid' ?>">
    <?php foreach ($_productCollection as $_product): ?>

      <div class="showcase">

        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>

        <div class="showcase-media">
          <!-- Product image -->
          <a href="<?= $_product->getProductUrl() ?>"
             title="<?= $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
             class="product-img-link"
            >
            <img id="image-<?= $_product->getId() . '-' . $this->getNameInLayout() ?>"
                 class="product-img"
                 src="<?= $this->helper('catalog/image')
                   ->init($_product, 'small_image')
                   ->keepFrame($this->getmode() === 'grid')
                   ->resize(Mage::getStoreConfig(Mage_Catalog_Helper_Image::XML_NODE_PRODUCT_SMALL_IMAGE_WIDTH)) ?>"
                 alt="<?= $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
              >

            <div class="sk-spinner sk-spinner-rotating-plane"></div>
          </a>

          <?php
          // This provides extra blocks on which to hang some features for products in the list, e.g. configurable swatch
          // Features providing UI elements targeting this block will display directly here
          if ($this->getChild('name.after')) {
            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
            foreach ($_nameAfterChildren as $_nameAfterChildName) {
              $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
              $_nameAfterChild->setProduct($_product);
              echo $_nameAfterChild->toHtml();
            }
          }
          ?>
        </div>

        <!-- Product info -->
        <div class="showcase-detail">

          <!-- Product name -->
          <h3 class="product-name">
            <a href="<?= $_product->getProductUrl() ?>"
               title="<?= $_productNameStripped ?>">
              <?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
            </a>
          </h3>

          <!-- Product short description -->
          <?php if ($this->getMode() === 'list') : ?>
            <?php
            // TODO: Make review template type configurable by parent block
            // Product Rating
            echo $this->getReviewsSummaryHtml($_product, 'short');
            ?>

            <p class="product-short-description">
              <?= $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>

              <a href="<?= $_product->getProductUrl() ?>"
                 title="<?= $_productNameStripped ?>"
                >
                <?= $this->__('Learn More') ?>
              </a>
            </p>
          <?php endif ?>

          <!-- Price -->
          <?= $this->getPriceHtml($_product, true, '-' . $this->getNameInLayout()) ?>

          <div class="btn-group" role="group" aria-label="...">

            <!-- "Add to Cart" or "View Details" or "Out of Stock"-->
            <?php if ($_product->isSaleable()): ?>

              <?php
              if ($_product->canConfigure()):
                $href = $_product->getProductUrl();
                $title = $this->__('View Details');
                $class = "btn-view-details";
              else:
                $href = $this->getAddToCartUrl($_product);
                $title = $this->__('Add to Cart');
                $class = "btn-add-to-cart";
              endif
              ?>

              <a href="<?= $href ?>"
                 class="btn btn-primary <?= $class ?>"
                 title="<?= $title ?>"
                 role="button"
                >
                <span><?= $title ?></span>
              </a>

            <?php else: ?>

              <button type="button" class="btn btn-primary btn-out-of-stock" disabled="disabled">
                <?= $this->__('Out of Stock') ?>
              </button>

            <?php endif; ?>

            <!-- "Add to Compare" -->
            <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
              <a href="<?= $_compareUrl ?>"
                 title="<?= $this->__('Add to Compare') ?>"
                 class="btn btn-primary btn-add-to-compare"
                >
                <?= Mage::helper('vr_kiwiberry')->getSvgIcon('columns') ?>
                <span class="sr-only"><?= $this->__('Add to Compare') ?></span>
              </a>
            <?php endif; ?>

            <!-- "Add to Wishlist" -->
            <?php if ($this->helper('wishlist')->isAllow()) : ?>
              <a href="<?= $this->getAddToWishlistUrl($_product) ?>"
                 title="<?= $this->__('Add to Wishlist') ?>"
                 class="btn btn-primary btn-add-to-wishlist"
                >
                <?= Mage::helper('vr_kiwiberry')->getSvgIcon('heart') ?>
                <span class="sr-only"><?= $this->__('Add to Wishlist') ?></span>
              </a>
            <?php endif; ?>

          </div>
        </div>

      </div>

    <?php endforeach; ?>
  </div>

<?php endif; ?>
