<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 * @var $this Mage_Catalog_Block_Product_List
 */
?>

<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>

<?php if (!$_productCollection->count()): ?>

  <p class="text-info"><?php echo $this->__('There are no products matching the selection.') ?></p>

<?php else: ?>

  <div class="">

  <?php echo $this->getToolbarHtml() ?>

  <?php if ($this->getMode() != 'grid'): ?>

    <!-- Start of list mode -->

    <ul class="list-unstyled">
      <?php foreach ($_productCollection as $_product): ?>

        <li>

          <!-- Product Image -->
          <a href="<?php echo $_product->getProductUrl() ?>"
             title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
          >
            <?php $_imgSize = 300; ?>
            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                 class="img-responsive"
            >
          </a>

          <!-- Product info -->
          <div>

            <div>
              <!-- Product name -->
              <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
              <h2>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
                  <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                </a>
              </h2>

              <?php
              // Product rating
              if ($_product->getRatingSummary()):
                echo $this->getReviewsSummaryHtml($_product);
              endif;
              ?>

              <?php
              // Extra info after product name
              $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
              foreach ($_nameAfterChildren as $_nameAfterChildName):
                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                $_nameAfterChild->setProduct($_product);
                echo $_nameAfterChild->toHtml();
              endforeach;
              ?>

            </div>

            <!-- Price -->
            <?php echo $this->getPriceHtml($_product, true) ?>

            <!-- Action buttons -->
            <div>

              <?php if ($_product->isSaleable() && !$_product->canConfigure()): ?>

                <a title="<?php echo $this->__('Add to Cart') ?>"
                   class="btn btn-default"
                   href="<?php echo $this->getAddToCartUrl($_product) ?>">
                  <?php echo $this->__('Add to Cart') ?>
                </a>

              <?php elseif ($_product->isSaleable()): ?>

                <a title="<?php echo $this->__('View Details') ?>"
                   class="btn btn-default"
                   href="<?php echo $_product->getProductUrl() ?>">
                  <?php echo $this->__('View Details') ?>
                </a>

              <?php
              else: ?>

                <p class="text-info"><?php echo $this->__('Out of stock') ?></p>

              <?php endif; ?>

              <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                   class="btn btn-default"
                   title="<?php echo $this->__('Add to Wishlist') ?>">
                  <?php echo $this->__('Add to Wishlist') ?>
                </a>
              <?php endif; ?>

              <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                <a href="<?php echo $_compareUrl ?>"
                   class="btn btn-default"
                   title="<?php echo $this->__('Add to Compare') ?>">
                  <?php echo $this->__('Add to Compare') ?>
                </a>

              <?php endif; ?>

            </div>

            <!-- Product short description -->
            <div>
              <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
              <a href="<?php echo $_product->getProductUrl() ?>"
                 title="<?php echo $_productNameStripped ?>"
                 class="link-learn">
                <?php echo $this->__('Learn More') ?>
              </a>
            </div>

          </div><!-- End of product info -->

        </li>

      <?php endforeach; ?>
    </ul><!-- End of list mode -->

  <?php else: ?>

    <!-- Start of grid Mode -->

    <div class="row">

      <?php
      $normalizedColWidth = 12 / $this->getColumnCount(); // we are using a 12 grids system
      foreach ($_productCollection as $_product): ?>

        <div class="col-sm-<?php echo $normalizedColWidth ?>">

          <!-- Product image -->
          <a href="<?php echo $_product->getProductUrl() ?>"
             title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
          >

            <?php $_imgSize = 210; ?>
            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                 class="img-responsive"
            >

          </a>

          <!-- Product info -->
          <div>

            <!-- Product name -->
            <h5>
              <a href="<?php echo $_product->getProductUrl() ?>"
                 title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
              </a>
            </h5>

            <?php
            // Extra info after product name
            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
            foreach ($_nameAfterChildren as $_nameAfterChildName):

              $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
              $_nameAfterChild->setProduct($_product);
              echo $_nameAfterChild->toHtml();

            endforeach;
            ?>

            <!-- Price -->
            <?php echo $this->getPriceHtml($_product, true) ?>

            <?php
            // Product Rating
            if ($_product->getRatingSummary()):
              echo $this->getReviewsSummaryHtml($_product, 'short');
            endif;
            ?>

            <!-- Action buttons -->
            <div>
              <?php if ($_product->isSaleable() && !$_product->canConfigure()): ?>

                <a title="<?php echo $this->__('Add to Cart') ?>"
                   class="btn btn-default"
                   href="<?php echo $this->getAddToCartUrl($_product) ?>">
                  <?php echo $this->__('Add to Cart') ?>
                </a>

              <?php elseif ($_product->isSaleable()): ?>

                <a title="<?php echo $this->__('View Details') ?>"
                   class="btn btn-default"
                   href="<?php echo $_product->getProductUrl() ?>">
                  <?php echo $this->__('View Details') ?>
                </a>

              <?php
              else: ?>

                <p class="text-info"><?php echo $this->__('Out of stock') ?></p>

              <?php endif; ?>

              <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                   class="btn btn-default"
                   title="<?php echo $this->__('Add to Wishlist') ?>">
                  <?php echo $this->__('Add to Wishlist') ?>
                </a>
              <?php endif; ?>

              <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                <a href="<?php echo $_compareUrl ?>"
                   class="btn btn-default"
                   title="<?php echo $this->__('Add to Compare') ?>">
                  <?php echo $this->__('Add to Compare') ?>
                </a>

              <?php endif; ?>
            </div>

          </div><!-- End of product info -->

        </div><!-- End of column -->

      <?php endforeach ?>
    </div><!-- End of grid mode -->

  <?php endif; ?>

  <div class="toolbar-bottom">
    <?php echo $this->getToolbarHtml() ?>
  </div>

  </div>

<?php endif; ?>

<?php
//set product collection on after blocks
$_afterChildren = $this->getChild('after')->getSortedChildren();
foreach ($_afterChildren as $_afterChildName):
  $_afterChild = $this->getChild('after')->getChild($_afterChildName);
  $_afterChild->setProductCollection($_productCollection);
  ?>
  <?php echo $_afterChild->toHtml(); ?>
<?php endforeach; ?>
