<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 * @var $this Mage_Catalog_Block_Product_List
 */
?>

<?php $_productCollection = $this->getLoadedProductCollection(); ?>

<?php if (!$_productCollection->getSize()): ?>

  <p class="text-info"><?= $this->__('There are no products matching the selection.') ?></p>

<?php else: ?>

  <?php
  echo $this->getToolbarHtml();

    echo $this->getChild('product-collection')
    ->setMode($this->getMode())
    ->setProductCollection($_productCollection)
    ->toHtml();

  echo $this->getToolbarHtml()
  ?>

<?php endif; ?>

<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
  $_afterChildren = $this->getChild('after')->getSortedChildren();
  foreach ($_afterChildren as $_afterChildName) {
    $_afterChild = $this->getChild('after')->getChild($_afterChildName);
    //set product collection on after blocks
    $_afterChild->setProductCollection($_productCollection);
    echo $_afterChild->toHtml();
  }
}
?>

