<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
  <h2><?php echo $this->__('New Products') ?></h2>

  <div class="row">
    <?php foreach ($_products->getItems() as $_product): ?>

      <div class="col-sm-<?php echo 12 / $this->getColumnCount() ?>">

        <div class="thumbnail">

          <!-- Product image -->
          <a href="<?php echo $_product->getProductUrl() ?>"
             title="<?php echo $this->escapeHtml($_product->getName()) ?>">
            <img class="img-responsive"
                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300) ?>"
                 alt="<?php echo $this->escapeHtml($_product->getName()) ?>">
          </a>

          <!-- Product info -->
          <div class="caption">

            <!-- Product name -->
            <h5>
              <a href="<?php echo $_product->getProductUrl() ?>"
                 title="<?php echo $this->escapeHtml($_product->getName()) ?>">
                <?php echo $this->escapeHtml($_product->getName()) ?>
              </a>
            </h5>

            <?php
            // Product Rating
            echo $this->getReviewsSummaryHtml($_product, 'short');
            ?>

            <!-- Price -->
            <?php echo $this->getPriceHtml($_product, true, '-new') ?>

            <!-- Action buttons -->
            <div class="btn-group btn-group-justified">
              <?php if ($_product->isSaleable() && !$_product->canConfigure()): ?>

                <a href="<?php echo $this->getAddToCartUrl($_product) ?>"
                   class="btn btn-default"
                   title="<?php echo $this->__('Add to Cart') ?>">
                  <i class="fa fa-shopping-cart"></i>
                  <span class="sr-only"><?php echo $this->__('Add to Cart') ?></span>
                </a>

              <?php elseif ($_product->isSaleable()): ?>

                <a title="<?php echo $this->__('View Details') ?>"
                   class="btn btn-default"
                   href="<?php echo $_product->getProductUrl() ?>">
                  <i class="fa fa-eye"></i>
                  <span class="sr-only"><?php echo $this->__('View Details') ?></span>
                </a>

              <?php
              else: ?>

                <p class="text-info"><?php echo $this->__('Out of stock') ?></p>

              <?php endif; ?>

              <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <a href="<?php echo $this->getAddToWishlistUrl($_product) ?>"
                   class="btn btn-default"
                   title="<?php echo $this->__('Add to Wishlist') ?>"
                  >
                  <i class="fa fa-heart"></i>
                  <span class="sr-only"><?php echo $this->__('Add to Wishlist') ?></span>
                </a>
              <?php endif; ?>

              <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                <a href="<?php echo $_compareUrl ?>"
                   class="btn btn-default"
                   title="<?php echo $this->__('Add to Compare') ?>"
                  >
                  <i class="fa fa-columns"></i>
                  <span class="sr-only"><?php echo $this->__('Add to Compare') ?></span>
                </a>
              <?php endif; ?>
            </div>

          </div>

        </div>

      </div>

    <?php endforeach; ?>
  </div>
<?php endif; ?>
