<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<!-- Messages -->
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="row">

  <div class="col-sm-6">
    <!-- Product Images -->
    <?php echo $this->getChildHtml('media') ?>
  </div>

  <div class="col-sm-6">
    <!-- Product Name -->
    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>

    <!-- Price -->
    <div>
      <?php echo $this->getPriceHtml($_product); ?>
      <?php echo $this->getChildHtml('bundle_prices') ?>
      <?php echo $this->getTierPriceHtml() ?>
    </div>

    <!-- Price Alert -->
    <?php echo $this->getChildHtml('alert_urls') ?>

    <!-- Reviews -->
    <?php echo $this->getReviewsSummaryHtml($_product, 'default', false) ?>

    <!-- Availability -->
    <?php echo $this->getChildHtml('product_type_availability'); ?>

    <!-- Short Description -->
    <?php if ($_product->getShortDescription()): ?>
      <p>
        <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
      </p>
    <?php endif; ?>

    <!-- 'Back to Main Product Info' link in review page-->
    <?php echo $this->getChildHtml('other'); ?>

    <form action="<?php echo $this->getSubmitUrl($_product) ?>"
          method="post"
          id="product_addtocart_form"
          role="form"
          class="form-horizontal"
      <?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

      <!-- Hidden Stuff -->
      <?php echo $this->getBlockHtml('formkey') ?>
      <input type="hidden" name="product" value="<?php echo $_product->getId() ?>"/>
      <input type="hidden" name="related_product" id="related-products-field" value=""/>

      <!-- Product Options and Buttons Container 1 -->
      <?php if ($_product->isSaleable() && $this->hasOptions()): // Saleable and has options ?>
        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
      <?php endif; ?>

      <!-- 'Add to Cart' and some other buttons -->
      <div class="add-to-cart-wrapper">
        <?php echo $this->getChildHtml('product_type_data') ?>
        <?php echo $this->getChildHtml('extrahint') ?>

        <?php if ($_product->isSaleable() && !$this->hasOptions()): ?>
          <?php echo $this->getChildHtml('addtocart') ?>
        <?php endif; ?>

        <?php if (!$this->hasOptions()): ?>
          <?php echo $this->getChildHtml('addto') ?>
          <?php echo $this->getChildHtml('sharing') ?>
        <?php endif; ?>
      </div>

      <!-- Related Products -->
      <?php echo $this->getChildHtml('related_products') ?>

      <!-- Product Options and Buttons Container 2 -->
      <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
        <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
      <?php endif; ?>
    </form>
  </div>

</div>

<div class="product-collateral toggle-content tabs">
  <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')): ?>
    <dl id="collateral-tabs" class="collateral-tabs">
      <?php foreach ($detailedInfoGroup as $alias => $html): ?>
        <dt class="tab"><span><?php echo $this->escapeHtml($this->getChildData($alias, 'title')) ?></span></dt>
        <dd class="tab-container">
          <div class="tab-content"><?php echo $html ?></div>
        </dd>
      <?php endforeach; ?>
    </dl>
  <?php endif; ?>
</div>

<?php echo $this->getChildHtml('upsell_products') ?>
<?php echo $this->getChildHtml('product_additional_data') ?>
