<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<!-- Messages -->
<?= $this->getMessagesBlock()->toHtml() ?>

<div class="row">

  <div class="col-sm-6">
    <!-- Product Images -->
    <?= $this->getChildHtml('media') ?>
  </div>

  <div class="col-sm-6">
    <!-- Product Name -->
    <h1><?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>

    <!-- Price -->
    <div>
      <?= $this->getPriceHtml($_product); ?>
      <?= $this->getChildHtml('bundle_prices') ?>
      <?= $this->getTierPriceHtml() ?>
    </div>

    <!-- Price Alert -->
    <?= $this->getChildHtml('alert_urls') ?>

    <!-- Reviews -->
    <?= $this->getReviewsSummaryHtml($_product, 'default', false) ?>

    <!-- Availability -->
    <?= $this->getChildHtml('product_type_availability'); ?>

    <!-- Short Description -->
    <?php if ($_product->getShortDescription()): ?>
      <p>
        <?= $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
      </p>
    <?php endif; ?>

    <!-- 'Back to Main Product Info' link in review page-->
    <?= $this->getChildHtml('other'); ?>

    <form action="<?= $this->getSubmitUrl($_product) ?>"
          method="post"
          id="product_addtocart_form"
          role="form"
          class="form-horizontal"
          data-options-price="<?= $this->escapeHtml($this->getJsonConfig()) ?>"
      <?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

      <!-- Hidden Stuff -->
      <?= $this->getBlockHtml('formkey') ?>
      <input type="hidden" name="product" value="<?= $_product->getId() ?>"/>

      <!-- Product Options and Buttons Container 1 -->
      <?php if ($_product->isSaleable() && $this->hasOptions()): // Saleable and has options ?>
        <?= $this->getChildChildHtml('container1', '', true, true) ?>
      <?php endif; ?>

      <!-- 'Add to Cart' and some other buttons -->
      <div class="add-to-cart-wrapper">
        <?= $this->getChildHtml('product_type_data') ?>
        <?= $this->getChildHtml('extrahint') ?>

        <?php if ($_product->isSaleable() && !$this->hasOptions()): ?>
          <?= $this->getChildHtml('addtocart') ?>
        <?php endif; ?>

        <?php if (!$this->hasOptions()): ?>
          <?= $this->getChildHtml('addto') ?>
          <?= $this->getChildHtml('sharing') ?>
        <?php endif; ?>
      </div>

      <!-- Related Products -->
      <?= $this->getChildHtml('related_products') ?>

      <!-- Product Options and Buttons Container 2 -->
      <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
        <?= $this->getChildChildHtml('container2', '', true, true) ?>
      <?php endif; ?>
    </form>
  </div>

</div>

<!-- Tabs for detailed product info-->
<?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')): ?>
  <ul class="nav nav-tabs" role="tablist">
    <?php $i = 0;
    foreach ($detailedInfoGroup as $alias => $html): ?>
      <li <?php if (++$i === 1) echo 'class="active"' ?>>
        <a href="#<?= "tab-$alias" ?>" role="tab" data-toggle="tab">
          <?= $this->escapeHtml($this->getChildData($alias, 'title')) ?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>

  <div class="tab-content">
    <?php $i = 0;
    foreach ($detailedInfoGroup as $alias => $html): ?>
      <div id="<?= "tab-$alias" ?>"
           class="tab-pane fade<?php if (++$i === 1) echo ' in active' ?>">
        <?= $html ?>
      </div>
    <?php endforeach; ?>
  </div>
<?php endif; ?>

<?= $this->getChildHtml('upsell_products') ?>
<?= $this->getChildHtml('product_additional_data') ?>
