<?php
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper = $this->helper('catalogsearch');
?>
<form id="search_mini_form"
      class="navbar-search navbar-form"
      role="search"
      action="<?= $catalogSearchHelper->getResultUrl() ?>"
      method="get">
  <div class="form-group">
    <div class="input-group">

      <label for="search" class="sr-only"><?= $this->__('Search:') ?></label>

      <input
        id="search"
        class="form-control"
        placeholder="<?= $this->__('Search entire store here...') ?>"
        type="text"
        name="<?= $catalogSearchHelper->getQueryParamName() ?>"
        value="<?= $catalogSearchHelper->getEscapedQueryText() ?>"
        maxlength="<?= $catalogSearchHelper->getMaxQueryLength(); ?>"
        data-suggest-url="<?= $catalogSearchHelper->getSuggestUrl() ?>"
        required
        >

      <div class="input-group-btn">
        <button class="btn btn-primary" type="submit" title="<?= $this->__('Search') ?>">
          <?= Mage::helper('vr_kiwiberry')->getSvgIcon('search') ?>
          <span class="btn-search-title"><?= $this->__('Search') ?></span>
        </button>

        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <span class="caret"></span>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu dropdown-menu-right" role="menu">
          <li><a href="<?= Mage::helper('catalogsearch')->getSearchTermUrl() ?>">Popular Search Terms</a></li>
          <li><a href="<?= Mage::helper('catalogsearch')->getAdvancedSearchUrl() ?>">Advanced Search</a></li>
        </ul>
      </div>

    </div>
  </div>
  <div id="search_autocomplete" class="search-autocomplete"></div>
</form>
