<div class="page-header">
  <h1>There has been an error processing your request</h1>
</div>

<?php if ($this->showSentMsg): ?>
  <div class="alert alert-success" role="alert">
    Your message was submitted and will be responded as soon as possible. Thank you for reporting.
  </div>

<?php endif; ?>

<?php if ($this->showSendForm): ?>

  <div class="alert alert-info" role="alert">
    We are currently experiencing some technical issues. We apologize for the inconvenience and will contact you shortly
    to resolve the issue. To help us serve you please fill in the form below.
  </div>

  <?php if ($this->showErrorMsg): ?>
    <div class="alert alert-info" role="alert">
      Please fill all required fields with valid information
    </div>
  <?php endif; ?>

  <form action="<?php echo "{$this->getBaseUrl(true)}errors/report.php?id={$this->reportId}" ?>"
        method="post"
        id="form-validate"
        role="form"
    >

    <h2>Personal Information</h2>

    <div class="form-group">
      <label for="firstname" class="required"><em>*</em>First Name</label>
      <input type="text"
             name="firstname"
             id="firstname"
             value="<?php echo $this->postData['firstName'] ?>"
             title="First Name"
             class="required-entry form-control">
    </div>

    <div class="form-group">
      <label for="lastname" class="required"><em>*</em>Last Name </label>
      <input type="text"
             name="lastname"
             id="lastname"
             value="<?php echo $this->postData['lastName'] ?>"
             title="Last Name"
             class="required-entry form-control">
    </div>

    <div class="form-group">
      <label for="firstname" class="required"><em>*</em>Email Address</label>
      <input type="text"
             name="email"
             id="email_address"
             value="<?php echo $this->postData['email'] ?>"
             title="Email Address"
             class="validate-email required-entry form-control">
    </div>

    <div class="form-group">
      <label for="firstname">Telephone</label>
      <input type="text"
             name="telephone"
             id="telephone"
             value="<?php echo $this->postData['telephone'] ?>"
             title="Telephone"
             class="form-control">
    </div>

    <div class="form-group">
      <label for="firstname">Comment</label>
      <textarea name="comment" rows="3" class="form-control"><?php echo $this->postData['comment'] ?></textarea>
    </div>

    <p class="text-danger">* Required Fields</p>

    <button name="submit" class="btn btn-primary" type="submit">
      Submit
    </button>


  </form>

<?php elseif ('' == $this->reportAction): ?>

  <p><em>Exception printing is disabled by default for security reasons.</em></p>

<?php endif; ?>

<?php if ($this->reportAction == 'print'): ?>
  <h2>Technical Details:</h2>
  <pre>
    <?php echo $this->reportData[0] ?><br>
    <strong>Trace:</strong>
    <?php echo htmlspecialchars($this->reportData[1]) ?><br>
  </pre>
<?php endif; ?>

<?php if ($this->reportId && $this->reportUrl): ?>
  <p>
    Error log record number:
    <a href="<?php echo htmlspecialchars($this->reportUrl) ?>"><?php echo $this->reportId ?></a>
  </p>
<?php endif; ?>
