<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>

<tr>
<td class="product-cart-image">
  <?php if ($this->hasProductUrl()): ?>
  <a href="<?= $this->getProductUrl() ?>"
     title="<?= $this->escapeHtml($this->getProductName()) ?>">
    <?php endif; ?>

    <img src="<?= $this->getProductThumbnail()->resize(180); ?>"
         class="img-responsive"
         alt="<?= $this->escapeHtml($this->getProductName()) ?>"/>

    <?php if ($this->hasProductUrl()): ?>
  </a>
<?php endif; ?>

</td>

<td class="product-cart-info">

  <h4 class="product-name">
    <?php if ($this->hasProductUrl()): ?>
      <a href="<?= $this->getProductUrl() ?>"><?= $this->escapeHtml($this->getProductName()) ?></a>
    <?php else: ?>
      <?= $this->escapeHtml($this->getProductName()) ?>
    <?php endif; ?>
  </h4>

  <div class="product-cart-sku">
  </div>

  <!-- Product Options -->
  <?php if ($_options = $this->getOptionList()): ?>
    <dl class="dl-horizontal">

      <dt><?= $this->__('SKU'); ?></dt>
      <dd><?= $this->escapeHtml($_item->getSku()); ?></dd>

      <?php foreach ($_options as $_option) : ?>
        <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
        <dt><?= $this->escapeHtml($_option['label']) ?></dt>
        <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?= $_formatedOptionValue['value'] ?>
          <?php if (isset($_formatedOptionValue['full_view'])): ?>
            <div class="truncated_full_value">
              <dl class="item-options dl-horizontal">
                <dt><?= $this->escapeHtml($_option['label']) ?></dt>
                <dd><?= $_formatedOptionValue['full_view'] ?></dd>
              </dl>
            </div>
          <?php endif; ?>
        </dd>
      <?php endforeach; ?>
    </dl>
  <?php endif; ?>

  <?php if ($messages = $this->getMessages()): ?>
    <?php foreach ($messages as $message): ?>
      <p class="item-msg <?= $message['type'] ?>">
        * <?= $this->escapeHtml($message['text']) ?>
      </p>
    <?php endforeach; ?>
  <?php endif; ?>

  <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
  <?php if ($addInfoBlock): ?>
    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
  <?php endif; ?>

</td>

<!-- Price -->
<?php if ($canApplyMsrp): ?>

  <td class="product-cart-price"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif; ?>>
    <span class="cart-price">

      <span class="cart-msrp-unit"><?= $this->__('See price before order confirmation.'); ?></span>

      <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>

      <a id="<?= $helpLinkId ?>"
         href="#"
         title="<?= $this->__("What's this?"); ?>"
         class="js-msrp-help-link">
        <?= $this->__("What's this?"); ?>
      </a>

    </span>
  </td>

<?php else: ?>

  <!-- exclusive price starts here -->
  <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="product-cart-price"
        data-rwd-label="<?= $this->__('Price'); ?>"
        data-rwd-tax-label="<?= $this->__('Excl. Tax'); ?>">

      <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
      <span class="cart-tax-total"
            onclick="taxToggle('eunit-item-tax-details<?= $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
      <?php else: ?>
        <span class="cart-price">
      <?php endif; ?>

      <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
        <?= $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?>
      <?php else: ?>
        <?= $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
      <?php endif; ?>

      </span>

        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

          <div class="cart-tax-info" id="eunit-item-tax-details<?= $_item->getId(); ?>" style="display:none;">
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                <span class="weee"><?= $tax['title']; ?>
                  : <?= Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span>
              <?php endforeach; ?>
            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                <span class="weee"><?= $tax['title']; ?>
                  : <?= Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span>
              <?php endforeach; ?>
            <?php
            elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                <span class="weee"><?= $tax['title']; ?>
                  : <?= Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span>
              <?php endforeach; ?>
            <?php endif; ?>
          </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <div class="cart-tax-total"
                 onclick="taxToggle('eunit-item-tax-details<?= $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
              <span class="weee"><?= Mage::helper('weee')->__('Total'); ?>
                : <?= $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?></span>
            </div>
          <?php endif; ?>
        <?php endif; ?>
    </td>
  <?php endif; ?>

  <!-- inclusive price starts here -->
  <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>

    <td class="product-cart-price"
        data-rwd-label="<?= $this->__('Price'); ?>"
        data-rwd-tax-label="<?= $this->__('Incl. Tax'); ?>">
      <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
      <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
      <span class="cart-tax-total"
            onclick="taxToggle('unit-item-tax-details<?= $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
        <span class="cart-price">
            <?php endif; ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
              <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
            <?php else: ?>
              <?= $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxDisposition()) ?>
            <?php endif; ?>

            </span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

          <div class="cart-tax-info" id="unit-item-tax-details<?= $_item->getId(); ?>" style="display:none;">
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                <span class="weee"><?= $tax['title']; ?>
                  : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
              <?php endforeach; ?>
            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                <span class="weee"><?= $tax['title']; ?>
                  : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
              <?php endforeach; ?>
            <?php
            elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                <span class="weee"><?= $tax['title']; ?>
                  : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
              <?php endforeach; ?>
            <?php endif; ?>
          </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <div class="cart-tax-total"
                 onclick="taxToggle('unit-item-tax-details<?= $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
              <span class="weee"><?= Mage::helper('weee')->__('Total incl. tax'); ?>
                : <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></span>
            </div>
          <?php endif; ?>
        <?php endif; ?>
    </td>
  <?php endif; ?>

<?php endif; ?>

<td class="product-cart-actions" data-rwd-label="<?= $this->__('Qty'); ?>">
  <div class="input-group input-group-qty">
    <input type="text"
           pattern="\d*"
           name="cart[<?= $_item->getId() ?>][qty]"
           value="<?= $this->getQty() ?>"
           size="4"
           title="<?= $this->__('Qty') ?>"
           class="form-control"
           maxlength="12"/>

    <span class="input-group-btn">
      <button type="submit"
              name="update_cart_action"
              value="update_qty"
              title="<?= $this->__('Update'); ?>"
              class="btn btn-primary">
        <?= $this->__('Update'); ?>
      </button>
    </span>

  </div>
</td>

<!--Sub total starts here -->
<!-- exclusive price starts here -->
<?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
  <td class="product-cart-total" data-rwd-label="<?= $this->__('Subtotal'); ?>">
    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
    <span class="cart-tax-total"
          onclick="taxToggle('esubtotal-item-tax-details<?= $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
      <span class="cart-price">
        <?php endif; ?>

        <?php if ($canApplyMsrp): ?>
          <span class="cart-msrp-subtotal">--</span>
        <?php else: ?>
          <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <?= $this->helper('checkout')->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()); ?>
          <?php else: ?>
            <?= $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
          <?php endif; ?>
        <?php endif; ?>

        </span>
      <?php if (Mage::helper('weee')->getApplied($_item)): ?>

        <div class="cart-tax-info" id="esubtotal-item-tax-details<?= $_item->getId(); ?>" style="display:none;">
          <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
              <span class="weee"><?= $tax['title']; ?>
                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true); ?></span>
            <?php endforeach; ?>
          <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
              <span class="weee"><?= $tax['title']; ?>
                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true); ?></span>
            <?php endforeach; ?>
          <?php
          elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
              <span class="weee"><?= $tax['title']; ?>
                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true); ?></span>
            <?php endforeach; ?>
          <?php endif; ?>
        </div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
          <div class="cart-tax-total"
               onclick="taxToggle('esubtotal-item-tax-details<?= $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <span class="weee"><?= Mage::helper('weee')->__('Total'); ?>
              : <?= $this->helper('checkout')->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()); ?></span>
          </div>
        <?php endif; ?>
      <?php endif; ?>
  </td>
<?php endif; ?>

<!-- inclusive price starts here -->
<?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
  <td class="product-cart-total" data-rwd-label="<?= $this->__('Subtotal'); ?>">
    <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
    <span class="cart-tax-total"
          onclick="taxToggle('subtotal-item-tax-details<?= $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
      <span class="cart-price">
        <?php endif; ?>

        <?php if ($canApplyMsrp): ?>
          <span class="cart-msrp-subtotal">--</span>
        <?php else: ?>
          <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
          <?php else: ?>
            <?= $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxRowDisposition()) ?>
          <?php endif; ?>
        <?php endif; ?>

        </span>


      <?php if (Mage::helper('weee')->getApplied($_item)): ?>

        <div class="cart-tax-info" id="subtotal-item-tax-details<?= $_item->getId(); ?>" style="display:none;">
          <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
              <span class="weee"><?= $tax['title']; ?>
                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
            <?php endforeach; ?>
          <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
              <span class="weee"><?= $tax['title']; ?>
                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
            <?php endforeach; ?>
          <?php
          elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
              <span class="weee"><?= $tax['title']; ?>
                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
            <?php endforeach; ?>
          <?php endif; ?>
        </div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
          <div class="cart-tax-total"
               onclick="taxToggle('subtotal-item-tax-details<?= $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <span class="weee"><?= Mage::helper('weee')->__('Total incl. tax'); ?>
              : <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
          </div>
        <?php endif; ?>
      <?php endif; ?>
  </td>

<?php endif; ?>

<td>

  <?php if ($isVisibleProduct): ?>
    <a href="<?= $this->getConfigureUrl() ?>"
       title="<?= $this->__('Edit item parameters') ?>">
      <i class="fa fa-pencil"></i>
      <span class="sr-only"><?= $this->__('Edit') ?></span>
    </a>
  <?php endif ?>

  <?php if ($this->helper('wishlist')->isAllowInCart() && $isVisibleProduct) : ?>
    <a href="<?= $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>">
      <i class="fa fa-heart"></i>
      <span class="sr-only"><?= $this->__('Move to wishlist'); ?></span>
    </a>
  <?php endif ?>

  <a href="<?= $this->getDeleteUrl() ?>"
     title="<?= $this->__('Remove Item') ?>">
    <i class="fa fa-trash"></i>
    <span class="sr-only"><?= $this->__('Remove Item') ?></span>
  </a>

</td>
</tr>


