module.exports = [
  "app/noconflict.js",
  "app/common.js",
  "app/form-validation.js",
  "app/region-updater.js",

  "app/cart.js",
  "app/checkout.js",
  "app/checkout/billing.js",
  "app/checkout/login.js",
  "app/checkout/payment.js",
  "app/checkout/progress.js",
  "app/checkout/review.js",
  "app/checkout/shipping-method.js",
  "app/checkout/shipping.js",

  "app/compare.js",
  "app/configurable-swatches/configurable-media-images.js",
  "app/configurable-swatches/configurable-swatches-list.js",
  "app/configurable-swatches/swatches-product.js",
  "app/cookie-notice.js",
  "app/custom_options.js",
  "app/date-option.js",
  "app/guest-order.js",
  "app/logout.js",
  "app/mini-cart.js",
  "app/my-account.js",
  "app/nav.js",
  "app/pointer-manager.js",
  "app/poll.js",
  "app/print.js",
  "app/product-list.js",
  "app/product-media-manager.js",
  "app/product-view.js",
  "app/reorder.js"
];
