<?php /* @var $this Mage_Reports_Block_Product_Viewed */ ?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
  <div class="panel panel-default">
    <div class="panel-heading">
      <?= $this->__('Recently Viewed Products') ?>
    </div>

    <ul class="list-group">
      <?php foreach ($_products as $_item): ?>

        <li class="list-group-item">
          <div class="media">
            <a class="media-left media-middle"
               href="<?= $this->getProductUrl($_item) ?>"
               title="<?= $this->escapeHtml($_item->getName()) ?>">
              <img
                src="<?= $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50, 50)->setWatermarkSize('30x10'); ?>"
                class="img-responsive"
                alt="<?= $this->escapeHtml($_item->getName()) ?>">
            </a>

            <div class="media-body">
              <h5 class="media-heading">
                <a href="<?= $this->getProductUrl($_item) ?>">
                  <?= $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?>
                </a>
              </h5>
            </div>
          </div>
        </li>

      <?php endforeach; ?>
    </ul>

  </div>
<?php endif; ?>

