<?php
/* @var $this Mage_Captcha_Block_Captcha_Zend */
/* @var $captcha Mage_Captcha_Model_Zend */
$captcha = $this->getCaptchaModel();
?>

<div id="captcha-input-box-<?php echo $this->getFormId() ?>" class="form-group">
  <label for="captcha_<?php echo $this->getFormId() ?>">
    <em>*</em><?php echo $this->__('Please type the letters below') ?>
  </label>

  <input name="<?php echo Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE ?>[<?php echo $this->getFormId() ?>]"
         type="text"
         class="form-control required-entry"
         id="captcha_<?php echo $this->getFormId() ?>">
</div>

<div id="captcha-image-box-<?php echo $this->getFormId() ?>">

  <img id="<?php echo $this->getFormId() ?>"
       class="js-captcha-img"
       height="<?php echo $this->getImgHeight() ?>"
       src="<?php echo $captcha->getImgSrc() ?>"
       data-refresh-url="<?php echo $this->getRefreshUrl() ?>"
    >

  <a href="#<?php echo $this->getFormId() ?>"
     class="js-captcha-refresh captcha-refresh"
     title="<?php echo $this->__('Reload captcha') ?>">
    <i class="fa fa-refresh"></i>
  </a>

  <?php if ($captcha->isCaseSensitive()) : ?>
    <p class="text-info">
      <?php echo $this->__('<strong>Attention</strong>: Captcha is case sensitive.') ?>
    </p>
  <?php endif; ?>
</div>

