<?php
/* @var $this Mage_Captcha_Block_Captcha_Zend */
/* @var $captcha Mage_Captcha_Model_Zend */
$captcha = $this->getCaptchaModel();
?>

<div id="captcha-input-box-<?= $this->getFormId() ?>" class="form-group">
  <label for="captcha_<?= $this->getFormId() ?>" class="required">
    <?= $this->__('Please type the letters below') ?>

    <?php if ($captcha->isCaseSensitive()) : ?>
      <span class="text-danger">
        (<?= $this->__('Captcha is case sensitive') ?>)
      </span>
    <?php endif; ?>
  </label>

  <input name="<?= Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE ?>[<?= $this->getFormId() ?>]"
         type="text"
         class="form-control required-entry"
         autocomplete="off"
         id="captcha_<?= $this->getFormId() ?>">

  <div id="captcha-image-box-<?= $this->getFormId() ?>" class="captcha-img-box">

    <img id="<?= $this->getFormId() ?>"
         class="js-captcha-img"
         height="<?= $this->getImgHeight() ?>"
         src="<?= $captcha->getImgSrc() ?>"
         data-refresh-url="<?= $this->getRefreshUrl() ?>"
      >

    <a href="#<?= $this->getFormId() ?>"
       class="js-captcha-refresh captcha-refresh"
       title="<?= $this->__('Reload captcha') ?>">
      <i class="fa fa-refresh"></i>
    </a>
  </div>

</div>
