<h1><?php echo $this->__('Compare Products') ?></h1>

<?php $_total = $this->getItems()->count() ?>
<?php if ($_total): ?>

  <button type="button" class="js-print btn btn-default">
    <?php echo $this->__('Print This Page') ?>
  </button>

  <span class="please-wait" id="compare-list-please-wait" style="display:none;">
    <i class="fa fa-spinner fa-spin"></i>
    <?php echo $this->__('Please wait...') ?>
  </span>

  <table class="table table-striped" id="product_comparison">

    <colgroup>
      <?php $_i = 0 ?>
      <?php foreach ($this->getItems() as $_item): ?>

        <?php if ($_i++ % 10 == 0): ?>
          <col width="1"/>
        <?php endif; ?>

        <col width="<?php echo floor(100 / $_total); ?>%"/>
      <?php endforeach; ?>
    </colgroup>

    <?php if ($_total > 2): ?>
      <thead>
      <tr>
        <?php $_i = 0 ?>
        <?php foreach ($this->getItems() as $_item): ?>

          <?php if ($_i++ % 10 == 0): ?>
            <th>&nbsp;</th>
          <?php endif; ?>

          <td>
            <a class="btn btn-default js-comparison-remove"
               href="<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_item) ?>"
              >
              <?php echo $this->__('Remove This Item') ?>
            </a>
          </td>
        <?php endforeach; ?>
      </tr>
      </thead>
    <?php endif ?>

    <tbody>
    <tr>
      <?php $_i = 0 ?>
      <?php foreach ($this->getItems() as $_item): ?>

        <?php if ($_i++ % 10 == 0): ?>
          <th>&nbsp;</th>
        <?php endif; ?>

        <td>
          <a class="product-image"
             href="<?php echo $this->getProductUrl($_item) ?>"
             title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
            <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(125, 125); ?>"
                 width="125"
                 height="125"
                 alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
          </a>

          <h2 class="product-name">
            <a href="<?php echo $this->getProductUrl($_item) ?>"
               title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
              <?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?>
            </a>
          </h2>

          <?php echo $this->getReviewsSummaryHtml($_item, 'short') ?>

          <?php echo $this->getPriceHtml($_item, true, '-compare-list-top') ?>
        </td>
      <?php endforeach; ?>
    </tr>

    <tr class="product-shop-row bottom">

      <?php $_i = 0 ?>
      <?php foreach ($this->getItems() as $_item): ?>
        <?php if ($_i++ % 10 == 0): ?>
          <th>&nbsp;</th>
        <?php endif; ?>

        <td>
          <?php if ($_item->isSaleable()): ?>
            <a class="btn btn-default btn-block"
               title="<?php echo $this->__('Add to Cart') ?>"
               href="<?php echo $this->helper('catalog/product_compare')->getAddToCartUrl($_item) ?>">
              <?php echo $this->__('Add to Cart') ?>
            </a>
          <?php else: ?>
            <p class="text-info"><?php echo $this->__('Out of stock') ?></p>
          <?php endif; ?>

          <?php if ($this->helper('wishlist')->isAllow()) : ?>
            <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>"
               class="btn btn-default btn-block"
               title="<?php echo $this->__('Add to Wishlist') ?>"
              >
              <?php echo $this->__('Add to Wishlist') ?>
            </a>
          <?php endif; ?>
        </td>
      <?php endforeach; ?>

    </tr>
    </tbody>

    <tbody>
    <?php foreach ($this->getAttributes() as $_attribute): ?>
      <tr>
        <?php $_i = 0 ?>
        <?php foreach ($this->getItems() as $_item): ?>

          <?php if ($_i++ % 10 == 0): ?>
            <th class="nobr"><?php echo $_attribute->getStoreLabel() ?></th>
          <?php endif; ?>

          <td>
            <?php switch ($_attribute->getAttributeCode()) {
              case "price":
                echo $this->getPriceHtml($_item, true, '-compare-list-' . $_attribute->getCode());
                break;
              case "small_image":
                printf(
                  '<img src="%s" alt="%s" width="125" height="125" class="img-responsive">',
                  $this->helper('catalog/image')->init($_item, 'small_image')->resize(125, 125),
                  $this->escapeHtml($_item->getName())
                );
                break;
              case "date":
                echo substr($this->getProductAttributeValue($_item, $_attribute), 0, 10);
                break;
              default:
                echo $this->helper('catalog/output')->productAttribute(
                  $_item,
                  $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode());
                break;
            } ?>
          </td>
        <?php endforeach; ?>
      </tr>
    <?php endforeach; ?>
    </tbody>

    <tbody>
    <tr>
      <?php $_i = 0 ?>
      <?php foreach ($this->getItems() as $_item): ?>
        <?php if ($_i++ % 10 == 0): ?>
          <th>&nbsp;</th>
        <?php endif; ?>

        <td>
          <?php echo $this->getPriceHtml($_item, true, '-compare-list-bottom') ?>

          <?php if ($_item->isSaleable()): ?>
            <a title="<?php echo $this->__('Add to Cart') ?>"
               class="btn btn-default btn-block"
               href="<?php echo $this->helper('catalog/product_compare')->getAddToCartUrl($_item) ?>">
              <?php echo $this->__('Add to Cart') ?>
            </a>
          <?php else: ?>
            <p class="text-info"><?php echo $this->__('Out of stock') ?></p>
          <?php endif; ?>

          <?php if ($this->helper('wishlist')->isAllow()) : ?>
            <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>"
               class="btn btn-default btn-block"
               title="<?php echo $this->__('Add to Wishlist') ?>"
              >
              <?php echo $this->__('Add to Wishlist') ?>
            </a>
          <?php endif; ?>
        </td>
      <?php endforeach; ?>
    </tr>
    </tbody>
  </table>

  <button type="button"
          title="<?php echo $this->__('Close Window') ?>"
          class="btn btn-default js-close">
    <?php echo $this->__('Close Window') ?>
  </button>

<?php else: ?>

  <p class="text-info">
    <?php echo $this->__('There is no product to compare right now.') ?>
  </p>

<?php endif; ?>
