<?php /* @var $this Mage_Catalog_Block_Product_Compare_Sidebar */ ?>
<?php
$_helper = $this->helper('catalog/product_compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
?>

<div class="panel panel-default">

  <div class="panel-heading">
    <?php echo $this->__('Compare Products') ?>

    <?php if ($_helper->getItemCount() > 0): ?>
      <span class="badge"><?php echo $_helper->getItemCount() ?></span>
    <?php endif; ?>
  </div>

  <?php if ($_helper->getItemCount() > 0): ?>
    <ul class="list-group">
      <?php foreach ($_items as $_index => $_item): ?>

        <li class="list-group-item">
          <a href="<?php echo $this->getProductUrl($_item) ?>">
            <?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?>
          </a>

          <a href="<?php echo $_helper->getRemoveUrl($_item) ?>"
             title="<?php echo $this->__('Remove This Item') ?>"
             data-confirmation="<?php echo $this->__('Are you sure you would like to remove this item from the compare products?') ?>"
             class="close js-confirm">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only"><?php echo $this->__('Remove This Item') ?></span>
          </a>
        </li>

      <?php endforeach; ?>
    </ul>

    <div class="panel-footer">
      <a title="<?php echo $this->__('Compare') ?>"
         href="<?php echo $_helper->getListUrl() ?>"
         class="btn btn-primary"
         target="_blank">
        <?php echo $this->__('Compare') ?>
      </a>

      <a href="<?php echo $_helper->getClearListUrl() ?>"
         class="btn btn-danger js-confirm"
         data-confirmation="<?php echo $this->__('Are you sure you would like to remove all products from your comparison?') ?>">
        <?php echo $this->__('Clear All') ?>
      </a>
    </div>

  <?php else: ?>

    <div class="panel-body">
      <p class="text-info"><?php echo $this->__('You have no items to compare.') ?></p>
    </div>

  <?php endif; ?>
</div>
