<?php
/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
  ->setItem($item)
  ->getConfiguredOptions();
?>

<?php if ($product->isSaleable()): ?>

  <button type="button"
          title="<?= $this->__('Add to Cart') ?>"
          data-item-id="<?= $item->getId() ?>"
          data-url-add-to-cart="<?= $this->getItemAddToCartUrl($item->getId()) ?>"
          class="btn btn-default btn-cart js-add-witem-to-cart">
    <?= $this->__('Add to Cart') ?>
  </button>

<?php else: ?>

  <?php if ($product->getIsSalable()): ?>

    <p class="availability in-stock">
      <span class="label"><?= $this->helper('catalog')->__('Availability:') ?></span>
      <span class="value"><?= $this->helper('catalog')->__('In stock') ?></span>
    </p>

  <?php else: ?>

    <p class="availability out-of-stock">
      <span class="label"><?= $this->helper('catalog')->__('Availability:') ?></span>
      <span class="value"><?= $this->helper('catalog')->__('Out of stock') ?></span>
    </p>

  <?php endif; ?>

<?php endif; ?>

<?php if ($product->isVisibleInSiteVisibility()): ?>
  <a class="btn btn-default"
     href="<?= $this->getItemConfigureUrl($item) ?>"><?= $this->__('Edit') ?>
  </a>
<?php endif ?>

<?php foreach ($this->getSortedChildren() as $childName): ?>
  <?= $this->getChildHtml($childName, false); ?>
<?php endforeach; ?>
