<?php
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
?>
<a class="product-image"
   href="<?= $this->getProductUrl($item) ?>"
   title="<?= $this->escapeHtml($product->getName()) ?>">
  <img src="<?= $this->helper('catalog/image')->init($product, 'small_image')->resize(113, 113); ?>"
       alt="<?= $this->escapeHtml($product->getName()) ?>" i
       class="img-responsive"
    >
</a>
