<?php
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
?>
<h3 class="product-name">
  <a href="<?= $this->getProductUrl($item) ?>"
     title="<?= $this->escapeHtml($product->getName()) ?>">
    <?= $this->escapeHtml($product->getName()) ?>
  </a>
</h3>

<div class="wishlist-sku">
  <span><?= $this->__('SKU'); ?> <?= $this->escapeHtml($product->getSku()) ?></span>
</div>

<div>
  <?= $this->escapeHtml($this->stripTags($product->getShortDescription())); ?>
</div>

<textarea name="description[<?= $item->getWishlistItemId() ?>]"
          rows="3"
          title="<?= $this->__('Comment') ?>"
          class="form-control"
          placeholder="<?= $this->helper('wishlist')->defaultCommentString(); ?>"><?php
  echo($this->escapeHtml($item->getDescription() ? $item->getDescription() : ''))
  ?></textarea>

<?php if ($this->getSortedChildren()): ?>
  <div class="item-manage">
    <?php foreach ($this->getSortedChildren() as $childName): ?>
      <?= $this->getChildHtml($childName, false); ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
