<?php
/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
  ->setItem($item)
  ->getConfiguredOptions();
?>
<?php if ($item->canHaveQty() && $item->getProduct()->isVisibleInSiteVisibility()): ?>
  <input type="number"
         min="1"
         pattern="\d*"
         class="form-control js-qty validate-not-negative-number"
         data-item-id="<?= $item->getId() ?>"
         name="qty[<?= $item->getId() ?>]"
         value="<?= $this->getAddToCartQty($item) * 1 ?>">
<?php endif; ?>
