<h1><?php echo $this->__('RSS Feeds') ?></h1>


<?php
$_categories = $this->getRssCatalogFeeds();
$_misc = $this->getRssMiscFeeds();
?>
<?php if ($_categories || $_misc): ?>

  <div class="table-responsive">

    <?php if ($_misc): ?>
      <table class="table table-striped" id="rss-table-misc">
        <colgroup>
          <col width="80%"/>
          <col width="20%"/>
        </colgroup>
        <thead>
        <tr>
          <th colspan="2"><?php echo $this->__('Miscellaneous Feeds') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($_misc as $_feed): ?>
          <tr>
            <td><?php echo $_feed->getLabel() ?></td>
            <td><a href="<?php echo $_feed->getUrl() ?>" class="link-rss"><?php echo $this->__('Get Feed'); ?></a></td>
          </tr>
        <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>

    <?php if ($_categories && $_misc): ?>
      <br/>
    <?php endif ?>

    <?php if ($_categories): ?>
      <table class="table table-striped" id="rss-table-category">
        <colgroup>
          <col width="80%"/>
          <col width="20%"/>
        </colgroup>
        <thead>
        <tr>
          <th colspan="2"><?php echo $this->__('Category Feeds') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($_categories as $_category): ?>
          <tr>
            <td><?php echo $_category->getLabel() ?></td>
            <td><a href="<?php echo $_category->getUrl() ?>" class="link-rss"><?php echo $this->__('Get Feed'); ?></a>
            </td>
          </tr>
        <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>

  </div>

<?php else: ?>

  <p><?php echo $this->__('There are no Rss Feeds'); ?></p>

<?php endif; ?>
