<div class="page-header">
  <h1><?= $this->__('Edit Account Information') ?></h1>
</div>


<form action="<?= $this->getUrl('customer/account/editPost') ?>"
      method="post"
      autocomplete="off"
      id="form-validate-account-info"
      role="form"
      class="js-validate-form"
      enctype="multipart/form-data">

  <?= $this->getBlockHtml('formkey') ?>

  <h2><?= $this->__('Account Information') ?></h2>

  <p class="text-danger"><?= $this->__('* Required Fields') ?></p>

  <?= $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>

  <div class="form-group">
    <label for="email" class="required"><?= $this->__('Email Address') ?></label>
    <input type="email"
           autocapitalize="off"
           autocorrect="off"
           spellcheck="false"
           name="email"
           id="email"
           value="<?= $this->escapeHtml($this->getCustomer()->getEmail()) ?>"
           title="<?= $this->__('Email Address') ?>"
           class="form-control required-entry validate-email"/>
  </div>

  <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
  <?php if ($_dob->isEnabled()): ?>
    <?= $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?>
  <?php endif ?>

  <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
  <?php if ($_taxvat->isEnabled()): ?>
    <?= $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?>
  <?php endif ?>

  <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
  <?php if ($_gender->isEnabled()): ?>
    <?= $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?>
  <?php endif ?>

  <div class="checkbox">
    <label>
      <input type="checkbox"
             name="change_password"
             id="change_password"
             value="1"
             title="<?= $this->__('Change Password') ?>"
        <?php if ($this->getCustomer()->getChangePassword() == 1): ?> checked="checked"<?php endif; ?>
        >
      <?= $this->__('Change Password') ?>
    </label>
  </div>

  <div id="form-field-change-password" style="display:none">
    <h2><?= $this->__('Change Password') ?></h2>

    <div class="form-group"
         <?php if (!$this->getCustomer()->getChangePassword()): ?>style="display:none;"<?php endif ?>
      >
      <label for="current_password" class="required">
        <?= $this->__('Current Password') ?>
      </label>

      <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
      <input type="text" class="form-control hidden" name="dummy" id="dummy">

      <input type="password"
             title="<?= $this->__('Current Password') ?>"
             class="form-control<?php if ($this->getCustomer()->getChangePassword()): ?> required-entry<?php endif ?>"
             name="current_password"
             id="current_password">
    </div>

    <div class="form-group">
      <label for="password" class="required">
        <?= $this->__('New Password') ?>
      </label>

      <input type="password"
             title="<?= $this->__('New Password') ?>"
             class="form-control validate-password"
             name="password<?php if ($this->getCustomer()->getChangePassword()): ?> required-entry<?php endif ?>"
             id="password">
    </div>

    <div class="form-group">
      <label for="confirmation" class="required">
        <?= $this->__('Confirm New Password') ?>
      </label>

      <input type="password"
             title="<?= $this->__('Confirm New Password') ?>"
             class="form-control validate-cpassword<?php if ($this->getCustomer()->getChangePassword()): ?> required-entry<?php endif ?>"
             name="confirmation"
             id="confirmation">
    </div>
  </div>

  <a class="btn btn-default" href="<?= $this->escapeUrl($this->getBackUrl()) ?>">
    <?= $this->__('Back') ?>
  </a>

  <button type="submit" title="<?= $this->__('Save') ?>" class="btn btn-default">
    <?= $this->__('Save') ?>
  </button>

</form>
