<div class="row-narrow-block">
  <div class="col-narrow-block">

    <div class="page-header"><h1><?= $this->__('Forgot Your Password?') ?></h1></div>

    <form action="<?= $this->getUrl('*/*/forgotpasswordpost') ?>"
          method="post"
          id="form-validate-forgot-password"
          role="form">

      <h2><?= $this->__('Retrieve your password here') ?></h2>

      <p class="text-info">
        <?= $this->__('Please enter your email address below. You will receive a link to reset your password.') ?>
      </p>

      <p class="text-danger"><?= $this->__('* Required Fields') ?></p>

      <div class="form-group">
        <label for="email_address" class="required"><?= $this->__('Email Address') ?></label>
        <input type="email"
               autocapitalize="off"
               autocorrect="off"
               spellcheck="false"
               name="email"
               alt="email"
               id="email_address"
               class="form-control required-entry validate-email"
               value="<?= $this->escapeHtml($this->getEmailValue()) ?>"
               required
          >
      </div>

      <?= $this->getChildHtml('form.additional.info'); ?>


      <a href="<?= $this->helper('customer')->getLoginUrl() ?>" class="btn btn-default">
        <?= Mage::helper('vr_kiwiberry')->getSvgIcon('chevron-left') ?>
        <?= $this->__('Back to Login') ?>
      </a>

      <button type="submit" title="<?= $this->__('Submit') ?>" class="btn btn-primary">
        <?= $this->__('Submit') ?>
      </button>

    </form>

  </div>
</div>
