<h1><?php echo $this->__('Forgot Your Password?') ?></h1>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>"
      method="post"
      id="form-validate-forgot-password"
      role="form">

  <h2><?php echo $this->__('Retrieve your password here') ?></h2>

  <p class="text-info">
    <?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?>
  </p>

  <p class="text-danger"><?php echo $this->__('* Required Fields') ?></p>

  <div class="form-group">
    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
    <input type="email"
           autocapitalize="off"
           autocorrect="off"
           spellcheck="false"
           name="email"
           alt="email"
           id="email_address"
           class="form-control required-entry validate-email"
           value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>">
  </div>

  <?php echo $this->getChildHtml('form.additional.info'); ?>


  <a href="<?php echo $this->helper('customer')->getLoginUrl() ?>" class="btn btn-default">
    <i class="fa fa-angle-double-left"></i>
    <?php echo $this->__('Back to Login') ?>
  </a>

  <button type="submit" title="<?php echo $this->__('Submit') ?>" class="btn btn-default">
    <?php echo $this->__('Submit') ?>
  </button>

</form>
