<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="page-header">
  <h1><?php echo $this->__('Newsletter Subscription') ?></h1>
</div>

<?php echo $this->getChildHtml('form_before') ?>

<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate-newsletter" role="form">

  <?php echo $this->getBlockHtml('formkey') ?>

  <div class="form-group">
    <label for="subscription">
      <input type="checkbox"
             name="is_subscribed"
             id="subscription"
             value="1"
             title="<?php echo $this->__('General Subscription') ?>"
             <?php if ($this->getIsSubscribed()): ?>checked="checked"<?php endif; ?>
        >
      <?php echo $this->__('General Subscription') ?>
    </label>
  </div>

  <?php /* Extensions placeholder */ ?>
  <?php echo $this->getChildHtml('customer.form.newsletter.extra') ?>

  <div>
    <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="btn btn-default">
      <i class="fa fa-angle-double-left"></i>
      <?php echo $this->__('Back') ?>
    </a>

    <button type="submit" title="<?php echo $this->__('Save') ?>" class="btn btn-default">
      <i class="fa fa-floppy-o"></i>
      <?php echo $this->__('Save') ?>
    </button>
  </div>
</form>

<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.newsletter.extra2') ?>
