<div class="row-narrow-block">
  <div class="col-narrow-block">

    <div class="page-header"><h1><?= $this->__('Reset a Password'); ?></h1></div>

    <form action="<?= $this->getUrl('*/*/resetpasswordpost', array(
      '_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>"
          method="post"
          id="form-validate-reset-password"
          role="form">

      <p class="text-danger"><?= $this->__('* Required Fields'); ?></p>

      <div class="form-group">
        <label for="password" class="required"><?= $this->__('New Password'); ?></label>
        <input type="password" class="form-control required-entry validate-password" name="password" id="password">
      </div>

      <div class="form-group">
        <label for="confirmation" class="required"><?= $this->__('Confirm New Password'); ?></label>
        <input type="password"
               class="form-control required-entry validate-cpassword"
               name="confirmation"
               id="confirmation">
      </div>

      <button type="submit" title="<?= $this->__('Reset a Password'); ?>" class="btn btn-primary">
        <?= $this->__('Reset a Password'); ?>
      </button>

    </form>

  </div>
</div>
