<h1><?= $this->__('Reset a Password'); ?></h1>

<?= $this->getMessagesBlock()->toHtml(); ?>

<form action="<?= $this->getUrl('*/*/resetpasswordpost', array(
  '_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>"
      method="post"
      id="form-validate-reset-password"
      role="form">

  <p class="text-danger"><?= $this->__('* Required Fields'); ?></p>

  <div class="form-group">
    <label for="password" class="required"><em>*</em><?= $this->__('New Password'); ?></label>
    <input type="password" class="form-control required-entry validate-password" name="password" id="password">
  </div>

  <div class="form-group">
    <label for="confirmation" class="required"><em>*</em><?= $this->__('Confirm New Password'); ?></label>
    <input type="password"
           class="form-control required-entry validate-cpassword"
           name="confirmation"
           id="confirmation">
  </div>

  <button type="submit" title="<?= $this->__('Reset a Password'); ?>" class="btn btn-default">
    <?= $this->__('Reset a Password'); ?>
  </button>

</form>
