<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */

$_helper = $this->helper('catalog/output');
$_category = $this->getCurrentCategory();
?>

<div class="page-header">
  <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>

  <?php if ($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
    <a href="<?php echo $this->getRssLink() ?>" class="link-category-rss">
      <?php echo Mage::helper('vr_kiwiberry')->getSvgIcon('rss') ?>
      <?php echo $this->__('Subscribe to RSS Feed') ?>
    </a>
  <?php endif; ?>
</div>

<?php
if ($_imgUrl = $_category->getImageUrl()) {

  $_imgHtml = '<img class="category-image" src="' . $_imgUrl
    . '" alt="' . $this->escapeHtml($_category->getName())
    . '" title="' . $this->escapeHtml($_category->getName())
    . '" >';

  echo $_helper->categoryAttribute($_category, $_imgHtml, 'image');
}
?>

<?php if ($_description = $this->getCurrentCategory()->getDescription()): ?>
  <div class="category-description">
    <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
  </div>
<?php endif; ?>

<?php if ($this->isContentMode()): ?>

  <?php echo $this->getCmsBlockHtml() ?>

<?php elseif ($this->isMixedMode()): ?>

  <?php echo $this->getCmsBlockHtml() ?>
  <?php echo $this->getProductListHtml() ?>

<?php else: ?>

  <?php echo $this->getProductListHtml() ?>

<?php endif; ?>
