<?php
/** @var Mage_Checkout_Block_Onepage_Billing $this */
?>
<form id="co-billing-form"
      action=""
      data-address-url="<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/"
      data-save-url="<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>"
      data-regions="<?php echo $this->escapeHtml($this->helper('directory')->getRegionJsonByStore()) ?>"
  >

<p class="text-danger"><?php echo $this->__('* Required Fields') ?></p>

<?php if ($this->customerHasAddresses()): ?>
  <div class="form-group">
    <label for="billing-address-select">
      <?php echo $this->__('Select a billing address from your address book or enter a new address.') ?>
    </label>
    <?php echo $this->getAddressesHtmlSelect('billing') ?>
  </div>
<?php endif; ?>

<div id="billing-new-address-form" <?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>

<input type="hidden"
       name="billing[address_id]"
       value="<?php echo $this->getAddress()->getId() ?>"
       id="billing:address_id">

<?php
echo $this->getLayout()->createBlock('customer/widget_name')
  ->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())
  ->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())
  ->setFieldIdFormat('billing:%s')
  ->setFieldNameFormat('billing[%s]')
  ->toHtml()
?>

<div class="form-group">
  <label for="billing:company"><?php echo $this->__('Company') ?></label>
  <input type="text"
         id="billing:company"
         name="billing[company]"
         value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
         title="<?php echo $this->__('Company') ?>"
         class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>">
</div>

<?php if (!$this->isCustomerLoggedIn()): ?>
  <div class="form-group">
    <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
    <input type="email"
           autocapitalize="off"
           autocorrect="off"
           spellcheck="false"
           name="billing[email]"
           id="billing:email"
           value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>"
           title="<?php echo $this->__('Email Address') ?>"
           class="form-control validate-email required-entry">
  </div>
<?php endif; ?>

<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>

<div class="form-group">
  <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
  <input type="text"
         title="<?php echo $this->__('Street Address') ?>"
         name="billing[street][]"
         id="billing:street1"
         value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
         class="form-control <?php echo $_streetValidationClass ?>">
</div>

<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>

<?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
  <div class="form-group">
    <label for="billing:street<?php echo $_i ?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
    <input type="text"
           title="<?php echo $this->__('Street Address %s', $_i) ?>"
           name="billing[street][]"
           id="billing:street<?php echo $_i ?>"
           value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
           class="form-control <?php echo $_streetValidationClass ?>">
  </div>
<?php endfor; ?>

<?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
  <div class="form-group">
    <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
    <input type="text"
           id="billing:vat_id"
           name="billing[vat_id]"
           value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>"
           title="<?php echo $this->__('VAT Number') ?>"
           class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>">
  </div>
<?php endif; ?>

<div class="form-group">
  <label for="billing:city" class="required">
    <em>*</em>
    <?php echo $this->__('City') ?>
  </label>
  <input type="text"
         title="<?php echo $this->__('City') ?>"
         name="billing[city]"
         value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
         class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
         id="billing:city">
</div>

<div class="form-group">
  <label for="billing:region_id" class="required">
    <em>*</em>
    <?php echo $this->__('State/Province') ?>
  </label>

  <select id="billing:region_id"
          name="billing[region_id]"
          title="<?php echo $this->__('State/Province') ?>"
          class="form-control validate-select"
          defaultValue="<?php echo $this->getAddress()->getRegionId() ?>"
          style="display:none;">
    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
  </select>

  <input type="text"
         id="billing:region"
         name="billing[region]"
         value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
         title="<?php echo $this->__('State/Province') ?>"
         class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
         style="display:none;">
</div>


<div class="form-group">
  <label for="billing:postcode" class="required">
    <em>*</em>
    <?php echo $this->__('Zip/Postal Code') ?>
  </label>
  <input type="text"
         title="<?php echo $this->__('Zip/Postal Code') ?>"
         name="billing[postcode]"
         id="billing:postcode"
         value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
         class="form-control validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>">
</div>

<div class="form-group">
  <label for="billing:country_id" class="required">
    <em>*</em>
    <?php echo $this->__('Country') ?>
  </label>
  <?php echo $this->getCountryHtmlSelect('billing') ?>
</div>

<div class="form-group">
  <label for="billing:telephone" class="required">
    <em>*</em>
    <?php echo $this->__('Telephone') ?>
  </label>
  <input type="tel"
         name="billing[telephone]"
         value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
         title="<?php echo $this->__('Telephone') ?>"
         class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>"
         id="billing:telephone">
</div>

<div class="form-group">
  <label for="billing:fax"><?php echo $this->__('Fax') ?></label>
  <input type="tel"
         name="billing[fax]"
         value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>"
         title="<?php echo $this->__('Fax') ?>"
         class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>"
         id="billing:fax">
</div>

<?php if (!$this->isCustomerLoggedIn()): ?>

  <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
  <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
  <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>

    <?php if ($_dob->isEnabled()): ?>
      <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())
        ->setFieldIdFormat('billing:%s')
        ->setFieldNameFormat('billing[%s]')
        ->toHtml() ?>
    <?php endif; ?>

    <?php if ($_gender->isEnabled()): ?>
      <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())
        ->setFieldIdFormat('billing:%s')
        ->setFieldNameFormat('billing[%s]')->toHtml() ?>
    <?php endif ?>

  <?php endif ?>

  <?php if ($this->isTaxvatEnabled()): ?>
    <?php echo $this->getTaxvatHtml() ?>
  <?php endif; ?>

  <div id="register-customer-password">

    <div class="form-group">
      <label for="billing:customer_password" class="required">
        <em>*</em>
        <?php echo $this->__('Password') ?>
      </label>
      <input type="password"
             name="billing[customer_password]"
             id="billing:customer_password"
             title="<?php echo $this->__('Password') ?>"
             class=form-control required-entry validate-password"/>
    </div>

    <div class="form-group">
      <label for="billing:confirm_password" class="required">
        <em>*</em>
        <?php echo $this->__('Confirm Password') ?>
      </label>
      <input type="password"
             name="billing[confirm_password]"
             title="<?php echo $this->__('Confirm Password') ?>"
             id="billing:confirm_password"
             class="form-control required-entry validate-cpassword"/>
    </div>

  </div>

  <?php echo $this->getChildHtml('persistent.remember.me'); ?>

<?php endif; ?>

<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>


  <div class="checkbox">
    <label for="billing:save_in_address_book">
      <input type="checkbox"
             name="billing[save_in_address_book]"
             value="1"
             title="<?php echo $this->__('Save in address book') ?>"
             id="billing:save_in_address_book"
        <?php if ($this->getAddress()->getSaveInAddressBook()): ?> checked="checked"<?php endif; ?>
        >
      <?php echo $this->__('Save in address book') ?>
    </label>
  </div>

<?php else: ?>

  <input type="hidden" name="billing[save_in_address_book]" value="1"/>

<?php endif; ?>

<?php echo $this->getChildHtml('form.additional.info'); ?>

</div>

<?php if ($this->canShip()): ?>
  <div class="radio">
    <label for="billing:use_for_shipping_yes">
      <input type="radio"
             name="billing[use_for_shipping]"
             id="billing:use_for_shipping_yes"
             value="1"
             <?php if ($this->isUseBillingAddressForShipping()) { ?>checked="checked"<?php } ?>
             title="<?php echo $this->__('Ship to this address') ?>"
        >
      <?php echo $this->__('Ship to this address') ?>
    </label>
  </div>

  <div class="radio">
    <label for="billing:use_for_shipping_no">
      <input type="radio"
             name="billing[use_for_shipping]"
             id="billing:use_for_shipping_no"
             value="0"<?php if (!$this->isUseBillingAddressForShipping()) { ?> checked="checked"<?php } ?>
             title="<?php echo $this->__('Ship to different address') ?>"
        >
      <?php echo $this->__('Ship to different address') ?>
    </label>
  </div>
<?php endif; ?>

<?php if (!$this->canShip()): ?>
  <input type="hidden" name="billing[use_for_shipping]" value="1"/>
<?php endif; ?>

<div class="buttons-set" id="billing-buttons-container">
  <button type="button" title="<?php echo $this->__('Continue') ?>" class="btn btn-primary" onclick="billing.save()">
    <?php echo $this->__('Continue') ?>
  </button>

  <span class="please-wait" id="billing-please-wait" style="display:none;">
    <?php echo $this->__('Loading next step...') ?>
  </span>
</div>

</form>
