<?php
/**
 * Customer onepage checkout login form template
 *
 * @see app/design/frontend/base/default/template/checkout/onepage/login.phtml
 * @var $this Mage_Checkout_Block_Onepage_Login
 */
?>

<?= $this->getChildHtml('login_before') ?>

<div class="row<?php
if (!$this->helper('customer')->isRegistrationAllowed() && !$this->getQuote()->isAllowedGuestCheckout())
  echo ' login-only' ?>">
  <div class="col-sm-6">

    <h3>
      <?php if ($this->getQuote()->isAllowedGuestCheckout() && $this->helper('customer')->isRegistrationAllowed()): ?>
        <?= $this->__('Checkout as a Guest or Register') ?>
      <?php elseif ($this->getQuote()->isAllowedGuestCheckout() && !$this->helper('customer')->isRegistrationAllowed()): ?>
        <?= $this->__('Checkout as a Guest') ?>
      <?php
      else: ?>
        <?= $this->__('Register to Create an Account') ?>
      <?php endif; ?>
    </h3>

    <?php if (!$this->getQuote()->isAllowedGuestCheckout() && $this->helper('customer')->isRegistrationAllowed()): ?>
      <p><?= $this->__('Register and save time!') ?></strong><br/>
        <?= $this->__('Register with us for future convenience:') ?></p>
      <ul>
        <li><?= $this->__('Fast and easy check out') ?></li>
        <li><?= $this->__('Easy access to your order history and status') ?></li>
      </ul>
    <?php elseif ($this->getQuote()->isAllowedGuestCheckout() && $this->helper('customer')->isRegistrationAllowed()): ?>
      <p><?= $this->__('Register with us for future convenience:') ?></p>
    <?php endif ?>

    <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>

      <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
        <div class="radio">
          <label for="login:guest">
            <input type="radio"
                   name="checkout_method"
                   id="login:guest"
                   value="guest"

              <?php if ($this->getQuote()->getCheckoutMethod() != Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER): ?>
                checked="checked"
              <?php endif; ?>
                   class="radio">
            <?= $this->__('Checkout as Guest') ?>
          </label>
        </div>
      <?php endif; ?>

      <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
        <div class="radio">
          <label for="login:register">
            <input type="radio"
                   name="checkout_method"
                   id="login:register"
                   value="register"
              <?php if ($this->getQuote()->getCheckoutMethod() == Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER
                || !$this->getQuote()->isAllowedGuestCheckout()
              ): ?>
                checked="checked"
              <?php endif ?>

              <?php
              $registerParam = $this->getRequest()->getParam('register');
              if ($registerParam || $registerParam === '') :
                ?>
                data-force-register="true"
              <?php endif ?>

                   class="radio">
            <?= $this->__('Register and Checkout') ?>
          </label>
        </div>
      <?php endif; ?>

    <?php else: ?>

      <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked">

    <?php endif; ?>


    <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>

      <button id="onepage-guest-register-button" type="button" class="btn btn-primary">
        <?= $this->__('Continue') ?>
      </button>

    <?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>

      <a id="onepage-guest-register-button-2"
         class="btn btn-primary"
         href="<?= $this->helper('checkout/url')->getRegistrationUrl(); ?>">
        <?= $this->__('Register') ?>
      </a>

    <?php
    else: ?>

      <form action="<?= $this->getUrl('persistent/index/saveMethod'); ?>">
        <button id="onepage-guest-register-button-3" type="submit" class="btn btn-primary">
          <?= $this->__('Register') ?>
        </button>
      </form>

    <?php endif; ?>

  </div>
  <div class="col-sm-6">

    <h3><?= $this->__('Returning Customers') ?></h3>

    <?= $this->getMessagesBlock()->toHtml() ?>

    <form id="login-form" action="<?= $this->getPostAction() ?>" method="post" role="form">

      <p class="description"><?= $this->__('Sign in to speed up your checkout process') ?></p>

      <p class="required"><?= $this->__('* Required Fields') ?></p>

      <div class="form-group">
        <label for="login-email"><em class="text-danger">*</em><?= $this->__('Email Address') ?></label>
        <input type="email"
               autocapitalize="off"
               autocorrect="off"
               spellcheck="false"
               class="form-control required-entry validate-email"
               id="login-email"
               name="login[username]"
               placeholder="<?= $this->__('Email Address') ?>"
               value="<?= $this->escapeHtml($this->getUsername()) ?>">
      </div>

      <div class="form-group">
        <label for="login-password"><em class="text-danger">*</em><?= $this->__('Password') ?></label>
        <input type="password"
               class="form-control validate-password required-entry"
               id="login-password"
               placeholder="<?= $this->__('Password') ?>"
               name="login[password]">
      </div>

      <a href="<?= $this->getUrl('customer/account/forgotpassword') ?>">
        <?= $this->__('Forgot your password?') ?>
      </a>

      <?= $this->getChildHtml('form.additional.info'); ?>
      <?= $this->getChildHtml('persistent.remember.me'); ?>

      <?= $this->getBlockHtml('formkey'); ?>
      <input name="context" type="hidden" value="checkout">

    </form>

    <button id="btn-one-page-login" type="submit" class="btn btn-primary">
      <?= $this->__('Login') ?>
    </button>

  </div>
</div>
