<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */

$_dimHelper = Mage::helper('configurableswatches/swatchdimensions');
$_swatchInnerWidth = $_dimHelper->getInnerWidth(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
$_swatchInnerHeight = $_dimHelper->getInnerHeight(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
?>

<div class="list-group">
  <?php foreach ($this->getItems() as $_item): ?>
    <?php
    $_label = $_item->getLabel();
    $_swatchUrl = Mage::helper('configurableswatches/productimg')->getGlobalSwatchUrl($_item, $_label, $_swatchInnerWidth, $_swatchInnerHeight);
    ?>
    <a class="list-group-item<?php if ($_item->getCount() <= 0): echo ' disabled'; endif ?>"
       href="<?= $this->urlEscape($_item->getUrl()) ?>">

      <?php if (!empty($_swatchUrl)): ?>
        <img src="<?= $_swatchUrl; ?>"
             alt="<?= $_label; ?>"
             title="<?= $_label ?>"
             width="<?= $_swatchInnerWidth ?>"
             height="<?= $_swatchInnerHeight ?>"/>
      <?php else: ?>
        <?= $_label; ?>
      <?php endif; ?>

      <?php if ($this->shouldDisplayProductCount()): ?>
        <span class="badge"><?= $_item->getCount() ?></span>
      <?php endif; ?>

    </a>
  <?php endforeach ?>
</div>
