

<div class="page-header">
  <h1><?= $this->__('My Product Reviews') ?></h1>
</div>

<?php if ($this->getCollection() && $this->count()): ?>

  <?= $this->getToolbarHtml() ?>

  <table class="table table-hover table-bordered" id="my-reviews-table">
    <thead>
    <tr>
      <th>Date</th>
      <th>Product</th>
      <th>Rating</th>
      <th>Comment</th>
      <th>&nbsp</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($this->getCollection() as $_review): ?>

      <tr>
        <td><span class="nobr"><?= $this->dateFormat($_review->getReviewCreatedAt()); ?></span></td>
        <td>
          <a href="<?= $this->getProductLink() ?>id/<?= $_review->getEntityPkValue() ?>">
            <?= $this->escapeHtml($_review->getName()) ?>
          </a>
        </td>
        <td>
          <?php if ($_review->getSum()): ?>
            <?= $this->getChild('rating')->setPercent($_review->getSum() / $_review->getCount())->toHtml() ?>
          <?php endif; ?>
        </td>
        <td><?= $this->helper('review')->getDetailHtml($_review->getDetail()) ?></td>
        <td>
          <a href="<?= $this->getReviewLink() ?>id/<?= $_review->getReviewId() ?>" class="nobr">
            <?= $this->__('View Details') ?>
          </a>
        </td>
      </tr>

    <?php endforeach; ?>
    </tbody>
  </table>

  <?= $this->getToolbarHtml() ?>

<?php else: ?>

  <p class="text-info"><?= $this->__('You have submitted no reviews.') ?></p>

<?php endif; ?>

<a href="<?= $this->escapeUrl($this->getBackUrl()) ?>" class="btn btn-default">
  <i class="fa fa-angle-double-left"></i>
  <?= $this->__('Back') ?>
</a>
