<?php if ($this->getCollection() && $this->count()): ?>
  <div class="panel panel-default">

    <div class="panel-heading">
      <h2 class="panel-title"><?php echo $this->__('My Recent Reviews') ?></h2>
      <a href="<?php echo $this->getAllReviewsUrl() ?>"><?php echo $this->__('View All Reviews') ?></a>
    </div>

    <div id="my_recent_reviews" class="list-group">
      <?php foreach ($this->getCollection() as $_review): ?>

        <a class="list-group-item" href="<?php echo $this->getReviewUrl($_review->getReviewId()) ?>">
          <h3><?php echo $this->escapeHtml($_review->getName()) ?></h3>

          <?php if ($_review->getSum()): ?>
            <div class="ratings">
              <strong><?php echo $this->__('Rating:') ?></strong>
              <?php
              $rating = $_review->getSum() / $_review->getCount() / 20;
              $i = 0;
              for ($i = 0; $i < 5; $i++) {
                if ($i + 1 <= $rating) {
                  echo '<i class="fa fa-star"></i>';
                } elseif ($i + 0.5 <= $rating) {
                  echo '<i class="fa fa-star-half-o"></i>';
                } else {
                  echo '<i class="fa fa-star-o"></i>';
                }
              }
              ?>
            </div>
          <?php endif; ?>
        </a>

      <?php endforeach; ?>
    </div>

  </div>
<?php endif; ?>
