<?php if ($this->getCollection() && $this->count()): ?>
  <div class="panel panel-default">

    <div class="panel-heading">
      <h2 class="panel-title"><?php echo $this->__('My Recent Reviews') ?></h2>
      <a href="<?php echo $this->getAllReviewsUrl() ?>"><?php echo $this->__('View All Reviews') ?></a>
    </div>

    <div id="my_recent_reviews" class="list-group">
      <?php foreach ($this->getCollection() as $_review): ?>

        <a class="list-group-item" href="<?php echo $this->getReviewUrl($_review->getReviewId()) ?>">
          <h3><?php echo $this->escapeHtml($_review->getName()) ?></h3>

          <?php if ($_review->getSum()): ?>
            <div class="ratings">
              <strong><?php echo $this->__('Rating:') ?></strong>
              <?php echo $this->getChild('rating')->setPercent($_review->getSum() / $_review->getCount())->toHtml() ?>
            </div>
          <?php endif; ?>
        </a>

      <?php endforeach; ?>
    </div>

  </div>
<?php endif; ?>
