<?php if ($this->getCollection() && $this->count()): ?>
    <div class="panel panel-primary">

    <div class="panel-heading">
      <h2 class="panel-title"><?= $this->__('My Recent Reviews') ?></h2>
      <a href="<?= $this->getAllReviewsUrl() ?>"><?= $this->__('View All Reviews') ?></a>
    </div>

    <div id="my_recent_reviews" class="list-group">
      <?php foreach ($this->getCollection() as $_review): ?>

        <a class="list-group-item" href="<?= $this->getReviewUrl($_review->getReviewId()) ?>">
          <h3><?= $this->escapeHtml($_review->getName()) ?></h3>

          <?php if ($_review->getSum()): ?>
            <div class="ratings">
              <strong><?= $this->__('Rating:') ?></strong>
              <?= $this->getChild('rating')->setPercent($_review->getSum() / $_review->getCount())->toHtml() ?>
            </div>
          <?php endif; ?>
        </a>

      <?php endforeach; ?>
    </div>

  </div>
<?php endif; ?>
