<div class="dashboard">

  <div class="page-header">
    <h1><?= $this->__('My Dashboard') ?></h1>
  </div>


    <?= $this->getChildHtml('hello') ?>
  <?= $this->getChildHtml('top') ?>

  <h2><?= $this->__('Account Information') ?></h2>
  <?php /* Extensions placeholder */ ?>
  <?= $this->getChildHtml('customer.account.dashboard.extra') ?>
  <?= $this->getChildHtml('info') ?>

  <?= $this->getChildHtml('address') ?>
  <?= $this->getChildHtml('info1') ?>
  <?= $this->getChildHtml('info2') ?>

</div>
