<div class="panel panel-primary">

  <div class="panel-heading">
    <?= $this->__('My Account'); ?>
  </div>

  <ul class="list-group">
    <?php foreach ($this->getLinks() as $_link): ?>

      <li class="list-group-item">
        <a href="<?= $_link->getUrl() ?>">
          <?php if ($this->isActive($_link)): ?>
            <strong><?= $_link->getLabel() ?></strong>
          <?php else: ?>
            <?= $_link->getLabel() ?>
          <?php endif; ?>
        </a>
      </li>

    <?php endforeach; ?>
  </ul>

</div>
