<div class="row">
  <div class="col-sm-4">
    <a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true) . 'home-decor.html' ?>">
      <img class="img-responsive"
           src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/homepage-three-column-promo-01B.png' ?>"
           alt="Physical &amp; Virtual Gift Cards">
    </a>
  </div>
  <div class="col-sm-4">
    <a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true) . 'vip.html' ?>">
      <img class="img-responsive"
           src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/homepage-three-column-promo-02.png' ?>"
           alt="Shop Private Sales - Members Only">
    </a>
  </div>
  <div class="col-sm-4">
    <a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true) . 'bags-luggage.html' ?>">
      <img class="img-responsive"
           src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/homepage-three-column-promo-03.png' ?>"
           alt="Travel Gear for Every Occasion">
    </a>
  </div>
</div>
