<?php
/**
 * One page checkout payment methods
 *
 * @var $this Mage_Checkout_Block_Onepage_Payment_Methods
 */
$methods = $this->getMethods();
?>

<?php if (empty($methods)): ?>

  <p class="text-info"><?= $this->__('No Payment Methods') ?></p>

<?php else: ?>

  <?php foreach ($methods as $_method): ?>
    <?php $_code = $_method->getCode() ?>

    <div class="radio">
      <label for="p_method_<?= $_code ?>">
        <input id="p_method_<?= $_code ?>"
               value="<?= $_code ?>"
               type="radio"
               name="payment[method]"
               title="<?= $this->escapeHtml($_method->getTitle()) ?>"
               <?php if ($this->getSelectedMethodCode() == $_code): ?>checked="checked"<?php endif ?>
               class="radio js-payment-method">
        <?= $this->escapeHtml($this->getMethodTitle($_method)) ?>
        <?= $this->getMethodLabelAfterHtml($_method) ?>
      </label>
    </div>

    <?php if ($html = $this->getPaymentMethodFormHtml($_method)) echo $html ?>

  <?php endforeach ?>

<?php endif ?>

<?= $this->getChildChildHtml('additional') ?>

<script><?= $this->getChildChildHtml('scripts') ?></script>
