<form action=""
      id="co-payment-form"
      data-quote-base-grand-total="<?= (float)$this->getQuoteBaseGrandTotal() ?>"
      data-save-url="<?= $this->escapeHtml($this->getUrl('checkout/onepage/savePayment')) ?>"
      data-current-method="<?= $this->getChild('methods')->getSelectedMethodCode() ?>"
  >
  <?= $this->getChildChildHtml('methods_additional', '', true, true) ?>
  <?= $this->getChildHtml('methods') ?>
</form>

<?= $this->getChildChildHtml('additional') ?>

<!-- Don't put buttons inside the form, otherwise they will be disabed when payment object is initialized. -->
<div id="payment-buttons-container">
  <button id="btn_save_payment" type="button" class="btn btn-primary">
    <span class="please-wait" id="payment-please-wait" style="display:none;">
      <i class="fa fa-spinner fa-spin"></i>
      <span class="sr-only"><?= $this->__('Loading next step...') ?></span>
    </span>
    <?= $this->__('Continue') ?>
  </button>

  <button type="button" class="btn btn-default btn-opc-back js-opc-back" title="<?= $this->__('Back') ?>">
    <?= Mage::helper('vr_kiwiberry')->getSvgIcon('chevron-left') ?>
    <?= $this->__('Back') ?>
  </button>
</div>
