<form action=""
      id="co-payment-form"
      data-quote-base-grand-total="<?= (float)$this->getQuoteBaseGrandTotal() ?>"
      data-save-url="<?= $this->escapeHtml($this->getUrl('checkout/onepage/savePayment')) ?>"
      data-current-method="<?= $this->getChild('methods')->getSelectedMethodCode() ?>"
  >
  <?= $this->getChildChildHtml('methods_additional', '', true, true) ?>
  <?= $this->getChildHtml('methods') ?>
</form>

<?= $this->getChildChildHtml('additional') ?>

<div id="payment-buttons-container">
  <button type="button"
          class="btn btn-primary btn-sm js-opc-back"
          title="<?= $this->__('Back') ?>">
        <?= Mage::helper('vr_kiwiberry')->getSvgIcon('chevron-left') ?>
    <?= $this->__('Back') ?>
  </button>

  <button id="btn_save_payment" type="button" class="btn btn-primary">
    <?= $this->__('Continue') ?>
  </button>

  <span class="please-wait" id="payment-please-wait" style="display:none;">
    <i class="fa fa-spinner fa-spin"></i>
    <?= $this->__('Loading next step...') ?>
  </span>
</div>
