<h2><?= $this->__('Your Checkout Progress') ?></h2>

<div id="opc-block-progress"
     class="opc-block-progress panel-group <?php if (!$this->isCustomerLoggedIn()): ?>opc-block-progress-step-login<?php endif ?>">

  <?php foreach (['billing', 'shipping', 'shipping_method', 'payment'] as $stepName) : ?>
    <?php if ($this->getCheckout()->getStepData($stepName, 'is_show')): ?>

      <div id="<?= $stepName ?>-progress-opcheckout"
           class="panel panel-info">
        <?= $this->getChildHtml($stepName . '.progress') ?>
      </div>

    <?php endif ?>
  <?php endforeach ?>

</div>

