<div class="opc-block-progress<?php if (!$this->isCustomerLoggedIn()): ?> opc-block-progress-step-login<?php endif; ?>">

  <h4><?= $this->__('Your Checkout Progress') ?></h4>

  <?php $steps = array('billing', 'shipping', 'shipping_method', 'payment') ?>
  <?php foreach ($steps as $stepName) : ?>

    <?php if ($this->getCheckout()->getStepData($stepName, 'is_show')): ?>
      <div id="<?= $stepName ?>-progress-opcheckout"
           class="panel panel-primary">
        <?= $this->getChildHtml($stepName . '.progress') ?>
      </div>
    <?php endif; ?>

  <?php endforeach ?>

</div>

