<form id="co-shipping-method-form"
      action=""
      data-save-url="<?= $this->getUrl('checkout/onepage/saveShippingMethod') ?>"
  >
  <div id="checkout-shipping-method-load"><!-- Content loaded dynamically --></div>
  <div id="onepage-checkout-shipping-method-additional-load"><?= $this->getChildHtml('additional') ?></div>

  <div id="shipping-method-buttons-container">
    <button type="button" id="shipping_method_btn_continue" class="btn btn-primary">
      <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
        <i class="fa fa-spinner fa-spin"></i>
        <span class="sr-only"><?= $this->__('Loading next step...') ?></span>
      </span>
      <?= $this->__('Continue') ?>
    </button>

    <button type="button" class="btn btn-default btn-opc-back js-opc-back" title="<?= $this->__('Back') ?>">
      <?= Mage::helper('vr_kiwiberry')->getSvgIcon('chevron-left') ?>
      <?= $this->__('Back') ?>
    </button>
  </div>
</form>
