<form id="co-shipping-method-form"
      action=""
      data-save-url="<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>"
  >

  <div id="checkout-shipping-method-load"><!-- Content loaded dynamically --></div>

  <div id="onepage-checkout-shipping-method-additional-load">
    <?php echo $this->getChildHtml('additional') ?>
  </div>

  <div id="shipping-method-buttons-container">
    <button type="button"
            class="btn btn-primary btn-sm js-opc-back"
            title="<?php echo $this->__('Back') ?>">
      <i class="fa fa-angle-double-left"></i>
      <?php echo $this->__('Back') ?>
    </button>

    <button type="button"
            id="shipping_method_btn_continue"
            class="btn btn-primary">
      <?php echo $this->__('Continue') ?>
    </button>

    <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
      <i class="fa fa-spinner fa-spin"></i>
      <?php echo $this->__('Loading next step...') ?>
    </span>
  </div>
</form>
