<form id="co-shipping-form"
      action=""
      data-address-url="<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/"
      data-save-url="<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>"
      data-methods-url="<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>"
      data-regions="<?php echo $this->escapeHtml($this->helper('directory')->getRegionJsonByStore()) ?>"
  >

<?php if ($this->customerHasAddresses()): ?>
  <div class="form-group">
    <label for="shipping-address-select">
      <?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?>
    </label>
    <?php echo $this->getAddressesHtmlSelect('shipping') ?>
  </div>
<?php endif ?>

<div id="shipping-new-address-form"
     <?php if ($this->customerHasAddresses()): ?>style="display:none;"<?php endif ?>
  >

  <p class="text-danger"><?php echo $this->__('* Required Fields') ?></p>

  <input type="hidden"
         name="shipping[address_id]"
         value="<?php echo $this->getAddress()->getId() ?>"
         id="shipping:address_id">

  <?php
  echo $this->getLayout()
    ->createBlock('customer/widget_name')
    ->setObject($this->getAddress())
    ->setFieldIdFormat('shipping:%s')
    ->setFieldNameFormat('shipping[%s]')
    ->toHtml();
  ?>

  <div class="form-group">
    <label for="shipping:company"><?php echo $this->__('Company') ?></label>
    <input type="text"
           id="shipping:company"
           name="shipping[company]"
           value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
           title="<?php echo $this->__('Company') ?>"
           class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>"
      >
  </div>

  <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>

  <div class="form-group">
    <label for="shipping:street1" class="required">
      <em>*</em>
      <?php echo $this->__('Address') ?>
    </label>

    <input type="text"
           title="<?php echo $this->__('Street Address') ?>"
           name="shipping[street][]"
           id="shipping:street1"
           value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
           class="form-control <?php echo $_streetValidationClass ?>"
      >
  </div>

  <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>

  <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
    <div class="form-group">
      <label for="billing:street<?php echo $_i ?>">
        <?php echo $this->__('Address') ?>
        <?php echo $_i ?>
      </label>
      <input type="text"
             title="<?php echo $this->__('Street Address %s', $_i) ?>"
             name="shipping[street][]"
             id="shipping:street<?php echo $_i ?>"
             value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
             class="form-control <?php echo $_streetValidationClass ?>"
        >
    </div>
  <?php endfor; ?>

  <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
    <div class="form-group">
      <label for="billing:vat_id">
        <?php echo $this->__('VAT Number'); ?>
      </label>
      <input type="text"
             id="shipping:vat_id"
             name="shipping[vat_id]"
             value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>"
             title="<?php echo $this->__('VAT Number'); ?>"
             class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>">
    </div>
  <?php endif; ?>

  <div class="form-group">
    <label for="shipping:city" class="required">
      <em>*</em>
      <?php echo $this->__('City') ?>
    </label>
    <input type="text"
           title="<?php echo $this->__('City') ?>"
           name="shipping[city]"
           value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
           class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
           id="shipping:city"
      >
  </div>

  <div class="form-group">
    <label for="shipping:region" class="required">
      <em>*</em>
      <?php echo $this->__('State/Province') ?>
    </label>

    <select id="shipping:region_id"
            name="shipping[region_id]"
            title="<?php echo $this->__('State/Province') ?>"
            class="form-control validate-select"
            style="display:none;">
      <option value="">
        <?php echo $this->__('Please select region, state or province') ?>
      </option>
    </select>

    <script type="text/javascript">
      //<![CDATA[
      $('shipping:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
      //]]>
    </script>

    <input type="text"
           id="shipping:region"
           name="shipping[region]"
           value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
           title="<?php echo $this->__('State/Province') ?>"
           class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
           style="display:none;">
  </div>

  <div class="form-group">
    <label for="shipping:postcode" class="required">
      <em>*</em>
      <?php echo $this->__('Zip/Postal Code') ?>
    </label>
    <input type="text"
           title="<?php echo $this->__('Zip/Postal Code') ?>"
           name="shipping[postcode]"
           id="shipping:postcode"
           value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
           class="form-control validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"
      >
  </div>

  <div class="form-group">
    <label for="shipping:country_id" class="required">
      <em>*</em>
      <?php echo $this->__('Country') ?>
    </label>
    <?php echo $this->getCountryHtmlSelect('shipping') ?>
  </div>

  <div class="form-group">
    <label for="shipping:telephone" class="required">
      <em>*</em>
      <?php echo $this->__('Telephone') ?>
    </label>
    <input type="tel"
           name="shipping[telephone]"
           value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
           title="<?php echo $this->__('Telephone') ?>"
           class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>"
           id="shipping:telephone"
           onchange="shipping.setSameAsBilling(false);"/>
  </div>

  <div class="form-group">
    <label for="shipping:fax">
      <?php echo $this->__('Fax') ?>
    </label>
    <input type="tel"
           name="shipping[fax]"
           value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>"
           title="<?php echo $this->__('Fax') ?>"
           class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>"
           id="shipping:fax"
      >
  </div>

  <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>

    <div class="checkbox">
      <label for="shipping:save_in_address_book">
        <input type="checkbox"
               name="shipping[save_in_address_book]"
               value="1"
               title="<?php echo $this->__('Save in address book') ?>"
               id="shipping:save_in_address_book"
          <?php if ($this->getAddress()->getSaveInAddressBook()): ?> checked="checked"<?php endif; ?>
          >
        <?php echo $this->__('Save in address book') ?>
      </label>
    </div>

  <?php else: ?>

    <input type="hidden" name="shipping[save_in_address_book]" value="1">

  <?php endif; ?>

</div>

<div class="checkbox">
  <label for="shipping:same_as_billing">
    <input type="checkbox"
           name="shipping[same_as_billing]"
           id="shipping:same_as_billing"
           value="1"<?php if ($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?>
           title="<?php echo $this->__('Use Billing Address') ?>"
           class="checkbox">
    <?php echo $this->__('Use Billing Address') ?>
  </label>
</div>

<div id="shipping-buttons-container">
  <button type="button"
          class="btn btn-primary btn-sm js-opc-back"
          title="<?php echo $this->__('Back') ?>">
    <i class="fa fa-angle-double-left"></i>
    <?php echo $this->__('Back') ?>
  </button>

  <button type="button"
          id="shipping_btn_continue"
          class="btn btn-primary"
          title="<?php echo $this->__('Continue') ?>"
    >
    <?php echo $this->__('Continue') ?>
  </button>

  <span id="shipping-please-wait" class="please-wait" style="display:none;">
    <i class="fa fa-spinner fa-spin"></i>
    <?php echo $this->__('Loading next step...') ?>
  </span>
</div>

</form>

