<?php
/**
 * Customer "Remember Me" template
 *
 * @var $this Mage_Persistent_Block_Form_Remember
 */
?>
<?php $rememberMeId = 'remember_me' . Mage::helper('core')->getRandomString(10); ?>
<div class="checkbox">
  <label for="<?= $rememberMeId; ?>">
    <input type="checkbox"
           name="persistent_remember_me"
           id="<?= $rememberMeId; ?>"
           title="<?= $this->__('Remember Me') ?>"
           <?php if ($this->isRememberMeChecked()): ?>checked<?php endif; ?>
      >
    <?= $this->__('Remember Me') ?>
  </label>

  <a tabindex="0"
     role="button"
     data-toggle="popover"
     data-trigger="focus"
     data-placement="top"
     data-content="<?= $this->__('Checking &quot;Remember Me&quot; will let you access your shopping cart on this computer when you are logged out'); ?>">
    <?= $this->__('What\'s this?') ?>
  </a>
</div>

