<?php $_order = $this->getOrder() ?>

<h1><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h1>

<p>
  <?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?>
</p>

<?php
$_creditmemo = $this->getCreditmemo();
$_creditmemos = $_creditmemo ? array($_creditmemo) : $_order->getCreditmemosCollection();
?>

<?php foreach ($_creditmemos as $_creditmemo): ?>

  <h2><?php echo $this->__('Refund #%s', $_creditmemo->getIncrementId()) ?></h2>

  <?php if (!$_order->getIsVirtual()): ?>
    <div class="row">
      <div class="col-xs-6">
        <h3><?php echo $this->__('Shipping Address') ?></h3>
        <?php $_shipping = $_creditmemo->getShippingAddress() ?>
        <address><?php echo $_shipping->format('html') ?></address>
      </div>

      <div class="col-xs-6">
        <h3><?php echo $this->__('Shipping Method') ?></h3>
        <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
      </div>
    </div>
  <?php endif; ?>

  <div class="row">
    <div class="col-xs-6">
      <h3><?php echo $this->__('Billing Address') ?></h3>
      <?php $_billing = $_creditmemo->getbillingAddress() ?>
      <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
    </div>

    <div class="col-xs-6">
      <h3><?php echo $this->__('Payment Method') ?></h3>
      <?php echo $this->getPaymentInfoHtml() ?>
    </div>
  </div>

  <h3><?php echo $this->__('Items Refunded') ?></h3>

  <table class="table table-bordered" id="my-refund-table-<?php echo $_creditmemo->getId(); ?>">
    <thead>
    <tr>
      <th><?php echo $this->__('Product Name') ?></th>
      <th><?php echo $this->__('SKU') ?></th>
      <th><?php echo $this->__('Price') ?></th>
      <th><?php echo $this->__('Qty') ?></th>
      <th><?php echo $this->__('Subtotal') ?></th>
      <th><?php echo $this->__('Discount Amount') ?></th>
      <th><?php echo $this->__('Row Total') ?></th>
    </tr>
    </thead>

    <tfoot><?php echo $this->getTotalsHtml($_creditmemo); ?></tfoot>

    <tbody>
    <?php foreach ($_creditmemo->getAllItems() as $_item): ?>
      <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
      <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach; ?>
    </tbody>
  </table>
<?php endforeach; ?>
