<?php $_order = $this->getOrder() ?>

<h1><?= $this->__('Order #%s', $_order->getRealOrderId()) ?></h1>

<p>
  <?= $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?>
</p>

<?php
$_invoice = $this->getInvoice();
$_invoices = $_invoice ? array($_invoice) : $_order->getInvoiceCollection();
?>

<?php foreach ($_invoices as $_invoice): ?>
  <h2><?= $this->__('Invoice #%s', $_invoice->getIncrementId()) ?></h2>

  <?php if (!$_order->getIsVirtual()): ?>
    <div class="row">
      <div class="col-xs-6">
        <h3><?= $this->__('Shipping Address') ?></h3>
        <?php $_shipping = $_invoice->getShippingAddress() ?>
        <address><?= $_shipping->format('html') ?></address>
      </div>

      <div class="col-xs-6">
        <h3><?= $this->__('Shipping Method') ?></h3>
        <?= $this->escapeHtml($_order->getShippingDescription()) ?>
      </div>
    </div>
  <?php endif; ?>

  <div class="row">
    <div class="col-xs-6">
      <h3><?= $this->__('Billing Address') ?></h3>
      <?php $_billing = $_invoice->getbillingAddress() ?>
      <address><?= $_order->getBillingAddress()->format('html') ?></address>
    </div>

    <div class="col-xs-6">
      <h3><?= $this->__('Payment Method') ?></h3>
      <?= $this->getPaymentInfoHtml() ?>
    </div>
  </div>

  <h3><?= $this->__('Items Invoiced') ?></h3>

  <table class="table table-bordered" id="my-invoice-table-<?= $_invoice->getId(); ?>">
    <thead>
    <tr>
      <th><?= $this->__('Product Name') ?></th>
      <th><?= $this->__('SKU') ?></th>
      <th><?= $this->__('Price') ?></th>
      <th><span class="nobr"><?= $this->__('Qty Invoiced') ?></span></th>
      <th><?= $this->__('Subtotal') ?></th>
    </tr>
    </thead>

    <tfoot><?= $this->getInvoiceTotalsHtml($_invoice) ?></tfoot>

    <tbody>
    <?php
    foreach ($_invoice->getItemsCollection() as $_item):
      if ($_item->getOrderItem()->getParentItem()) continue;
      echo $this->getItemHtml($_item);
    endforeach;
    ?>
    </tbody>
  </table>
<?php endforeach; ?>
