<?php /* @var $this Mage_Sales_Block_Order_Print_Shipment */ ?>
<?php $order = $this->getOrder(); ?>

<h1><?= $this->__('Order #%s', $this->getObjectData($order, 'real_order_id')); ?></h1>

<p>
  <?= $this->__(
    'Order Date: %s',
    $this->formatDate($this->getObjectData($order, 'created_at_store_date'), 'long')) ?>
</p>

<?php if (!$this->getObjectData($order, 'is_virtual')): ?>
  <?php foreach ($this->getShipmentsCollection() as $shipment): ?>

    <h2><?= $this->__('Shipment #%s', $this->getObjectData($shipment, 'increment_id')); ?></h2>

    <div class="row">
      <div class="col-xs-6">
        <h3><?= $this->__('Shipping Address') ?></h3>
        <address><?= $this->getShipmentAddressFormattedHtml($shipment); ?></address>
      </div>

      <div class="col-xs-6">
        <h3><?= $this->__('Billing Address') ?></h3>
        <address><?= $this->getBillingAddressFormattedHtml($order); ?></address>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6">
        <h3><?= $this->__('Shipping Method') ?></h3>

        <?= $this->escapeHtml($this->getObjectData($order, 'shipping_description')); ?>

        <?php $tracks = $this->getShipmentTracks($shipment);
        if ($tracks): ?>
          <table class="table table-bordered" id="my-shipment-tracking">

            <thead>
            <tr>
              <th><?= Mage::helper('sales')->__('Title') ?></th>
              <th><?= Mage::helper('sales')->__('Number') ?></th>
            </tr>
            </thead>

            <tbody>
            <?php foreach ($tracks as $track): ?>
              <tr>
                <td><?= $this->escapeHtml($this->getObjectData($track, 'title')); ?></td>
                <td><?= $this->escapeHtml($this->getObjectData($track, 'number')); ?></td>
              </tr>
            <?php endforeach; ?>
            </tbody>
          </table>
        <?php endif; ?>
      </div>

      <div class="col-xs-6">
        <h3><?= $this->__('Payment Method') ?></h3>
        <?= $this->getPaymentInfoHtml() ?>
      </div>
    </div>

    <h3><?= $this->__('Items Shipped') ?></h3>
    <table class="table table-bordered" id="my-shipment-table-<?= $this->getObjectData($shipment, 'id') ?>">
      <thead>
      <tr>
        <th><?= $this->__('Product Name') ?></th>
        <th><?= $this->__('SKU') ?></th>
        <th class="a-center"><span class="nobr"><?= $this->__('Qty Shipped') ?></span></th>
      </tr>
      </thead>

      <tbody>
      <?php foreach ($this->getShipmentItems($shipment) as $item): ?>
        <?= $this->getItemHtml($item) ?>
      <?php endforeach; ?>
      </tbody>
    </table>

  <?php endforeach; ?>
<?php endif; ?>
