<?php /* @var $this Mage_Sales_Block_Recurring_Profiles */ ?>

<?= $this->getMessagesBlock()->toHtml() ?>

<div class="page-header">
  <h1><?= $this->__('Recurring Profiles') ?></h1>
</div>

<div class="recurring-profiles">

  <?= $this->getChildHtml('grid') ?>

  <a href="<?= $this->escapeHtml($this->getBackUrl()) ?>" class="btn btn-default">
    <i class="fa fa-angle-double-left"></i>
    <?= $this->__('Back') ?>
  </a>
</div>
