<?php /* @var $this Mage_Sales_Block_Recurring_Profiles */ ?>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="page-header">
  <h1><?php echo $this->__('Recurring Profiles') ?></h1>
</div>

<div class="recurring-profiles">

  <?php echo $this->getChildHtml('grid') ?>

  <a href="<?php echo $this->escapeHtml($this->getBackUrl()) ?>" class="btn btn-default">
    <i class="fa fa-angle-double-left"></i>
    <?php echo $this->__('Back') ?>
  </a>
</div>
