<?php
/**
 * USAGE:
 *
 * Simple:
 *
 * <?= $this->getLayout()->createBlock('customer/widget_dob')
 * ->setDate($this->getCustomer()->getDob())
 * ->toHtml() ?>
 *
 * For checkout/onepage/billing.phtml:
 *
 * <?= $this->getLayout()->createBlock('customer/widget_dob')
 * ->setDate($this->getCustomer()->getDob())
 * ->setFieldIdFormat('billing:%s')
 * ->setFieldNameFormat('billing[%s]')
 * ->toHtml() ?>
 *
 * NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css
 * Alternatively we could calculate widths automatically using block input parameters.
 */

/**
 * @see Mage_Customer_Block_Widget_Dob
 */
?>
<div id="customer-dob"
     class="form-group form-group-dob"
     data-is_required="<?= $this->isRequired() ? 'true' : 'false' ?>"
     data-date-format="<?= $this->getDateFormat() ?>">

  <label for="<?= $this->getFieldId('month') ?>"
    <?php if ($this->isRequired()) echo ' class="required"' ?>>
    <?= $this->__('Date of Birth') ?>
  </label>

  <?php ob_start() ?>
  <div class="col-xs-4 dob-day">
    <input type="number"
           id="<?= $this->getFieldId('day') ?>"
           name="<?= $this->getFieldName('day') ?>"
           value="<?= $this->getDay() ?>"
           title="<?= $this->__('Day') ?>"
           class="form-control validate-custom"
           placeholder="<?= $this->__('DD') ?>"
           <?php if ($this->isRequired()) : ?>required<?php endif ?>
      <?php $this->getFieldParams() ?>>
  </div>
  <?php $dateInputDay = ob_get_clean() ?>

  <?php ob_start() ?>
  <div class="col-xs-4 dob-month">
    <input type="number"
           id="<?= $this->getFieldId('month') ?>"
           name="<?= $this->getFieldName('month') ?>"
           value="<?= $this->getMonth() ?>"
           title="<?= $this->__('Month') ?>"
           class="form-control validate-custom"
           placeholder="<?= $this->__('MM') ?>"
           <?php if ($this->isRequired()) : ?>required<?php endif ?>
      <?php $this->getFieldParams() ?>>
  </div>
  <?php $dateInputMonth = ob_get_clean() ?>

  <?php ob_start() ?>
  <div class="col-xs-4 dob-year">
    <input type="number"
           id="<?= $this->getFieldId('year') ?>"
           name="<?= $this->getFieldName('year') ?>"
           value="<?= $this->getYear() ?>"
           title="<?= $this->__('Year') ?>"
           class="form-control validate-custom"
           placeholder="<?= $this->__('YYYY') ?>"
           <?php if ($this->isRequired()) : ?>required<?php endif ?>
      <?php $this->getFieldParams() ?>>
  </div>
  <?php $dateInputYear = ob_get_clean() ?>

  <?php
  $this->setDateInput('d', $dateInputDay);
  $this->setDateInput('m', $dateInputMonth);
  $this->setDateInput('y', $dateInputYear);
  ?>

  <div class="row">
    <?= $this->getSortedDateInputs() ?>
  </div>

  <!-- The .dob-full container here is for DOB validation working properly, which is hidden by CSS -->
  <div class="dob-full">
    <input type="hidden" id="<?= $this->getFieldId('dob') ?>" name="<?= $this->getFieldName('dob') ?>">
  </div>

  <div class="validation-advice" style="display:none;"></div>

</div>
