<?php
/**
 * USAGE:
 *
 * Simple:
 *
 * <?= $this->getLayout()->createBlock('customer/widget_dob')
 * ->setDate($this->getCustomer()->getDob())
 * ->toHtml() ?>
 *
 * For checkout/onepage/billing.phtml:
 *
 * <?= $this->getLayout()->createBlock('customer/widget_dob')
 * ->setDate($this->getCustomer()->getDob())
 * ->setFieldIdFormat('billing:%s')
 * ->setFieldNameFormat('billing[%s]')
 * ->toHtml() ?>
 *
 * NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css
 * Alternatively we could calculate widths automatically using block input parameters.
 */

/**
 * @see Mage_Customer_Block_Widget_Dob
 */
?>
<div id="customer-dob"
     class="form-group"
     data-is_required="<?= $this->isRequired() ? 'true' : 'false' ?>"
     data-date-format="<?= $this->getDateFormat() ?>">

  <label for="<?= $this->getFieldId('month') ?>"
    <?php if ($this->isRequired()) echo ' class="required"' ?>>
    <?php if ($this->isRequired()) echo '<em>*</em>' ?>
    <?= $this->__('Date of Birth') ?>
  </label>

  <?php ob_start() ?>
  <div class="form-group dob-day">
    <label for="<?php $this->getFieldId('day') ?>">
      <?= $this->__('DD') ?>
    </label>
    <input type="text"
           id="<?= $this->getFieldId('day') ?>"
           name="<?= $this->getFieldName('day') ?>"
           value="<?= $this->getDay() ?>"
           title="<?= $this->__('Day') ?>"
           class="form-control validate-custom"
      <?php $this->getFieldParams() ?>>
  </div>
  <?php $dateInputDay = ob_get_clean() ?>

  <?php ob_start() ?>
  <div class="form-group dob-month">
    <label for="<?php $this->getFieldId('month') ?>">
      <?= $this->__('MM') ?>
    </label>
    <input type="text"
           id="<?= $this->getFieldId('month') ?>"
           name="<?= $this->getFieldName('month') ?>"
           value="<?= $this->getMonth() ?>"
           title="<?= $this->__('Month') ?>"
           class="form-control validate-custom"
      <?php $this->getFieldParams() ?>>
  </div>
  <?php $dateInputMonth = ob_get_clean() ?>

  <?php ob_start() ?>
  <div class="form-group dob-year">
    <label for="<?php $this->getFieldId('year') ?>">
      <?= $this->__('YYYY') ?>
    </label>
    <input type="text"
           id="<?= $this->getFieldId('year') ?>"
           name="<?= $this->getFieldName('year') ?>"
           value="<?= $this->getYear() ?>"
           title="<?= $this->__('Year') ?>"
           class="form-control validate-custom"
      <?php $this->getFieldParams() ?>>
  </div>
  <?php $dateInputYear = ob_get_clean() ?>

  <?php
  $this->setDateInput('d', $dateInputDay);
  $this->setDateInput('m', $dateInputMonth);
  $this->setDateInput('y', $dateInputYear);
  echo $this->getSortedDateInputs();
  ?>

  <div class="dob-full" style="display:none;">
    <input type="hidden" id="<?= $this->getFieldId('dob') ?>" name="<?= $this->getFieldName('dob') ?>"/>
  </div>

  <div class="validation-advice" style="display:none;"></div>

</div>
