<div class="form-group">
  <label for="<?php echo $this->getFieldId('gender') ?>"
    <?php if ($this->isRequired()) echo ' class="required"' ?>>
    <?php if ($this->isRequired()) echo '<em>*</em>' ?>
    <?php echo $this->__('Gender') ?>
  </label>
  <select id="<?php echo $this->getFieldId('gender') ?>"
          name="<?php echo $this->getFieldName('gender') ?>"
          title="<?php echo $this->__('Gender') ?>"
          class="form-control<?php if ($this->isRequired()): ?> validate-select<?php endif; ?>"
    <?php echo $this->getFieldParams() ?>>

    <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions(); ?>
    <?php $value = $this->getGender(); ?>
    <?php foreach ($options as $option): ?>

      <option value="<?php echo $option['value'] ?>"
        <?php if ($option['value'] == $value) echo ' selected="selected"' ?>>
        <?php echo $option['label'] ?>
      </option>

    <?php endforeach; ?>
  </select>
</div>
