<div class="form-group">
  <label for="<?= $this->getFieldId('gender') ?>"
    <?php if ($this->isRequired()) echo ' class="required"' ?>>
    <?= $this->__('Gender') ?>
  </label>
  <select id="<?= $this->getFieldId('gender') ?>"
          name="<?= $this->getFieldName('gender') ?>"
          title="<?= $this->__('Gender') ?>"
          class="form-control<?php if ($this->isRequired()): ?> validate-select<?php endif; ?>"
          <?php if ($this->isRequired()): ?>required<?php endif ?>
    <?= $this->getFieldParams() ?>
    >

    <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions(); ?>
    <?php $value = $this->getGender(); ?>
    <?php foreach ($options as $option): ?>

      <option value="<?= $option['value'] ?>"
        <?php if ($option['value'] == $value) echo ' selected="selected"' ?>>
        <?= $option['label'] ?>
      </option>

    <?php endforeach; ?>
  </select>
</div>
