<?php
/**
 * USAGE:
 *
 * Simple:
 *
 * <?= $this->getLayout()->createBlock('customer/widget_name')
 * ->setObject($this->getAddress())
 * ->toHtml() ?>
 *
 * For checkout/onepage/shipping.phtml:
 *
 * <?= $this->getLayout()->createBlock('customer/widget_name')
 * ->setObject($this->getAddress())
 * ->setFieldIdFormat('shipping:%s')
 * ->setFieldNameFormat('shipping[%s]')
 * ->setFieldParams('onchange="shipping.setSameAsBilling(false);"')
 * ->toHtml() ?>
 */
/* @var $this Mage_Customer_Block_Widget_Name */
?>

<div class="<?= $this->getContainerClassName() ?> row-name">

  <?php if ($this->showPrefix()): ?>
    <div class="col-prefix">
      <div class="form-group">
        <label for="<?= $this->getFieldId('prefix') ?>"
          <?php if ($this->isPrefixRequired()) echo ' class="required"' ?>>
          <?= $this->getStoreLabel('prefix') ?>
        </label>

        <?php if ($this->getPrefixOptions() === false): ?>

          <input type="text"
                 id="<?= $this->getFieldId('prefix') ?>"
                 name="<?= $this->getFieldName('prefix') ?>"
                 value="<?= $this->escapeHtml($this->getObject()->getPrefix()) ?>"
                 title="<?= $this->getStoreLabel('prefix') ?>"
                 class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('prefix') ?>"
            <?= $this->getFieldParams() ?>>

        <?php else: ?>

          <select id="<?= $this->getFieldId('prefix') ?>"
                  name="<?= $this->getFieldName('prefix') ?>"
                  title="<?= $this->getStoreLabel('prefix') ?>"
                  class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('prefix') ?>"
            <?= $this->getFieldParams() ?>>

            <?php foreach ($this->getPrefixOptions() as $_option): ?>
              <option value="<?= $_option ?>"
                <?php if ($this->getObject()->getPrefix() == $_option): ?> selected="selected"<?php endif; ?>>
                <?= $this->__($_option) ?>
              </option>
            <?php endforeach; ?>

          </select>

        <?php endif; ?>
      </div>
    </div>
  <?php endif; ?>

  <div class="col-firstname">
    <div class="form-group">
      <label for="<?= $this->getFieldId('firstname') ?>"
             class="required">

        <?= $this->getStoreLabel('firstname') ?>
      </label>
      <input type="text"
             id="<?= $this->getFieldId('firstname') ?>"
             name="<?= $this->getFieldName('firstname') ?>"
             value="<?= $this->escapeHtml($this->getObject()->getFirstname()) ?>"
             title="<?= $this->getStoreLabel('firstname') ?>"
             maxlength="255"
             class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('firstname') ?>"
        <?= $this->getFieldParams() ?>>
    </div>
  </div>

  <?php if ($this->showMiddlename()): ?>
    <?php $isMiddlenameRequired = $this->isMiddlenameRequired(); ?>
    <div class="col-middlename">
      <div class="form-group">
        <label for="<?= $this->getFieldId('middlename') ?>"
          <?= $isMiddlenameRequired ? ' class="required"' : '' ?>>
          <?= $this->getStoreLabel('middlename') ?>
        </label>
        <input type="text"
               id="<?= $this->getFieldId('middlename') ?>"
               name="<?= $this->getFieldName('middlename') ?>"
               value="<?= $this->escapeHtml($this->getObject()->getMiddlename()) ?>"
               title="<?= $this->getStoreLabel('middlename') ?>"
               class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('middlename') ?>"
          <?= $this->getFieldParams() ?>/>
      </div>
    </div>
  <?php endif; ?>

  <div class="col-lastname">
    <div class="form-group">
      <label for="<?= $this->getFieldId('lastname') ?>"
             class="required">

        <?= $this->getStoreLabel('lastname') ?>
      </label>
      <input type="text"
             id="<?= $this->getFieldId('lastname') ?>"
             name="<?= $this->getFieldName('lastname') ?>"
             value="<?= $this->escapeHtml($this->getObject()->getLastname()) ?>"
             title="<?= $this->getStoreLabel('lastname') ?>"
             maxlength="255"
             class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('lastname') ?>"
        <?= $this->getFieldParams() ?>>
    </div>
  </div>

  <?php if ($this->showSuffix()): ?>
    <div class="col-suffix">
      <div class="form-group">
        <label for="<?= $this->getFieldId('suffix') ?>"
          <?php if ($this->isSuffixRequired()) echo ' class="required"' ?>>
          <?= $this->getStoreLabel('suffix') ?>
        </label>

        <?php if ($this->getSuffixOptions() === false): ?>

          <input type="text"
                 id="<?= $this->getFieldId('suffix') ?>"
                 name="<?= $this->getFieldName('suffix') ?>"
                 value="<?= $this->escapeHtml($this->getObject()->getSuffix()) ?>"
                 title="<?= $this->getStoreLabel('suffix') ?>"
                 class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('suffix') ?>"
            <?= $this->getFieldParams() ?>>

        <?php else: ?>

          <select id="<?= $this->getFieldId('suffix') ?>"
                  name="<?= $this->getFieldName('suffix') ?>"
                  title="<?= $this->getStoreLabel('suffix') ?>"
                  class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('suffix') ?>"
            <?= $this->getFieldParams() ?>>
            <?php foreach ($this->getSuffixOptions() as $_option): ?>

              <option value="<?= $_option ?>"
                      <?php if ($this->getObject()->getSuffix() == $_option): ?>selected="selected"<?php endif; ?>>
                <?= $this->__($_option) ?>
              </option>

            <?php endforeach; ?>
          </select>

        <?php endif; ?>

      </div>
    </div>
  <?php endif; ?>

</div>
