<div class="form-group">
  <label for="<?php echo $this->getFieldId('taxvat') ?>"
    <?php if ($this->isRequired()) echo ' class="required"' ?>>
    <?php if ($this->isRequired()) echo '<em>*</em>' ?>
    <?php echo $this->__('Tax/VAT number') ?>
  </label>
  <input type="text"
         id="<?php echo $this->getFieldId('taxvat') ?>"
         name="<?php echo $this->getFieldName('taxvat') ?>"
         value="<?php echo $this->escapeHtml($this->getTaxvat()) ?>"
         title="<?php echo $this->__('Tax/VAT number') ?>"
         class="form-control <?php echo $this->helper('customer/address')->getAttributeValidationClass('taxvat') ?>"
    <?php echo $this->getFieldParams() ?>>
</div>
