<div class="form-group">
  <label for="<?= $this->getFieldId('taxvat') ?>"
    <?php if ($this->isRequired()) echo ' class="required"' ?>>
    <?php if ($this->isRequired()) echo '<em>*</em>' ?>
    <?= $this->__('Tax/VAT number') ?>
  </label>
  <input type="text"
         id="<?= $this->getFieldId('taxvat') ?>"
         name="<?= $this->getFieldName('taxvat') ?>"
         value="<?= $this->escapeHtml($this->getTaxvat()) ?>"
         title="<?= $this->__('Tax/VAT number') ?>"
         class="form-control <?= $this->helper('customer/address')->getAttributeValidationClass('taxvat') ?>"
    <?= $this->getFieldParams() ?>>
</div>
