<?php
/**
 * @see Mage_Downloadable_Block_Customer_Products_List
 */
?>

<?= $this->getMessagesBlock()->toHtml() ?>

<div class="page-title">
  <h1><?= Mage::helper('downloadable')->__('My Downloadable Products') ?></h1>
</div>

<?= $this->getChildHtml('pager'); ?>

<?php $_items = $this->getItems(); ?>
<?php if (count($_items)): ?>

  <table class="table table-bordered table-hover" id="my-downloadable-products-table">
    <thead>
    <tr>
      <th><?= Mage::helper('downloadable')->__('Order #') ?></th>
      <th><?= Mage::helper('downloadable')->__('Date') ?></th>
      <th><?= Mage::helper('downloadable')->__('Title') ?></th>
      <th><?= Mage::helper('downloadable')->__('Status') ?></th>
      <th><span class="nobr"><?= Mage::helper('downloadable')->__('Remaining Downloads') ?></span></th>
    </tr>
    </thead>

    <tbody>
    <?php $_odd = ''; ?>
    <?php foreach ($_items as $_item): ?>

      <tr>
        <td data-rwd-label="<?= Mage::helper('downloadable')->__('Order #') ?>">
          <a href="<?= $this->getOrderViewUrl($_item->getPurchased()->getOrderId()) ?>"
             title="<?= Mage::helper('downloadable')->__('View Order') ?>">
            <?= $_item->getPurchased()->getOrderIncrementId() ?>
          </a>
        </td>
        <td data-rwd-label="<?= Mage::helper('downloadable')->__('Date') ?>">
          <span class="nobr"><?= $this->formatDate($_item->getPurchased()->getCreatedAt()) ?></span>
        </td>
        <td data-rwd-label="<?= Mage::helper('downloadable')->__('Title') ?>">
          <?= $this->escapeHtml($_item->getPurchased()->getProductName()) ?>
          -
          <a href="<?= $this->getDownloadUrl($_item) ?>"
             title="<?= Mage::helper('downloadable')->__('Start Download') ?>"
             <?php if ($this->getIsOpenInNewWindow()) : ?>target="_blank"<?php endif ?>
            >
            <?= $this->escapeHtml($_item->getLinkTitle()); ?>
          </a>
        </td>
        <td data-rwd-label="<?= Mage::helper('downloadable')->__('Status') ?>">
          <em><?= Mage::helper('downloadable')->__(ucfirst($_item->getStatus())) ?></em></td>
        <td data-rwd-label="<?= Mage::helper('downloadable')->__('Remaining Downloads') ?>">
          <?= $this->getRemainingDownloads($_item) ?>
        </td>
      </tr>

    <?php endforeach; ?>
    </tbody>

  </table>

<?php else: ?>

  <p class="text-info">
    <?= Mage::helper('downloadable')->__('You have not purchased any downloadable products yet.'); ?>
  </p>

<?php endif; ?>

<?= $this->getChildHtml('pager'); ?>

<a href="<?= $this->escapeUrl($this->getBackUrl()) ?>" class="btn btn-default">
  <i class="fa fa-angle-double-left"></i>
  <?= $this->__('Back') ?>
</a>
