<?php $_product = $this->getProduct(); ?>
<?php if ($this->displayProductStockStatus()): ?>
<p class="availability">
  <?php echo $this->helper('catalog')->__('Availability:') ?>

  <?php if ($_product->isAvailable()): ?>
    <?php echo $this->helper('catalog')->__('In stock') ?>
  <?php else: ?>
    <?php echo $this->helper('catalog')->__('Out of stock') ?>
  <?php endif; ?>
</p>
<?php endif; ?>
