<?php
$_product = $this->getProduct();
$_associatedProducts = $this->getAssociatedProducts();
$_hasAssociatedProducts = count($_associatedProducts) > 0;
?>

<?php if ($this->displayProductStockStatus()): ?>
  <p class="availability">
    <?= $this->helper('catalog')->__('Availability:') ?>

    <?php if ($_product->isAvailable() && $_hasAssociatedProducts): ?>
      <?= $this->helper('catalog')->__('In stock') ?>
    <?php else: ?>
      <?= $this->helper('catalog')->__('Out of stock') ?>
    <?php endif; ?>
  </p>
<?php endif; ?>
