<img class="img-responsive img-thumbnail"
     src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/catwomen-newimg.jpg' ?>"
     alt="Bon Voyage - sleek and stylish selections for on-the-go" >

<div class="row">

  <div class="col-sm-3">
    <a class="thumbnail" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'women/new-arrivals.html' ?>">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/Womennewarrivalsimg.jpg' ?>"
           alt="New Arrivals">
      <div class="caption"><h3>New Arrivals</h3></div>
    </a>
  </div>

  <div class="col-sm-3">
    <a class="thumbnail" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'women/tops-blouses.html' ?>">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/Womentopsimg.jpg' ?>"
           alt="Tops &amp; Blouses">
      <div class="caption"><h3>Tops &amp; Blouses</h3></div>
    </a>
  </div>

  <div class="col-sm-3">
    <a class="thumbnail" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'women/pants-denim.html' ?>">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/Womenpantsimg.jpg' ?>"
           alt="Pants &amp; Denim">
      <div class="caption"><h3>Pants &amp; Denim</h3></div>
    </a>
  </div>

  <div class="col-sm-3">
    <a class="thumbnail" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'women/dresses-skirts.html' ?>">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/Womenskirtsimg.jpg' ?>"
           alt="Dresses &amp; Skirts">
      <div class="caption"><h3>Dresses &amp; Skirts</h3></div>
    </a>
  </div>

</div>
