<img class="img-responsive img-thumbnail"
     src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/Cataccessoriesmainimg.jpg' ?>"
     alt="Hold It - Jet setting just got easier with our innovative travel gear and accessories" >

<div class="row">

  <div class="col-sm-3">
    <a class="thumbnail" href="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'accessories/eyewear.html' ?>">
      <img src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/accessorieseyewearimg.jpg"' ?>"
           alt="Eyewear">
      <div class="caption"><h3>Eyewear</h3></div>
    </a>
  </div>

  <div class="col-sm-3">
    <a class="thumbnail" href="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'accessories/jewelry.html"' ?>">
      <img src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/acessoreiesjeweleryimg.jpg"' ?>"
           alt="Jewelry">
      <div class="caption"><h3>Jewelry</h3></div>
    </a>
  </div>

  <div class="col-sm-3">
    <a class="thumbnail" href="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'accessories/shoes.html"' ?>">
      <img src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/accessoriesshoesimg.jpg"' ?>"
           alt="Shoes">
      <div class="caption"><h3>Shoes</h3></div>
    </a>
  </div>

  <div class="col-sm-3">
    <a class="thumbnail" href="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'accessories/bags-luggage.html"' ?>">
      <img src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/Accessoriesbagimg.jpg"' ?>"
           alt="Bags & Luggage">
      <div class="caption"><h3>Bags & Luggage</h3></div>
    </a>
  </div>

</div>

<div class="alert alert-danger" role="alert">
  <a class="alert-link" href="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'accessories/shoes.html' ?>">50% OFF ALL SHOES!</a>
</div>
