<img class="img-responsive img-thumbnail"
     src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/mainimg-home_decorcategory.jpg' ?>"
     alt="Bon Voyage - sleek and stylish selections for on-the-go" >

<div class="row">

  <div class="col-sm-3">
    <a class="thumbnail" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'home-decor/books-music.html' ?>">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/Homecatimg-books.jpg' ?>"
           alt="Books &amp; Music">
      <div class="caption"><h3>Books &amp; Music</h3></div>
    </a>
  </div>

  <div class="col-sm-3">
    <a class="thumbnail" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'home-decor/bed-bath.html' ?>">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/home_bed_bathimg.jpg' ?>"
           alt="Bed &amp; Bath">
      <div class="caption"><h3>Bed &amp; Bath</h3></div>
    </a>
  </div>

  <div class="col-sm-3">
    <a class="thumbnail" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'home-decor/electronics.html' ?>">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/Homecatimg-electronics.jpg' ?>"
           alt="Electronics">
      <div class="caption"><h3>Electronics/h3></div>
    </a>
  </div>

  <div class="col-sm-3">
    <a class="thumbnail" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'home-decor/decorative-accents.html' ?>">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/Homecatimg-decor.jpg' ?>"
           alt="Decorative Accents">
      <div class="caption"><h3>Decorative Accents</h3></div>
    </a>
  </div>

</div>
