<img class="img-responsive img-thumbnail"
     src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/catmen-newimg.jpg' ?>"
     alt="Bold New Blues - superior fabrics and tailored fits in subtle and standout hues" >

<div class="row">

  <div class="col-sm-3">
    <a class="thumbnail" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'men/new-arrivals.html' ?>">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/mencat-newarrivalsimg.jpg' ?>"
           alt="New Arrivals">
      <div class="caption"><h3>New Arrivals</h3></div>
    </a>
  </div>

  <div class="col-sm-3">
    <a class="thumbnail" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'men/shirts.html' ?>">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/clp-sub-m-shirts.jpg' ?>"
           alt="Shirts">
      <div class="caption"><h3>Shirts</h3></div>
    </a>
  </div>

  <div class="col-sm-3">
    <a class="thumbnail" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . 'men/tees-knits-and-polos.html' ?>">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/Mencat-teesimg.jpg' ?>"
           alt="Tees, Knits and Polos">
      <div class="caption"><h3>Tees, Knits and Polos</h3></div>
    </a>
  </div>

  <div class="col-sm-3">
    <a class="thumbnail" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) . '}men/pants-denim.html' ?>">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/mencat-pants.jpg' ?>"
           alt="Pants &amp; Denis">
      <div class="caption"><h3>Pants &amp; Denis</h3></div>
    </a>
  </div>

</div>
