<h2>Company</h2>

<ul class="nav nav-pills nav-stacked" role="tablist">
  <li role="presentation">
    <a href="<?= Mage::getUrl('about-magento-demo-store') ?>">About Us</a>
  </li>
  <li role="presentation">
    <a href="<?= Mage::getUrl('contacts') ?>">Contact Us</a>
  </li>
  <li role="presentation">
    <a href="<?= Mage::getUrl('customer-service') ?>">Customer Service</a>
  </li>
  <li role="presentation">
    <a href="<?= Mage::getUrl('privacy-policy-cookie-restriction-mode') ?>">Privacy Policy</a>
  </li>
</ul>
