<h2>Company</h2>

<ul class="nav nav-pills nav-stacked" role="tablist">
  <li role="presentation"
      <?php if ('about-magento-demo-store' === trim(Mage::app()->getRequest()->getRequestUri(), '/')): ?>
        class="active"
      <?php endif ?>
    >
    <a href="<?= Mage::getUrl('about-magento-demo-store') ?>">About Us</a>
  </li>
  <li role="presentation"
      <?php if ('contacts' === Mage::app()->getRequest()->getModuleName()): ?>class="active"<?php endif ?>
    >
    <a href="<?= Mage::getUrl('contacts') ?>">Contact Us</a>
  </li>
  <li role="presentation"
    <?php if ('customer-service' === trim(Mage::app()->getRequest()->getRequestUri(), '/')): ?>
      class="active"
    <?php endif ?>
    >
    <a href="<?= Mage::getUrl('customer-service') ?>">Customer Service</a>
  </li>
  <li role="presentation"
    <?php if ('privacy-policy-cookie-restriction-mode' === trim(Mage::app()->getRequest()->getRequestUri(), '/')): ?>
      class="active"
    <?php endif ?>
    >
    <a href="<?= Mage::getUrl('privacy-policy-cookie-restriction-mode') ?>">Privacy Policy</a>
  </li>
  <li role="presentation"
    <?php if ('reward-points' === trim(Mage::app()->getRequest()->getRequestUri(), '/')): ?>
      class="active"
    <?php endif ?>
    >
    <a href="<?= Mage::getUrl('reward-points') ?>">Reward Points</a>
  </li>
</ul>
