<h5 class=footer-label>Connect With Us</h5>
<ul class="footer-sns-links">
  <li>
    <a href="http://facebook.com/" target="_blank" data-toggle="tooltip" data-placement="top" title="Facebook">
      <?= Mage::helper('vr_kiwiberry')->getSvgIcon('facebook') ?>
      <span class="sr-only">Facebook</span>
    </a>
  </li>
  <li>
    <a href="http://twitter.com/" target="_blank" data-toggle="tooltip" data-placement="top" title="Twitter">
      <?= Mage::helper('vr_kiwiberry')->getSvgIcon('twitter') ?>
      <span class="sr-only">Twitter</span>
    </a>
  </li>
  <li>
    <a href="http://instagram.com/" target="_blank" data-toggle="tooltip" data-placement="top" title="Instagram">
      <?= Mage::helper('vr_kiwiberry')->getSvgIcon('instagram') ?>
      <span class="sr-only">Instagram</span>
    </a>
  </li>
  <li>
    <a href="http://youtube.com/" target="_blank" data-toggle="tooltip" data-placement="top" title="Youtube">
      <?= Mage::helper('vr_kiwiberry')->getSvgIcon('youtube-play') ?>
      <span class="sr-only">YouTube</span>
    </a>
  </li>
  <li>
    <a href="http://pinterest.com/" target="_blank" data-toggle="tooltip" data-placement="top" title="Pinterest">
      <?= Mage::helper('vr_kiwiberry')->getSvgIcon('pinterest') ?>
      <span class="sr-only">Pinterest</span>
    </a>
  </li>

  <li>
    <a href="<?= Mage::getUrl('rss') ?>" data-toggle="tooltip" data-placement="top" title="RSS">
      <?= Mage::helper('vr_kiwiberry')->getSvgIcon('rss') ?>
      <span class="sr-only">RSS</span>
    </a>
  </li>
</ul>
