<h5>Connect With Us</h5>
<ul class="footer-sns-links">
  <li>
    <a href="http://facebook.com/" target="_blank" data-toggle="tooltip" data-placement="top" title="Facebook">
      <i class="fa fa-fw fa-lg fa-facebook"></i>
      <span class="sr-only">Facebook</span>
    </a>
  </li>
  <li>
    <a href="http://twitter.com/" target="_blank" data-toggle="tooltip" data-placement="top" title="Twitter">
      <i class="fa fa-fw fa-lg fa-twitter"></i>
      <span class="sr-only">Twitter</span>
    </a>
  </li>
  <li>
    <a href="http://instagram.com/" target="_blank" data-toggle="tooltip" data-placement="top" title="Instagram">
      <i class="fa fa-fw fa-lg fa-instagram"></i>
      <span class="sr-only">Instagram</span>
    </a>
  </li>
  <li>
    <a href="http://youtube.com/" target="_blank" data-toggle="tooltip" data-placement="top" title="Youtube">
      <i class="fa fa-fw fa-lg fa-youtube-play"></i>
      <span class="sr-only">YouTube</span>
    </a>
  </li>
  <li>
    <a href="http://pinterest.com/" target="_blank" data-toggle="tooltip" data-placement="top" title="Pinterest">
      <i class="fa fa-fw fa-lg fa-pinterest"></i>
      <span class="sr-only">Pinterest</span>
    </a>
  </li>

  <li>
    <a href="<?php echo Mage::getUrl('rss') ?>" data-toggle="tooltip" data-placement="top" title="RSS">
      <i class="fa fa-fw fa-lg fa-rss"></i>
      <span class="sr-only">RSS</span>
    </a>
  </li>
</ul>
