<h5 class="footer-label">Our Company</h5>
<ul class="footer-cms-links">
  <li><a href="<?= Mage::getBaseUrl() ?>about-magento-demo-store/">About Us</a></li>
  <li><a href="<?= Mage::getBaseUrl() ?>contacts/">Contact Us</a></li>
  <li><a href="<?= Mage::getBaseUrl() ?>customer-service/">Customer Service</a></li>
  <li><a href="<?= Mage::getBaseUrl() ?>privacy-policy-cookie-restriction-mode/">Privacy Policy</a></li>
</ul>
