<?php $_order = $this->getOrder() ?>

<p>
  <a href="<?= $this->getPrintAllCreditmemosUrl($_order) ?>"
     target="_blank"
     class="btn btn-default">
    <?= $this->__('Print All Refunds') ?>
  </a>
</p>

<?php foreach ($_order->getCreditmemosCollection() as $_creditmemo): ?>

  <h2>
    <?= $this->__('Refund #') . $_creditmemo->getIncrementId(); ?>

    <small>
      <a href="<?= $this->getPrintCreditmemoUrl($_creditmemo) ?>"
         target="_blank">
        <?= $this->__('Print Refund') ?>
      </a>
    </small>
  </h2>

  <h3><?= $this->__('Items Refunded') ?></h3>

  <table class="table table-bordered table-creditmemo" id="my-refund-table-<?= $_creditmemo->getId(); ?>">

    <thead>
    <tr>
      <th><?= $this->__('Product Name') ?></th>
      <th><?= $this->__('SKU') ?></th>
      <th><?= $this->__('Price') ?></th>
      <th><?= $this->__('Qty') ?></th>
      <th><?= $this->__('Subtotal') ?></th>
      <th><?= $this->__('Discount Amount') ?></th>
      <th><?= $this->__('Row Total') ?></th>
    </tr>
    </thead>

    <tfoot><?= $this->getTotalsHtml($_creditmemo); ?></tfoot>

    <tbody>
    <?php foreach ($_creditmemo->getAllItems() as $_item): ?>
      <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
      <?= $this->getItemHtml($_item) ?>
    <?php endforeach; ?>
    </tbody>

  </table>

  <?= $this->getCommentsHtml($_creditmemo) ?>

<?php endforeach; ?>
