<?php
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>
<form id="search_mini_form" class="navbar-form navbar-right" role="search" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
  <div class="form-group">
    <div class="input-group">
      <label for="search" class="sr-only"><?php echo $this->__('Search:') ?></label>
      <input
        id="search"
        class="form-control"
        placeholder="<?php echo $this->__('Search entire store here...') ?>"
        type="text"
        name="<?php echo $catalogSearchHelper->getQueryParamName() ?>"
        value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>"
        maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>"
        data-suggest-url="<?php echo $catalogSearchHelper->getSuggestUrl() ?>"
        >
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit" title="<?php echo $this->__('Search') ?>">
          <i class="fa fa-search"></i>
        </button>
      </span>
    </div>
  </div>
  <div id="search_autocomplete" class="search-autocomplete"></div>
</form>
