<form id="newsletter-validate-detail"
      action="<?= $this->getFormActionUrl() ?>"
      method="post"
      role="form"
      class="js-validate-form"
  >

  <label class="footer-label" for="newsletter">
    <?= $this->__('Sign Up for Our Newsletter:') ?>
  </label>

  <div class="input-group input-group-subscription input-group-sm">
    <input type="email"
           autocapitalize="off"
           autocorrect="off"
           autocomplete="email"
           spellcheck="false"
           name="email"
           id="newsletter"
           title="<?= $this->__('Sign up for our newsletter') ?>"
           placeholder="john@example.com"
           class="form-control"
           required
      >
    <sapn class="input-group-btn">
      <button type="submit" title="<?= $this->__('Subscribe') ?>" class="btn btn-primary">
        <?= $this->__('Subscribe') ?>
      </button>
    </sapn>
  </div>

</form>
