<?php
/**
 * Language switcher template
 *
 * @see Mage_Page_Block_Switch
 */
?>
<?php if(count($this->getStores())>1): ?>
<form class="navbar-form navbar-left" role="language">
  <div class="form-group">
    <label for="select_language"><i class="fa fa-language"></i></label>
    <select id="select_language" class="form-control js-change-location" title="<?php echo $this->__('Language') ?>">
    <?php foreach ($this->getStores() as $_lang): ?>
        <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
        <option value="<?php echo $_lang->getCurrentUrl() ?>"<?php echo $_selected ?>><?php echo $this->escapeHtml($_lang->getName()) ?></option>
    <?php endforeach; ?>
    </select>
  </div>
</form>
<?php endif; ?>
