<?php
/**
 * Language switcher template
 *
 * @see Mage_Page_Block_Switch
 */
?>
<?php if (count($this->getStores()) > 1): ?>
  <div class="language-switcher btn-group btn-group-sm dropup">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <?= Mage::helper('vr_kiwiberry')->getSvgIcon('language') ?>
      <span class="title"><?= $this->__('Language') ?></span>
      <span class="caret"></span>
    </button>

    <ul class="dropdown-menu" role="menu">
      <?php foreach ($this->getStores() as $_lang): ?>

        <li <?php if ($_lang->getId() == $this->getCurrentStoreId()): ?>class="active"<?php endif ?>>
          <a href="<?= $_lang->getCurrentUrl() ?>">
            <?= $this->escapeHtml($_lang->getName()) ?>
          </a>
        </li>

      <?php endforeach; ?>
    </ul>
  </div>
<?php endif; ?>
