<?php
/**
 * Store switcher template
 *
 * @see Mage_Core_Block_Store_Switcher
 */
?>
<?php if (count($this->getGroups()) > 1): ?>

  <div class="language-switcher btn-group btn-group-sm dropup">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <?= Mage::helper('vr_kiwiberry')->getSvgIcon('language') ?>
      <span class="title"><?= $this->__('Store') ?></span>
      <span class="caret"></span>
    </button>

    <ul class="dropdown-menu" role="menu">
      <?php foreach ($this->getGroups() as $_group): ?>

        <li <?php if ($_group->getId() == $this->getCurrentGroupId()): ?>class="active"<?php endif ?>>
          <a href="<?= $_group->getHomeUrl() ?>">
            <?= $this->escapeHtml($_group->getName()) ?>
          </a>
        </li>

      <?php endforeach; ?>
    </ul>
  </div>

<?php endif; ?>
