<input type="hidden" name="related_product" id="related-products-field" value="">

<?php if ($this->getItems()->getSize()): ?>
  <h2><?= $this->__('Related Products') ?></h2>

  <p class="block-subtitle">
    <?= $this->__('Check items to add to the cart or') ?>&nbsp;
    <a id="select-all-related" href="#">
      <?= $this->__('select all') ?>
    </a>
  </p>

  <ul class="list-unstyled" id="block-related">
    <?php foreach ($this->getItems() as $_item): ?>

      <li>

        <?php if (!$_item->isComposite()
          && $_item->isSaleable()
          && !$_item->getRequiredOptions()
        ): ?>
          <input type="checkbox"
                 class="cb-related-product pull-left js-related-checkbox"
                 id="related-checkbox<?= $_item->getId() ?>"
                 name="related_products[]"
                 value="<?= $_item->getId() ?>"/>
        <?php endif; ?>

        <div class="related-product media">
          <a href="<?= $_item->getProductUrl() ?>"
             title="<?= $this->escapeHtml($_item->getName()) ?>"
             class="pull-left">
            <img src="<?= $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(75) ?>"
                 class="img-responsive media-object"
                 alt="<?= $this->escapeHtml($_item->getName()) ?>"/>
          </a>

          <div class="media-body">
            <h4 class="media-heading">
              <a href="<?= $_item->getProductUrl() ?>">
                <?= $this->escapeHtml($_item->getName()) ?>
              </a>
            </h4>

            <?= $this->getPriceHtml($_item, true, '-related') ?>

            <?php if ($this->helper('wishlist')->isAllow()) : ?>
              <a href="<?= $this->getAddToWishlistUrl($_item) ?>">
                <?= $this->__('Add to Wishlist') ?>
              </a>
            <?php endif; ?>
          </div>
        </div>
      </li>

    <?php endforeach ?>
  </ul>
<?php endif ?>
