<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if ($this->getCollection()->getSize()): ?>
  <div class="toolbar">

    <div class="toolbar-left">
      <?php if ($this->isExpanded()): ?>

        <!-- Sort By -->
        <div class="sort-by">
          <label for="sort_by"><?= $this->__('Sort By') ?></label>
          <select id="sort_by" class="form-control js-change-location" title="<?= $this->__('Sort By') ?>">
            <?php foreach ($this->getAvailableOrders() as $_key => $_order): ?>
              <option value="<?= $this->getOrderUrl($_key, 'asc') ?>"
                <?php if ($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>
                >
                <?= $this->__($_order) ?>
              </option>
            <?php endforeach; ?>
          </select>

          <?php if ($this->getCurrentDirection() == 'desc'): ?>
            <a href="<?= $this->getOrderUrl(null, 'asc') ?>"
               title="<?= $this->__('Set Ascending Direction') ?>"
               class="btn btn-default"
              >
              <?= Mage::helper('vr_kiwiberry')->getSvgIcon('sort-amount-asc') ?>
              <span class="sr-only"><?= $this->__('Set Ascending Direction') ?></span>
            </a>
          <?php else: ?>
            <a href="<?= $this->getOrderUrl(null, 'desc') ?>"
               title="<?= $this->__('Set Descending Direction') ?>"
               class="btn btn-default"
              >
              <?= Mage::helper('vr_kiwiberry')->getSvgIcon('sort-amount-desc') ?>
              <span class="sr-only"><?= $this->__('Set Descending Direction') ?></span>
            </a>
          <?php endif; ?>
        </div>

        <!-- Mode Switcher -->
        <?php if ($this->isEnabledViewSwitcher()): ?>
          <div class="view-mode">
            <?php $_modes = $this->getModes(); ?>
            <?php if ($_modes && count($_modes) > 1): ?>

              <label><?= $this->__('View as') ?></label>

              <div class="btn-group">
                <?php foreach ($this->getModes() as $_code => $_label): ?>

                  <a href="<?= $this->getModeUrl($_code) ?>"
                     title="<?= $_label ?>"
                     class="btn btn-default<?php if ($this->isModeActive($_code)): echo ' active'; endif; ?>">
                    <?= Mage::helper('vr_kiwiberry')->getSvgIcon($_code === 'grid' ? 'th' : 'list') ?>
                    <span class="sr-only"><?= $_label ?></span>
                  </a>

                <?php endforeach; ?>
              </div>

            <?php endif; ?>
          </div>
        <?php endif; ?>

      <?php endif; ?>
    </div>

    <div class="toolbar-right">
      <div class="page-limiter">
        <!-- Product Item Counter -->
        <span class="item-count">
          <?php
          if ($this->getLastPageNum() > 1):
            echo $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum());
          else:
            echo $this->__('%s Item%s', $this->getTotalNum(), $this->getTotalNum() > 1 ? 's' : '');
          endif
          ?>
        </span>

        <!-- Results Per Page -->
        <label for="results_per_page"><?= $this->__('Show') ?></label>
        <select id="results_per_page" class="form-control js-change-location"
                title="<?= $this->__('Results Per Page'); ?>">
          <?php foreach ($this->getAvailableLimit() as $_key => $_limit): ?>
            <option value="<?= $this->getLimitUrl($_key) ?>"
              <?php if ($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
              <?= $_limit ?>
            </option>
          <?php endforeach; ?>
        </select>
      </div>

      <!-- Pager -->
      <?= $this->getPagerHtml() ?>
    </div>
  </div>
<?php endif ?>
