<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="<?= $this->getLang(); ?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?= $this->getLang(); ?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?= $this->getLang(); ?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?= $this->getLang(); ?>" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?= $this->getLang(); ?>" id="top" class="no-js"> <!--<![endif]-->
<head>
<?= $this->getChildHtml('head') ?>
</head>
<body class="page-popup <?= $this->getBodyClass()?$this->getBodyClass() : ''?>">

  <?= $this->getChildHtml('after_body_start') ?>

  <div class="container container-body">
    <?= $this->getChildHtml('content') ?>
  </div>

  <?= $this->getChildHtml('before_body_end') ?>
  <?= $this->getAbsoluteFooter() ?>

</body>
</html>
