<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js"> <!--<![endif]-->
<head>
  <?php echo $this->getChildHtml('head') ?>
</head>
<body class="page-print js-page-print <?php echo $this->getBodyClass() ? $this->getBodyClass() : '' ?>">
<div class="container">

  <div>
    <img src="<?php echo $this->getPrintLogoUrl() ? $this->getPrintLogoUrl() : $this->getSkinUrl('images/logo_print.gif') ?>"
         class="logo-print"
         alt=""/>

    <?php if ($this->getPrintLogoText()): ?>
      <address><?php echo nl2br($this->escapeHtml($this->getPrintLogoText())) ?></address>
    <?php endif; ?>
  </div>

  <?php echo $this->getChildHtml('content') ?>

  <?php echo $this->getChildHtml('kiwiberry_js') ?>

  <?php echo $this->getAbsoluteFooter() ?>

</div>
</body>
</html>
