<h2><?php echo $this->__('Address Book') ?></h2>

<p>
  <a href="<?php echo $this->getAddressBookUrl() ?>">
    <?php echo $this->__('Manage Addresses') ?>
  </a>
</p>

<div class="row">

  <div class="col-md-6">
    <div class="panel panel-default">

      <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->__('Default Billing Address') ?></h3>
        <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
      </div>

      <div class="panel-body">
        <address><?php echo $this->getPrimaryBillingAddressHtml() ?></address>
      </div>

    </div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-default">

      <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->__('Default Shipping Address') ?></h3>
        <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
      </div>

      <div class="panel-body">
        <address><?php echo $this->getPrimaryShippingAddressHtml() ?></address>
      </div>

    </div>
  </div>

</div>
