<h2><?= $this->__('Address Book') ?></h2>

<p>
  <a href="<?= $this->getAddressBookUrl() ?>">
    <?= $this->__('Manage Addresses') ?>
  </a>
</p>

<div class="row">

  <div class="col-md-6">
      <div class="panel panel-primary">

      <div class="panel-heading">
        <h3 class="panel-title"><?= $this->__('Default Billing Address') ?></h3>
        <a href="<?= $this->getPrimaryBillingAddressEditUrl() ?>"><?= $this->__('Edit Address') ?></a>
      </div>

      <div class="panel-body">
        <address><?= $this->getPrimaryBillingAddressHtml() ?></address>
      </div>

    </div>
  </div>

  <div class="col-md-6">
      <div class="panel panel-primary">

      <div class="panel-heading">
        <h3 class="panel-title"><?= $this->__('Default Shipping Address') ?></h3>
        <a href="<?= $this->getPrimaryShippingAddressEditUrl() ?>"><?= $this->__('Edit Address') ?></a>
      </div>

      <div class="panel-body">
        <address><?= $this->getPrimaryShippingAddressHtml() ?></address>
      </div>

    </div>
  </div>

</div>
