<div class="row">

  <div class="col-md-6">

      <div class="panel panel-primary">

      <div class="panel-heading">
        <h3 class="panel-title"><?= $this->__('Contact Information') ?></h3>
        <a href="<?= $this->getUrl('customer/account/edit') ?>"><?= $this->__('Edit') ?></a>
      </div>

      <div class="panel-body">
        <?= $this->escapeHtml($this->getCustomer()->getName()) ?><br/>
        <?= $this->escapeHtml($this->getCustomer()->getEmail()) ?><br/>
        <a href="<?= $this->getChangePasswordUrl() ?>"><?= $this->__('Change Password') ?></a>
      </div>

    </div>

  </div>

  <?php if ($this->isNewsletterEnabled()): ?>
    <div class="col-md-6">

        <div class="panel panel-primary">

        <div class="panel-heading">
          <h3 class="panel-title"><?= $this->__('Newsletters') ?></h3>
          <a href="<?= $this->getUrl('newsletter/manage') ?>"><?= $this->__('Edit') ?></a>
        </div>

        <div class="panel-body">
          <?php if ($this->getIsSubscribed()): ?>
            <?= $this->__("You are currently subscribed to 'General Subscription'.") ?>
          <?php else: ?>
            <?= $this->__('You are currently not subscribed to any newsletter.') ?>
          <?php endif; ?>
        </div>

      </div>

      <?php /* Extensions placeholder */ ?>
      <?= $this->getChildHtml('customer.account.dashboard.info.extra') ?>

    </div>
  <?php endif; ?>

</div>
