<div class="row">

  <div class="col-md-6">

    <div class="panel panel-default">

      <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->__('Contact Information') ?></h3>
        <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
      </div>

      <div class="panel-body">
        <?php echo $this->escapeHtml($this->getCustomer()->getName()) ?><br/>
        <?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?><br/>
        <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
      </div>

    </div>

  </div>

  <?php if ($this->isNewsletterEnabled()): ?>
    <div class="col-md-6">

      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="panel-title"><?php echo $this->__('Newsletters') ?></h3>
          <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
        </div>

        <div class="panel-body">
          <?php if ($this->getIsSubscribed()): ?>
            <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
          <?php else: ?>
            <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
          <?php endif; ?>
        </div>

      </div>

      <?php /* Extensions placeholder */ ?>
      <?php echo $this->getChildHtml('customer.account.dashboard.info.extra') ?>

    </div>
  <?php endif; ?>

</div>
