<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php $_links = $this->getLinks(); ?>
<?php if (count($_links) > 0): ?>
  <ul class="dropdown-menu header-top-links" role="menu">

    <li class="welcome-msg"><?= $this->getChildHtml('welcome') ?></li>

    <?php foreach ($_links as $_link): ?>
      <?php if ($_link instanceof Mage_Core_Block_Abstract): ?>
        <?= $_link->toHtml() ?>
      <?php else: ?>
        <li <?= $_link->getLiParams() ?>>
          <?= $_link->getBeforeText() ?>
          <a href="<?= $_link->getUrl() ?>"
             title="<?= $_link->getTitle() ?>" <?= $_link->getAParams() ?>>
            <?= $_link->getLabel() ?>
          </a>
          <?= $_link->getAfterText() ?>
        </li>
      <?php endif; ?>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
