<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>
  <ul class="nav navbar-nav navbar-right"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
    <?php foreach($_links as $_link): ?>
      <?php if ($_link instanceof Mage_Core_Block_Abstract):?>
        <?php echo $_link->toHtml() ?>
      <?php else: ?>
        <li <?php echo $_link->getLiParams() ?>>
          <?php echo $_link->getBeforeText() ?>
          <a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>>
            <?php
            $iconClass = Mage::helper('vr_kiwiberry')->getFaIconClassFromLabel($_link->getLabel());
            if ($iconClass):
            ?>
              <i class="fa <?php echo $iconClass ?>"></i>
            <?php endif ?>
            <?php echo $_link->getLabel() ?>
          </a>
          <?php echo $_link->getAfterText() ?>
        </li>
      <?php endif;?>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
