<?php $_order = $this->getOrder() ?>

<div>
  <?php if ($this->helper('rss/order')->isStatusNotificationAllow()): ?>
    <a href="<?= $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>" class="btn btn-default">
      <?= $this->__('Subscribe to Order Status') ?>
    </a>
  <?php endif; ?>

  <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
    <a href="<?= $this->getReorderUrl($_order) ?>" class="btn btn-default">
      <?= $this->__('Reorder') ?>
    </a>
  <?php endif ?>

  <a href="<?= $this->getPrintUrl($_order) ?>"
     class="btn btn-default"
     target="_blank">
    <?= $this->__('Print Order') ?>
  </a>
  <?= $this->getChildHtml(); ?>
</div>
