<?php /** @var $this Mage_Oauth_Block_Customer_Token_List */ ?>

<?= $this->getMessagesBlock()->toHtml() ?>

<div class="page-title">
  <h1><?= $this->__('My Applications') ?></h1>
</div>

<?php if ($this->getCollection() && $this->count()): ?>

  <?= $this->getToolbarHtml() ?>

  <table class="table table-bordered table-hover" id="my-apps-table">
    <thead>
    <tr>
      <th><?= $this->__('App Name') ?></th>
      <th><?= $this->__('Status') ?></th>
      <th>&nbsp;</th>
    </tr>
    </thead>

    <tbody>
    <?php /** @var $item Mage_Oauth_Model_Token */ ?>
    <?php foreach ($this->getCollection() as $item) : ?>

      <tr>
        <td><?= $this->escapeHtml($item->getName()); ?></td>
        <td><em><?= $this->getStatusLabel($item->getRevoked()) ?></em></td>
        <td>
          <a href="<?= $this->getUpdateRevokeLink($item) ?>" class="btn btn-warning js-need-confirmation"
             title="<?= $this->getChangeStatusLabel($item->getRevoked()) ?>"
             data-confirmation="<?= $this->getChangeStatusConfirmMessage($item->getRevoked()) ?>">
            <?= $this->getChangeStatusLabel($item->getRevoked()) ?>
          </a>
          <a href="<?= $this->getDeleteLink($item) ?>" class="btn btn-danger js-need-confirmation"
             title="<?= $this->__('Delete') ?>"
             data-confirmation="<?= $this->__('Are you sure you want to delete this application?') ?>">
            <?= $this->__('Delete') ?>
          </a>
        </td>
      </tr>

    <?php endforeach; ?>
    </tbody>
  </table>

  <?= $this->getToolbarHtml() ?>

<?php else: ?>

  <p class="text-info"><?= $this->__('You have no applications.'); ?></p>

<?php endif; ?>
