<?php if ($crumbs && is_array($crumbs)): ?>
  <ol class="breadcrumb">
    <?php foreach ($crumbs as $_crumbName => $_crumbInfo): ?>
      <li class="<?= $_crumbName; if ($_crumbInfo['last']) echo 'active'; ?>">
        <?php if ($_crumbInfo['link']): ?>
          <a href="<?= $_crumbInfo['link'] ?>" title="<?= $this->escapeHtml($_crumbInfo['title']) ?>">
            <?= $this->escapeHtml($_crumbInfo['label']) ?>
          </a>
        <?php else: ?>
          <?= $this->escapeHtml($_crumbInfo['label']) ?>
        <?php endif; ?>
      </li>
    <?php endforeach; ?>
  </ol>
<?php endif; ?>
