<?php
/**
 * @see Mage_Page_Block_Html_CookieNotice
 */
?>
<?php if (Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
  <div class="alert alert-warning clearfix" role="alert" id="notice-cookie-block">
    <?= $this->getCookieRestrictionBlockContent(); ?>
    <a id="allow-save-cookie"
       class="btn btn-default pull-right"
       data-cookie-name="<?= $this->escapeHtml(Mage_Core_Helper_Cookie::IS_USER_ALLOWED_SAVE_COOKIE) ?>"
       data-cookie-value="<?= $this->escapeHtml(Mage::helper('core/cookie')->getAcceptedSaveCookiesWebsiteIds()) ?>"
       data-cookie-expires="<?= $this->escapeHtml(Mage::helper('core/cookie')->getCookieRestrictionLifetime()) ?>"
       href="<?= Mage::getUrl('cms/index/noCookies') ?>"
      >
      <?= $this->__('Allow'); ?>
    </a>
  </div>
<?php endif; ?>
