<footer>
  <div class="container">

    <div class="footer-row">

      <div class="footer-col-sns">
        <?= $this->getChildHtml('cms_footer_links_sm') ?>
      </div>

      <div class="footer-col-newsletter">
        <?= $this->getChildHtml('newsletter') ?>
      </div>

      <div class="footer-col-cms-links">
        <?= $this->getChildHtml('cms_footer_links') ?>
      </div>

      <div class="footer-col-language-currency">
        <h5 class="footer-label">Language and Currency</h5>
        <div class="btn-group language-currency" role="group" aria-label="Language and Currency">
          <?= $this->getChildHtml('store_switcher') ?>
          <?= $this->getChildHtml('store_language') ?>
          <?= $this->getChildHtml('footer_currency') ?>
        </div>
      </div>

      <!-- Payment Support Icons -->
      <div class="footer-col-payment">
        <?= $this->getChildHtml('cms_footer_links_payment') ?>
      </div>

      <div class="footer-col-copyright">
        <?= $this->getCopyright() ?>

        <?php if (Mage::getStoreConfigFlag('catalog/seo/site_map')) : ?>
          <a href="<?= Mage::helper('catalog/map')->getCategoryUrl() ?>">Site Map</a>
        <?php endif ?>
      </div>
    </div>

  </div>
</footer>
