<footer>

  <div class="footer-row">
    <div class="footer-col-cms-links">
      <?php echo $this->getChildHtml('cms_footer_links') ?>
    </div>
    <div class="footer-col-quick-links">
      <?php echo $this->getChildHtml('footer_links') ?>
    </div>

    <div class="footer-col-sns">
      <?php echo $this->getChildHtml('cms_footer_links_sm') ?>
    </div>

    <div class="footer-col-newsletter">
      <?php echo $this->getChildHtml('newsletter') ?>
    </div>
  </div>

  <div class="footer-row">
    <!-- Payment Support Icons -->
    <div class="footer-col-payment">
      <?php echo $this->getChildHtml('cms_footer_links_payment') ?>
    </div>

    <div class="footer-col-copyright">
      <address><?php echo $this->getCopyright() ?></address>
    </div>
  </div>

  <!-- Store Switch -->

</footer>
