<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<header>
  <div class="container clearfix">

    <?php ob_start() ?>
    <a class="logo-link" href="<?= $this->getUrl('') ?>" title="<?= $this->getLogoAlt() ?>">
      <strong class="sr-only"><?= $this->getLogoAlt() ?></strong>
      <img class="logo" src="<?= $this->getLogoSrc() ?>" alt="<?= $this->getLogoAlt() ?>">
    </a>
    <?php $logoHtml = ob_get_clean() ?>

    <?php if ($this->getIsHomePage()) : ?>
      <h1 class="logo-container"><?= $logoHtml ?></h1>
    <?php else: ?>
      <div class="logo-container"><?= $logoHtml ?></div>
    <?php endif ?>

    <?= $this->getAdditionalHtml() ?>

  </div>
</header>

<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <div class="btn-group btn-group-menu" role="group">
        <div class="btn-group btn-group-catalog" role="group">
          <button type="button"
                  class="btn btn-primary btn-catalog"
                  data-toggle="collapse"
                  data-target="#nav-catalog"
                  aria-controls="nav-catalog"
                  aria-expanded="false"
            >
            <?= Mage::helper('vr_kiwiberry')->getSvgIcon('store') ?>
            <span class="btn-title"><?= $this->__('Category') ?></span>
            <span class="caret"></span>
          </button>
        </div>

        <div class="btn-group" role="group">
          <button type="button"
                  class="btn btn-primary btn-account dropdown-toggle"
                  data-toggle="dropdown"
                  aria-expanded="false"
            >
            <?= Mage::helper('vr_kiwiberry')->getSvgIcon('user') ?>
            <span class="btn-title"><?= $this->__('My Account') ?></span>
            <span class="caret"></span>
          </button>

          <?= $this->getChildHtml('topLinks') ?>
        </div>

        <?= $this->getChildHtml('minicart_head') ?>

        <div class="btn-group" role="group">
          <a href="<?= Mage::helper('checkout/url')->getCheckoutUrl() ?>"
             class="btn btn-primary btn-header-checkout"
            >
            <?= Mage::helper('vr_kiwiberry')->getSvgIcon('cashier') ?>
            <span class="btn-title"><?= $this->__('Checkout') ?></span>
          </a>
        </div>
      </div>

    </div>

    <div class="collapse navbar-collapse" id="nav-catalog">
      <?= $this->getChildHtml('topMenu') ?>
    </div>

    <?= $this->getChildHtml('topSearch') ?>

  </div>
</nav>
<?= $this->getChildHtml('topContainer'); ?>
