<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<title><?= $this->getTitle() ?></title>

<meta name="description" content="<?= htmlspecialchars($this->getDescription()) ?>">
<meta name="keywords" content="<?= htmlspecialchars($this->getKeywords()) ?>">
<meta name="robots" content="<?= htmlspecialchars($this->getRobots()) ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="icon" href="<?= $this->getFaviconFile(); ?>" type="image/x-icon">
<link rel="shortcut icon" href="<?= $this->getFaviconFile(); ?>" type="image/x-icon">

<?= $this->getCssJsHtml() ?>
<?= $this->getChildHtml() ?>
<?= $this->helper('core/js')->getTranslatorScript() ?>
<?= $this->getIncludes() ?>

