<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
?>
<?php if ($this->getCollection()->getSize()): ?>

  <?php if ($this->getUseContainer()): ?>
    <div class="pager-no-toolbar">
  <?php endif ?>

  <?php if ($this->getShowAmounts() || $this->getShowPerPage()): ?>
    <div class="count-container">

      <?php if ($this->getShowAmounts()): ?>
        <?php if ($this->getLastPageNum() > 1): ?>
          <p class="amount amount-has-pages">
            <?= $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
          </p>
        <?php else: ?>
          <p class="amount amount-no-pages">
            <strong><?= $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
          </p>
        <?php endif; ?>
      <?php endif ?>

      <?php if ($this->getShowPerPage()): ?>
        <div class="limiter">
          <label><?= $this->__('Show') ?></label>
          <select class="js-change-location" title="<?= $this->__('Results per page'); ?>">
            <?php foreach ($this->getAvailableLimit() as $_key => $_limit): ?>
              <option value="<?= $this->getLimitUrl($_key) ?>"
                <?php if ($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>
                >
                <?= $_limit ?>
              </option>
            <?php endforeach; ?>
          </select>
        </div>
      <?php endif ?>

    </div>
  <?php endif; ?>

  <?php if ($this->getLastPageNum() > 1): ?>
    <nav class="pagination-container">
      <ul class="pagination">
        <?php if (!$this->isFirstPage()): ?>
          <li>
            <a class="previous<?php if (!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif; ?>"
               href="<?= $this->getPreviousPageUrl() ?>"
               title="<?= $this->__('Previous') ?>">
              <?php if (!$this->getAnchorTextForPrevious()): ?>
                <span aria-hidden="true">&laquo;</span><span class="sr-only"><?= $this->__('Previous') ?></span>
              <?php else: ?>
                <?= $this->getAnchorTextForPrevious() ?>
              <?php endif; ?>
            </a>
          </li>
        <?php endif; ?>

        <?php if ($this->canShowFirst()): ?>
          <li><a class="first" href="<?= $this->getFirstPageUrl() ?>">1</a></li>
        <?php endif; ?>

        <?php if ($this->canShowPreviousJump()): ?>
          <li><a class="previous_jump" title="" href="<?= $this->getPreviousJumpUrl() ?>">...</a></li>
        <?php endif; ?>


        <?php foreach ($this->getFramePages() as $_page): ?>
          <?php if ($this->isPageCurrent($_page)): ?>
            <li class="active"><span><?= $_page ?><span class="sr-only">(current)</span></span></li>
          <?php else: ?>
            <li><a href="<?= $this->getPageUrl($_page) ?>"><?= $_page ?></a></li>
          <?php endif; ?>
        <?php endforeach; ?>


        <?php if ($this->canShowNextJump()): ?>
          <li><a class="next_jump" title="" href="<?= $this->getNextJumpUrl() ?>">...</a></li>
        <?php endif; ?>

        <?php if ($this->canShowLast()): ?>
          <li><a class="last" href="<?= $this->getLastPageUrl() ?>"><?= $this->getLastPageNum() ?></a>
          </li>
        <?php endif; ?>

        <?php if (!$this->isLastPage()): ?>
          <li>
            <a class="next<?php if (!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>"
               href="<?= $this->getNextPageUrl() ?>"
               title="<?= $this->__('Next') ?>">
              <?php if (!$this->getAnchorTextForNext()): ?>
                <span aria-hidden="true">&raquo;</span><span class="sr-only"><?= $this->__('Next') ?></span>
              <?php else: ?>
                <?= $this->getAnchorTextForNext() ?>
              <?php endif; ?>
            </a>
          </li>
        <?php endif; ?>
      </ul>
    </nav>
  <?php endif; ?>

  <?php if ($this->getUseContainer()): ?>
    </div>
  <?php endif ?>

<?php endif ?>
