<?php if (isset($poll)) : ?>
  <form id="pollForm" action="<?= $action ?>" method="post" role="form">
    <div class="panel panel-primary panel-collapse-mobile">

      <div class="panel-heading" role="tab" id="panel-heading-poll">
        <div class="panel-title">
          <a data-toggle="collapse"
             class="link-toggle-collapse"
             aria-expanded="false"
             aria-controls="panel-collapse-poll"
             href="#panel-collapse-poll">
            <?= $this->__('Community Poll') ?>
          </a>
        </div>
      </div>

      <div class="panel-collapse collapse"
           id="panel-collapse-poll"
           role="tabpanel"
           aria-labelledby="panel-heading-poll"
           aria-expanded="false"
        >
        <div class="panel-body">

          <p><?= $this->escapeHtml($poll->getPollTitle()); ?></p>

          <?php if ($poll_answers): ?>
            <?php foreach ($poll_answers as $answer): ?>

              <div class="radio">
                <label for="vote_<?= $answer->getId() ?>">
                  <input type="radio"
                         name="vote"
                         id="vote_<?= $answer->getId() ?>"
                         value="<?= $answer->getAnswerId() ?>"/>
                  <?= $this->escapeHtml($answer->getAnswerTitle()) ?>
                </label>
              </div>

            <?php endforeach; ?>
          <?php endif; ?>
        </div>

        <div class="panel-footer">
          <button type="submit" title="<?= $this->__('Vote') ?>" class="btn btn-default">
            <?= $this->__('Vote') ?>
          </button>
        </div>
      </div>

    </div>
  </form>
<?php endif; ?>
