<?php if (isset($poll)) : ?>
  <div class="panel panel-default">

    <div class="panel-heading">
      <?php echo $this->__('Community Poll') ?>
    </div>

    <form id="pollForm" action="<?php echo $action ?>" method="post" role="form">

      <div class="panel-body">

        <p><?php echo $this->escapeHtml($poll->getPollTitle()); ?></p>

        <?php if ($poll_answers): ?>
          <?php foreach ($poll_answers as $answer): ?>

            <div class="radio">
              <label for="vote_<?php echo $answer->getId() ?>">
                <input type="radio"
                       name="vote"
                       id="vote_<?php echo $answer->getId() ?>"
                       value="<?php echo $answer->getAnswerId() ?>"/>
                <?php echo $this->escapeHtml($answer->getAnswerTitle()) ?>
              </label>
            </div>

          <?php endforeach; ?>
        <?php endif; ?>
      </div>

      <div class="panel-footer">
        <button type="submit" title="<?php echo $this->__('Vote') ?>" class="btn btn-default">
          <?php echo $this->__('Vote') ?>
        </button>
      </div>

    </form>

  </div>
<?php endif; ?>
