<?php if (isset($poll)) : ?>
  <div class="panel panel-default">

    <div class="panel-heading">
      <?= $this->__('Community Poll') ?>
    </div>

    <form id="pollForm" action="<?= $action ?>" method="post" role="form">

      <div class="panel-body">

        <p><?= $this->escapeHtml($poll->getPollTitle()); ?></p>

        <?php if ($poll_answers): ?>
          <?php foreach ($poll_answers as $answer): ?>

            <div class="radio">
              <label for="vote_<?= $answer->getId() ?>">
                <input type="radio"
                       name="vote"
                       id="vote_<?= $answer->getId() ?>"
                       value="<?= $answer->getAnswerId() ?>"/>
                <?= $this->escapeHtml($answer->getAnswerTitle()) ?>
              </label>
            </div>

          <?php endforeach; ?>
        <?php endif; ?>
      </div>

      <div class="panel-footer">
        <button type="submit" title="<?= $this->__('Vote') ?>" class="btn btn-default">
          <?= $this->__('Vote') ?>
        </button>
      </div>

    </form>

  </div>
<?php endif; ?>
