<h1><?= Mage::helper('sales')->__('Orders and Returns') ?></h1>

<h2 class="legend"><?= Mage::helper('sales')->__('Order Information') ?></h2>

<form id="oar_widget_orders_and_returns_form"
      action="<?= $this->getActionUrl() ?>"
      method="post"
      role="form"
      class="js-validate-form"
      name="guest_post">

  <div class="form-group">
    <label for="oar_order_id" class="required">
      <?= Mage::helper('sales')->__('Order ID') ?>

    </label>
    <input type="text"
           class="form-control required-entry"
           id="oar_order_id"
           name="oar_order_id">
  </div>

  <span id="oar_help_block" class="help-block">
    <?= Mage::helper('sales')
      ->__('Enter the billing last name and email/ZIP as in the order billing address.') ?>
  </span>

  <div class="form-group">
    <label for="oar_billing_lastname"
           class="required">
      <?= Mage::helper('sales')->__('Billing Last Name') ?>

    </label>
    <input type="text"
           class="form-control required-entry"
           id="oar_billing_lastname"
           name="oar_billing_lastname"
           aria-describedby="oar_help_block">
  </div>

  <div class="form-group">
    <label class="required"><?= Mage::helper('sales')->__('Find Order By:') ?></label>
    <select name="oar_type"
            id="quick_search_type_id"
            class="form-control"
            title="<?= Mage::helper('sales')->__('Find Order By:') ?>"
            aria-describedby="oar_help_block"
            value="email">
      <option value="email">Email Address</option>
      <option value="zip">ZIP Code</option>
    </select>
  </div>

  <div class="form-group" id="oar-email">
    <label for="oar_email" class="required">
      <?= Mage::helper('sales')->__('Email Address') ?>

    </label>
    <input type="text"
           class="form-control validate-email required-entry"
           id="oar_email"
           name="oar_email"
           aria-describedby="oar_help_block">
  </div>

  <div class="form-group" id="oar-zip" style="display:none;">
    <label for="oar_zip" class="required">
      <?= Mage::helper('sales')->__('Billing ZIP Code') ?>

    </label>
    <input type="text"
           class="form-control required-entry"
           id="oar_zip"
           name="oar_zip"
           aria-describedby="oar_help_block">
  </div>

  <p class="text-danger"><?= Mage::helper('sales')->__('* Required Fields') ?></p>

  <button type="submit" title="<?= Mage::helper('sales')->__('Continue') ?>" class="btn btn-default">
    <?= Mage::helper('sales')->__('Continue') ?>
  </button>
</form>
