<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>
<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>

<?php if ($_specificInfo = $this->getSpecificInformation()): ?>
  <dl class="dl-horizontal">
    <?php foreach ($_specificInfo as $_label => $_value): ?>
      <dt><?php echo $this->escapeHtml($_label) ?></dt>
      <dd><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n")) ?></dd>
    <?php endforeach; ?>
  </dl>
<?php endif; ?>

<?php echo $this->getChildHtml() ?>
