<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>
<p><?= $this->escapeHtml($this->getMethod()->getTitle()) ?></p>

<?php if ($_specificInfo = $this->getSpecificInformation()): ?>
  <dl class="dl-horizontal">
    <?php foreach ($_specificInfo as $_label => $_value): ?>
      <dt><?= $this->escapeHtml($_label) ?></dt>
      <dd><?= nl2br(implode($this->getValueAsArray($_value, true), "\n")) ?></dd>
    <?php endforeach; ?>
  </dl>
<?php endif; ?>

<?= $this->getChildHtml() ?>
