<?php
/**
 * Catalog advanced search form
 *
 * @see Mage_CatalogSearch_Block_Advanced_Form
 */
?>

<h1><?= $this->__('Catalog Advanced Search') ?></h1>


<form action="<?= $this->getSearchPostUrl() ?>"
      method="get"
      id="form-validate-advanced-search"
      role="form"
      class="js-validate-form"
  >

  <h2 class="legend"><?= $this->__('Search Settings') ?></h2>

  <?php $maxQueryLength = $this->helper('catalogsearch')->getMaxQueryLength(); ?>

  <?php foreach ($this->getSearchableAttributes() as $_attribute): ?>
    <?php $_code = $_attribute->getAttributeCode() ?>
    <div class="form-group">

      <label for="<?= $_code ?>"><?= $this->getAttributeLabel($_attribute) ?></label>

      <?php switch ($this->getAttributeInputType($_attribute)):
        case 'number':
          ?>
          <div class="row">
            <div class="col-sm-5">
              <input type="text"
                     pattern="\d*"
                     name="<?= $_code ?>[from]"
                     value="<?= $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>"
                     id="<?= $_code ?>"
                     title="<?= $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"
                     class="form-control validate-number"
                     maxlength="<?= $maxQueryLength; ?>">
            </div>
            <div class="col-sm-2">
              <span class="separator">-</span>
            </div>
            <div class="col-sm-5">
              <input type="text"
                     pattern="\d*"
                     name="<?= $_code ?>[to]"
                     value="<?= $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>"
                     id="<?= $_code ?>_to"
                     title="<?= $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"
                     class="form-control validate-number"
                     maxlength="<?= $maxQueryLength; ?>">
            </div>
          </div>
          <?php break;
        case 'price':
          ?>
          <div class="row">
            <div class="col-sm-5">
              <input name="<?= $_code ?>[from]"
                     value="<?= $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>"
                     id="<?= $_code ?>"
                     title="<?= $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"
                     class="form-control validate-number"
                     type="text"
                     pattern="\d*"
                     maxlength="<?= $maxQueryLength; ?>">
            </div>
            <div class="col-sm-1">
              <span class="separator">-</span>
            </div>
            <div class="col-sm-5">
              <input name="<?= $_code ?>[to]"
                     value="<?= $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>"
                     id="<?= $_code ?>_to"
                     title="<?= $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"
                     class="form-control validate-number"
                     type="text"
                     pattern="\d*"
                     maxlength="<?= $maxQueryLength; ?>">
            </div>
            <div class="col-sm-1">
              <span>(<?= $this->getCurrency($_attribute); ?>)</span>
            </div>
          </div>
          <?php break;
        case 'select':
          ?>
          <?= $this->getAttributeSelectElement($_attribute) ?>
          <?php break;
        case 'yesno':
          ?>
          <?= $this->getAttributeYesNoElement($_attribute) ?>
          <?php break;
        case 'date':
          ?>
          <div class="row">
            <div class="col-sm-5">
              <?= $this->getDateInput($_attribute, 'from') ?>
            </div>
            <div class="col-sm-2">
              <span class="separator">-</span>
            </div>
            <div class="col-sm-5">
              <?= $this->getDateInput($_attribute, 'to') ?>
            </div>
          </div>
          <?php break;
        default:
          ?>
          <input type="text"
                 name="<?= $_code ?>"
                 id="<?= $_code ?>"
                 value="<?= $this->escapeHtml($this->getAttributeValue($_attribute)) ?>"
                 title="<?= $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"
                 class="form-control <?= $this->getAttributeValidationClass($_attribute) ?>"
                 maxlength="<?= $maxQueryLength; ?>">
        <?php endswitch; ?>
    </div>
  <?php endforeach; ?>

  <button type="submit" title="<?= $this->__('Search') ?>" class="btn btn-default">
    <?= $this->__('Search') ?>
  </button>

</form>
