<?php
/**
 * Catalog advanced search form
 *
 * @see Mage_CatalogSearch_Block_Advanced_Form
 */
?>

<h1><?php echo $this->__('Catalog Advanced Search') ?></h1>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<form action="<?php echo $this->getSearchPostUrl() ?>" method="get" id="form-validate-advanced-search" role="form">

  <h2 class="legend"><?php echo $this->__('Search Settings') ?></h2>

  <?php $maxQueryLength = $this->helper('catalogsearch')->getMaxQueryLength(); ?>

  <?php foreach ($this->getSearchableAttributes() as $_attribute): ?>
    <?php $_code = $_attribute->getAttributeCode() ?>
    <div class="form-group">

      <label for="<?php echo $_code ?>"><?php echo $this->getAttributeLabel($_attribute) ?></label>

      <?php switch ($this->getAttributeInputType($_attribute)):
        case 'number':
          ?>
          <div class="row">
            <div class="col-sm-5">
              <input type="text"
                     pattern="\d*"
                     name="<?php echo $_code ?>[from]"
                     value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>"
                     id="<?php echo $_code ?>"
                     title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"
                     class="form-control validate-number"
                     maxlength="<?php echo $maxQueryLength; ?>">
            </div>
            <div class="col-sm-2">
              <span class="separator">-</span>
            </div>
            <div class="col-sm-5">
              <input type="text"
                     pattern="\d*"
                     name="<?php echo $_code ?>[to]"
                     value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>"
                     id="<?php echo $_code ?>_to"
                     title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"
                     class="form-control validate-number"
                     maxlength="<?php echo $maxQueryLength; ?>">
            </div>
          </div>
          <?php break;
        case 'price':
          ?>
          <div class="row">
            <div class="col-sm-5">
              <input name="<?php echo $_code ?>[from]"
                     value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>"
                     id="<?php echo $_code ?>"
                     title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"
                     class="form-control validate-number"
                     type="text"
                     pattern="\d*"
                     maxlength="<?php echo $maxQueryLength; ?>">
            </div>
            <div class="col-sm-1">
              <span class="separator">-</span>
            </div>
            <div class="col-sm-5">
              <input name="<?php echo $_code ?>[to]"
                     value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>"
                     id="<?php echo $_code ?>_to"
                     title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"
                     class="form-control validate-number"
                     type="text"
                     pattern="\d*"
                     maxlength="<?php echo $maxQueryLength; ?>">
            </div>
            <div class="col-sm-1">
              <span>(<?php echo $this->getCurrency($_attribute); ?>)</span>
            </div>
          </div>
          <?php break;
        case 'select':
          ?>
          <?php echo $this->getAttributeSelectElement($_attribute) ?>
          <?php break;
        case 'yesno':
          ?>
          <?php echo $this->getAttributeYesNoElement($_attribute) ?>
          <?php break;
        case 'date':
          ?>
          <div class="row">
            <div class="col-sm-5">
              <?php echo $this->getDateInput($_attribute, 'from') ?>
            </div>
            <div class="col-sm-2">
              <span class="separator">-</span>
            </div>
            <div class="col-sm-5">
              <?php echo $this->getDateInput($_attribute, 'to') ?>
            </div>
          </div>
          <?php break;
        default:
          ?>
            <input type="text"
                   name="<?php echo $_code ?>"
                   id="<?php echo $_code ?>"
                   value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute)) ?>"
                   title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"
                   class="form-control <?php echo $this->getAttributeValidationClass($_attribute) ?>"
                   maxlength="<?php echo $maxQueryLength; ?>">
          <?php endswitch; ?>
    </div>
  <?php endforeach; ?>

  <button type="submit" title="<?php echo $this->__('Search') ?>" class="btn btn-default">
    <?php echo $this->__('Search') ?>
  </button>

</form>
