<?php
/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Options */
?>

<?php $options = $this->getOptionList(); ?>
<?php if ($options): ?>

  <?php ob_start() ?>
  <dl>
    <?php foreach ($options as $option): ?>
      <dt><?php echo $this->escapeHtml($option['label']) ?></dt>
      <dd>
        <?php if (is_array($option['value'])): ?>
          <?php echo nl2br(implode("\n", $option['value'])) ?>
        <?php else: ?>
          <?php echo $option['value'] ?>
        <?php endif; ?>
      </dd>
    <?php endforeach; ?>
  </dl>
  <?php $optionDetails = ob_get_clean() ?>

  <a href="#"
     class="js-wishlist-view-details"
     title="<?php echo $this->__('Options Details'); ?>"
     tabindex="0"
     role="button"
     data-toggle="popover"
     data-trigger="hover"
     data-html="true"
     data-placement="bottom"
     data-content="<?php echo $this->escapeHtml($optionDetails) ?>">
    <?php echo $this->__('View Details') ?>
  </a>
<?php endif ?>
