<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="page-header">
  <h1><?php echo $this->__('Share Your Wishlist') ?></h1>
</div>

<form action="<?php echo $this->getSendUrl() ?>" id="form-validate-share-wishlist" method="post">

  <?php echo $this->getBlockHtml('formkey') ?>

  <h2><?php echo $this->__('Sharing Information') ?></h2>

  <div class="form-group">
    <label for="email_address" class="required">
      <em>*</em>
      <?php echo $this->__('Email addresses, separated by commas') ?>
    </label>
    <textarea name="emails"
              rows="5"
              id="email_address"
              class="form-control validate-emails required-entry"><?php
      echo $this->getEnteredData('emails')
      ?></textarea>
  </div>

  <div class="form-group">
    <label for="message"><?php echo $this->__('Message') ?></label>
    <textarea id="message"
              name="message"
              class="form-control"
              rows="5"
      ><?php echo $this->getEnteredData('message') ?></textarea>
  </div>

  <?php if ($this->helper('wishlist')->isRssAllow()): ?>
    <div class="form-group">
      <label for="rss_url">
        <input type="checkbox"
               name="rss_url"
               id="rss_url"
               value="1"
               title="<?php
               echo $this->__('Check this checkbox if you want to add a link to an rss feed to your wishlist.') ?>"
          >
        <?php echo $this->__('Check this checkbox if you want to add a link to an rss feed to your wishlist.') ?>
      </label>
    </div>
  <?php endif; ?>

  <p class="text-danger"><?php echo $this->__('* Required Fields') ?></p>

  <div>
    <a href="<?php echo $this->getBackUrl(); ?>" class="btn btn-default">
      <i class="fa fa-angle-double-left"></i>
      <?php echo $this->__('Back') ?>
    </a>

    <button type="submit" title="<?php echo $this->__('Share Wishlist') ?>" class="btn btn-default">
      <i class="fa fa-share-alt"></i>
      <?php echo $this->__('Share Wishlist') ?>
    </button>
  </div>
</form>
