<?php if ($this->helper('wishlist')->isAllow()) : ?>



    <div class="my-wishlist">

    <div class="page-header">
      <?php if ($this->helper('wishlist')->isRssAllow() && $this->hasWishlistItems()): ?>
        <a href="<?= $this->helper('wishlist')->getRssUrl($this->getWishlistInstance()->getId()); ?>">
          <?= $this->__('RSS Feed') ?>
        </a>
      <?php endif; ?>
      <h1><?= $this->getTitle(); ?></h1>
    </div>

    <form id="wishlist-view-form"
          action="<?= $this->getUrl('*/*/update', array('wishlist_id' => $this->getWishlistInstance()->getId())) ?>"
          method="post"
          role="form">

      <?= $this->getChildHtml('top'); ?>

      <?php if ($this->hasWishlistItems()): ?>

        <?= $this->getBlockHtml('formkey'); ?>
        <?php $this->getChild('items')->setItems($this->getWishlistItems()); ?>
        <?= $this->getChildHtml('items'); ?>

      <?php else: ?>

        <p class="wishlist-empty"><?= $this->__('You have no items in your wishlist.') ?></p>

      <?php endif ?>

      <div>
        <?= $this->getChildHtml('control_buttons'); ?>
      </div>

    </form>

    <form id="wishlist-allcart-form" action="<?= $this->getUrl('*/*/allcart') ?>" method="post">
      <?= $this->getBlockHtml('formkey') ?>
      <input type="hidden"
             name="wishlist_id"
             id="wishlist_id"
             value="<?= $this->getWishlistInstance()->getId() ?>">
      <input type="hidden" name="qty" id="qty" value="">
    </form>

  </div>

  <?= $this->getChildHtml('bottom'); ?>

  <a href="<?= $this->escapeUrl($this->getBackUrl()) ?>" class="btn btn-default">
    <i class="fa fa-angle-double-left"></i>
    <?= $this->__('Back') ?>
  </a>
<?php endif ?>
