<?php
/**
 * Currency switcher
 *
 * @see Mage_Directory_Block_Currency
 */
?>
<?php if ($this->getCurrencyCount() > 1): ?>
  <div class="currency-switcher btn-group btn-group-sm dropup">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <?php echo Mage::helper('vr_kiwiberry')->getSvgIcon('currency') ?>
      <span class="title"><?php echo $this->__('Currency') ?></span>
      <span class="caret"></span>
    </button>

    <ul class="dropdown-menu" role="menu">
      <?php foreach ($this->getCurrencies() as $_code => $_name): ?>

        <li <?php if ($_code == $this->getCurrentCurrencyCode()): ?>class="active"<?php endif ?>>
          <a href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>">
            <?php echo $_name ?> - <?php echo $_code ?>
          </a>
        </li>

      <?php endforeach; ?>
    </ul>
  </div>
<?php endif; ?>
